### ISSUE TITLE
Build tool should utilize multicore processors

### ISSUE THREAD

**Issue by tsr8** [castle-engine/castle-engine#13]
Build tool and whole castle engine building should utilize multi-core CPUs.

There is "--threads=value" option in fpmake but it doesn’t work for now.

I found a clue that --threads option works if there are many packages to compile. We have only one.

**Comment by michaliskambi** [comment]
Sorry for taking so long to look into this!

I looked into it now, and I don't think this is really doable (at CGE side)... "fpmake" can use threads by calling multiple times FPC in parallel. For this, you not only need multiple projects, they also cannot depend on each other. This is confirmed by looking at ThreadsAmount documentation in fpc/trunk/packages/fpmkunit/src/fpmkunit.pp :

>    // When ThreadsAmount is specified, #threadsamount# worker-threads are
>    // created. When such a worker-thread is ready all worker-threads are evaluated
>    // to see if there are idle threads (there is always at least one such thread.)
>    // To each idle thread a package is assigned which has to be compiled for the
>    // current target and for which all dependencies are compiled earlier.
>    // When no package is available the thread remains idle until another thread
>    // has finished it's task. Compilation stops when all packages are compiled
>    // or when an error occures.

We don't have that luxury in Castle Game Engine units. See https://github.com/castle-engine/castle-engine/wiki/Units-Map . The unit groups all depend on each other. We could split them (like they are splitted into subdirectories now -- base, audio, x3d...). But the groups would tightly depend on each other, so the parallel compilation would not be possible anyway. You have to compile group "x3d" before you compile group "game", you have to compile group "castlescript" before you compile group "x3d" and so on.

Also, this assumes that FPC doesn't try to mistakenly recompile units when not needed. Which unfortunately sometimes happens, due to some FPC bugs (that also manifest in internal errors), sometimes caused by the usage of "inline" routines in the engine (for speed). These problems, right now, are a small nuisance -- sometimes FPC fails and you should just recompile (possibly cleaning before). If we would activate threads, these errors would be very bad, as multiple FPC instances would try to write the same ppu and o files at the same time.

So, using the option --threads with fpmake is not possible for us now...

Same answer goes for the Lazarus packages compilation, BTW. Since some time, Lazarus packages can be compiled in parallel. But this is also done by just executing FPC multiple times. Splitting cge into more Lazarus packages would not help --- as they would depend on each other.
