### ISSUE TITLE
Camera facing billboard problem (again)

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#148]
I rerun this test from the old forum and looks like billboard is broken again on my PC.

https://sourceforge.net/p/castle-engine/discussion/general/thread/882ca037/

**Comment by michaliskambi** [comment]
I investigated -- the reason for the breakage is different now than before :) Camera events reach all scenes correctly. 

However, you put the same scene CandyScene 4 times within the `SceneManager.Items`. This means that inside the scene, we don't know the "world transformation" to correctly orient our billboards. (In old engine versions, I think we didn't account for it correctly at all, it may have worked by accident.) In general, reusing the scenes like this is allowed, but all scenes must "have the same state" ( https://castle-engine.io/manual_scene.php#section_many_instances ), this unfortunately means that Billboards cannot work inside such scenes (since the local camera position/direction would be different in each scene instance, so each scene instance would have to orient the Billboard a bit differently.)

IOW: I'm not sure how did it work in 2015, but I think it was an accident (Billboards within TCastleScene probably didn't account for surrounding TCastleTransform at all). Right now, Billboards within scenes inserted multiple times to SceneManager.Items are not supported. (Changing this would require quite different Billboard implementation, so not something I can do easily now.)

Solution is to not reuse `CandyScene`. Instead of

```
CandyTransform.Add(CandyScene);
```

use (4 times)

```
CandyTransform.Add(CandySceneClone);
```

where `CandySceneClone` is defined like this:

```
function CandySceneClone: TCastleScene;
begin
  Result := CandyScene.Clone(Application);
  Result.Spatial:= [ssRendering, ssDynamicCollisions];
  Result.ProcessEvents:= true;
  Result.Attributes.Shaders:= srAlways;
end;
```

Note that `CandyScene.Clone` copies only the X3D nodes (stuff loaded by `CandyScene.Load`). So in `CandySceneClone` I just set the remaining fields as necessary. They also don't have to be initialized at `CandyScene` anymore (since `CandyScene` serves only as template to clone now).

I placed a complete working code on https://gist.github.com/michaliskambi/9520282717870d3be1511412754958e9 .
