### ISSUE TITLE
Error: Access Violation when import Spine files that contain clipping regions

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#150]
I open this issue to avoid PR derails.

More information can be shown here: https://github.com/castle-engine/castle-engine/pull/147

Sample Spine file: [test.zip](https://github.com/castle-engine/castle-engine/files/4014228/test.zip)

**Comment by michaliskambi** [comment]
Thank you, fixed!

Background: This was caused by invalid partial implementation of "clipping" attachment type. The "clipping" Spine attachment is still not supported (TClippingAttachment.BuildNodes is implemented, but `ClipPlane` X3D node needs an extension like `ClipPlane.global` to make it actually work.) But not it will make a normal warning, without any errors.

I understand that this testcase is public, so I added it to the test suite.
