### ISSUE TITLE
build-tool cannot copy DLL files when those file already existed in project directory

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#167]
On my Windows machine, whenever I tried to recompile project via build-tool I always got "EFCreateError" exception:

![image](https://user-images.githubusercontent.com/7451778/86991678-e1da7880-c1c9-11ea-9066-f321639ecb8c.png)

**Comment by michaliskambi** [comment]
Hm, it should be able to replace `.dll` files.

- Is the project (exe) running? 
- Or something else is using these dll files? (Possible if you put them on $PATH.)

Can you do a test by removing them manually, and doing doing `castle-engine compile` a few times one after each other? This one should work.

**Comment by michaliskambi** [comment]
I can reproduce it. My error message is a bit more descriptive:

```
Exception "EFCreateError":
Unable to create file "OpenAL32.dll": Proces nie może uzyskać dostępu do pliku,
ponieważ jest on używany przez inny proces.
```

The Polish part of the message (Windows returns it translated) says "Process cannot access the file, because it is used by another process". 

I'm investigating. 
- I can remove the `OpenAL32.dll` using the file explorer without any issue. 
- I can also remove it using Cygwin `rm -f *.dll`.  
- But what is using this file? If I try using `castle-engine compile` (without dll files present), and then immediately next `castle-engine compile` call says that the file is used. I don't know yet (Resource Manager doesn't tell me) what is using this file.

**Comment by michaliskambi** [comment]
Fixed.

The build tool itself was accidentally opening `OpenAL32.dll`, and in effect it was itself the process using it.

I already solved it long time ago :), but not completely. We had a compilation flag `CASTLE_DISABLE_DYNAMIC_LIBRARIES` to deal with this. But it was not used if you compiled the build tool using Lazarus LPI file and LPK packages. I changed it to a global variable that is always used.
