### ISSUE TITLE
Feature request: Dock ability for Castle Editor

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#169]
I open this issue to see if the community is interested in adding dock ability to Castle Editor.

Many people, including me, either own a widescreen monitor, or multi-monitor setup. Having dock ability helps us increase working space, by moving windows to other monitor, or let them dock to the left/right so that working space can make use of monitor's full height.

Things we need to do to add dock ability:
- Use a dock manager. Either [Anchor Docking](https://wiki.freepascal.org/Anchor_Docking) (used by Lazarus itself) or  [EasyDockingManager](https://wiki.lazarus.freepascal.org/EasyDockingManager).
- Separate components in TPageControl to their own form, and make the design window the dock master.

**Comment by michaliskambi** [comment]
I think it's a good idea. My curent editor design doesn't use docking, simply because it was easier to make. But in the long run, ability to detach some parts and move them around (e.g. like in Unity) is a good feature.

One requirement I would have, when implementing this, is to make sure there's an easy way to restore defaults. People sometimes undock by accident, or it's not OK if you later have to spend some time bringing your windows back to original state :) So, just a menu item like "Restore Default Layout" would be something I want.

**Comment by Kagamma** [comment]
A new docking mode is added in #322.

**Comment by Kagamma** [comment]
I am closing this issue as the PR got accepted to main repo.
