### ISSUE TITLE
Wavefront Obj differences from Blender 

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#178]
Today I collected some more free assets - this one's a CC0, part of an asset set you can find here https://fertile-soil-productions.itch.io/modular-village-pack, I've extracted one model to illustrate the issue

[broken_model.zip](https://github.com/castle-engine/castle-engine/files/5011539/broken_model.zip)

When viewed in view3dscene the model is all White whilst if imported into Blender its properly coloured. The reason is that the Specular is set to 1.0 1.0 1.0 as can be seen below...

```
newmtl Wood_Dark
Ka 0.0000 0.0000 0.0000
Kd 0.5176 0.4196 0.3333
Ks 1.0000 1.0000 1.0000 ### This looks wrong to me - that says White as I read it
Tf 0.0000 0.0000 0.0000  ### What's a Tf? I don't see it in the obj specs on Wiki
d 1.0000
Ns 0

```
Anyway, as I read it, view3dscene is right and everything else is wrong (Blender, Unity, Asset Forge) - not that I tried it in Unity, I did check the other two though. They display properly.

The problem is that being right isn't always best (I think CGE is right)

There's a horrible choice here. Do you cater for everything else being wrong and default to broken-obj-mode or what? From a purely public relations point of view even if CGE is right everyone will think it's broken if it doesn't act the same way as other popular applications.

**Comment by michaliskambi** [comment]
specular color = white is not a problem, usually. It means that specular reflections are pure white, but usually this doesn't make object just "unlit white". Only the specular reflections are white.

However, in case of this model, also _shininess_ ("specular exponent", https://en.wikipedia.org/wiki/Wavefront_.obj_file ) is zero. This is indicated by `Ns 0` in material file. Shininess equal exactly zero means that specular highlights just cover everything... which is neither realistic nor sensible :) Shininess acts as an exponent, and `power(anything, 0)` yields just 1.

I am guessing Blender and Unity don't show the problem, as they probably just ignore `Ns`, because they use physically-based lighting model (aka "PBR, physically-based rendering") by default, and there is no place to specify "shininess exponent" directly in the PBR model. CGE can do both physically-based lighting model, and Phong lighting model. In case of Phong lighting (which we use when loading from Wavefront OBJ, since this is what Wavefront OBJ material parameters describe) the shininess can be represented accurately, so we use it.

IOW, indeed, it is a problem inside a model (`Ns 0` makes no sense), and CGE is right, and others are wrong (because they probably ignore `Ns` value).

However, we can easily workaround it in CGE, without loosing any functionality :) I now just detect and ignore `Ns 0` special case (making a warning).

![Beach_Prop_Tree_Palm_1_0](https://user-images.githubusercontent.com/1076978/89838110-adf8c700-db6a-11ea-84aa-308c7878f3ef.png)

**Comment by peardox** [comment]
If Ns = 0 which as you state is not sensible and now ignore then shouldn't Ks also be ignored?

Manually editing the mtl and making this change (removing Ks) results at least in colour in a test object

[Possibly this following wants a new issue / trello]

The reason I want to get this consistent is that the model author has a lot of CC0 models - [see here](https://www.fertilesoilproductions.com/)

I was thinking about the comments you made regarding the amateur look of the models in demos + examples in reference to the gamesfromscratch recent video. This is, of course, easily fixable by using better models like the collection this guy has...

Extending this concept the main site's Gallery -> Graphics Assets currently links to a handful of models / images on opengameart.org. It would seem beneficial to all to expand that section to include a decent selection of free models - the one I mention is just bugging me 'cos of the bad mtl defs, there are actually a lot of decent models and 2d iso art freely available. A curated selection of assets would make it easier for beginners to get started. If we had such a gallery this could even be integrated into Editor at some point...

**Comment by michaliskambi** [comment]
`Ks` is a specular color. Ignoring `Ks` when we ignore `Ns` would be a hack very specifically for these models, so it doesn't feel like a good idea. In the future, someone else will come with buggy models, and have `Ns` equal zero but will want to preserve `Ks` :)

You can process these models in a number of ways using CGE, including setting SpecularColor for materials to 0 if you want after loading.

Looking at Blender OBJ importer, they also use `Ks`. However they render using physical materials, squeezing the Phong lighting parameters into PBR, which hides the troublesome specular value, as it is interpreted in different way by PBR.

I'm indeed always looking for a good collection of models. Note that for using them in the engine for demos, we need sources (in Blender) to be able to modify them as we like, we also like them prepared for PBR with proper textures. Static models are not that hard to get ( https://opengameart.org/ , blendswap.com/ , https://sketchfab.com/features/gltf have a number of nice models), good animations are much harder to find.
