### ISSUE TITLE
Incorrect texture coords when dynamic batching is enabled

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#179]
I dont know if this is intended or not, but this happen when I play around with dynamic batching in view3dscene:
- Without dynamic batching:
![image](https://user-images.githubusercontent.com/7451778/89658687-09bc1980-d8f9-11ea-8154-511fc5832c79.png)
- With dynamic batching:
![image](https://user-images.githubusercontent.com/7451778/89658732-180a3580-d8f9-11ea-9e42-1f48b05808ba.png)

Test model: [tests.zip](https://github.com/castle-engine/castle-engine/files/5042117/tests.zip)

Edit: I notice dynamic batching not working when IndexedFaceSet contains texCoordIndex / TextureCoordinate. So I wonder what's the exact requirements for it to work?

Btw it would be nice if we port Eugene Loza's 10000 cubes test on old forum to make use of dynamic batching:
https://sourceforge.net/p/castle-engine/discussion/general/thread/637c6b12/
This can be served as a nice example of how optimized the engine is when it's come to dynamic batching (almost all game engines I've tried have this kind of demo).

**Comment by michaliskambi** [comment]
Bug confirmed, thank you.

Automatic texture coordinate generation is used (because you specify `Appearance.texture`, but without any explicit texture coordinates). And the texture coordinate generation in case of `IndexedFaceSet` adjust to shape's bounding box. And this bounding box is of course larger if we treat both boxes as one single shape.

I'm not yet sure about the best fix. Maybe we should just disable dynamic batching in this case. Trying to fix it otherwise will be costly (we would need to generate texture coordinates at the batching moment, on CPU, adjusting to each shape's bounding box; this is very different from how these texture coordinates are done without batching, when they can be delegated to GPU).

Turning on `DynamicBatching` should never change the resulting geometry look. So this is definitely a bug.

> Edit: I notice dynamic batching not working when IndexedFaceSet contains texCoordIndex / TextureCoordinate. So I wonder what's the exact requirements for it to work?

The rules are kind of complicated, and encoded in `TBatchShapes.Collect` in `src/x3d/opengl/castleinternalbatchshapes.pas`. Indeed using `texCoordIndex` right now prevents batching. Using `TextureCoordinate` by itself is definitely still OK for batching.

These rules are not documented (yet), because they are complicated, and they can change, depending on the implementation. I fully expect these rules to change from time to time, and get even more complicated, if we start to employ some heuristics. 

> This can be served as a nice example of how optimized the engine is when it's come to dynamic batching (almost all game engines I've tried have this kind of demo).

I agree! I would like to have a demo showing 1000 cubes. I recall you also once showed a demo using 1000 sprites at one point. I would like to have demos that easily showcase how `DynamicBatching` helps. Added ticket https://trello.com/c/N7EWgiwR/51-a-demo-showing-1000-3d-cubes-1000-2d-sprites-to-show-that-dynamicbatching-helps-shows-fps-and-statistics-of-rendered-shapes-from .

**Comment by michaliskambi** [comment]
Fixed. The shapes that need automatic texture coordinate generation (i.e., have a texture, but don't have explicit texture coordinates) just don't participate in batching.

As all shapes from Spine or glTF in practice have explicit texture coordinates, this is probably not a big loss :)
