### ISSUE TITLE
Method naming inconsistency

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#183]
OK, I'm being pedantic again but...

CastleFilesUtils has StringToFile 
CastleDownload has StreamSaveToFile

If I know there's a StringToFile then I'm going to naturally search the API for StreamToFile (whichever one you know the other will be a wrong guess)

The choice of whether to include the word 'Save' is arbitrary as long as it's consistent

This could possibly be extended to other conceptual data-types, e.g. we could have NodeToFile (Save3d) and SceneToFile (is one defined?). I'm not sure which other <someData>To<someOtherData> are actually useful though.

**Comment by michaliskambi** [comment]
`StreamSaveToFile` is for consistency with standard `TMemoryStream.SaveToFile`, `TStringStream.SaveToFile` etc. The idea of  `StreamSaveToFile` is that we can do this on any `TStream` descendant.

`StringToFile` and `FileToString` are because it looks nice, consistent e.g. with `IntToStr` and `StrToInt`.

In general our loading routines follow `LoadXxx`, `SaveXxx` names. Like `LoadImage`, `SaveImage`, `LoadNode` (and `Save3D` should be `SaveNode`, I already have this in TODO). When they are methods, that are called just `Load` and `Save`  (on `TCastleSceneCore`). 

I'm all after consistency, but I don't feel we can do anything better in this particular case :), we cannot satisfy every possible argument. `StreamSaveToFile` makes perfect sense if you realize it's "like `SaveToFile` method on any `TStream`".

Ultimately, I am more concerned that search in our API docs doesn't work good enough. E.g. searching "stream save file" on https://castle-engine.io/apidoc-unstable/html/ doesn't find `StreamSaveToFile` (at least not within 10 first pages). Even though the search index "knows" about it, as searching explicitly for `StreamSaveToFile` finds it OK. Even searching DuckDuckGo or Google for "https://castle-engine.io/apidoc-unstable/html/ stream save to file" works better, but also very far from what we need. (Possibly because our routine is an anchor inside a larger www page; PasDoc is similar to e.g. Doxygen or JavaDoc here, and unlike FpDoc.) I would like to improve this within PasDoc some day.
