### ISSUE TITLE
SSL with castle_download (Command line) on macOS

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#184]
[Win10 + Linux are fine]

Well - apart from not supplying a second parameter (same issue as old download example) resulting in a exception

The Mac issue is to do with https downloads. Compiled with build tool...

```
./castle_download https://github.com/castle-engine/castle-engine/releases/download/snapshot/castle-engine-6.5-linux-x86_64.zip > cge-release.zip
Error when downloading "https://github.com/castle-engine/castle-engine/releases/download/snapshot/castle-engine-6.5-linux-x86_64.zip": Exception "ESocketError":
Connect to github.com:443 failed.

```

I mention this before the iOS issue as it may be linked to that issue - i.e. fixing this _may_ resolve both issues (so there will be no need to raise an issue for iOS).

This one's also easy to test on cloud Mac...

**Comment by peardox** [comment]
Found something important ....

This URL works - ./castle_download https://mtgatool.com/database/latest/en
This one fails - ./castle_download https://mtgjson.com/api/v5/Meta.json.gz (same if you req without .gz)
This one fails - ./castle_download https://decknet.co.uk/api/v5/Meta.json.gz (should 404 if you req without .gz)

The last one is a copy on a site I own - and I know how that one works...

Of particular note and a possible pointer is that decknet uses a https re-write so that a request for http turns into one for https (it's something that let's encrypt offers via certbot-auto)

It's possible that the site I'm actually after - mtgjson.com is also doing a rewrite...

**Comment by michaliskambi** [comment]
We need to figure out how to setup SSL downloading on macOS. This isn't really related to _Castle Game Engine_ (I suppose you can test FPC FpHttpClient implementation directly), but of course I'd like to know the solution anyway.

On iOS we'll also need to include OpenSSL library working for iOS. So macOS and iOS are actually separate problems.

The redirect from http->https should not matter, since in your examples you provide explicit https links. Also, FpHttpClient can deal with redirects just fine (also when they change http/https socket). Testing on Linux

```
./castle_download  https://decknet.co.uk/api/v5/Meta.json.gz  > a
```

shows that no redirects occur (the log is in `~/.config/castle_download/castle_download.log`, it says if there are any redirects). Same as `wget https://decknet.co.uk/api/v5/Meta.json.gz`, it would show redirect if any.

**Comment by peardox** [comment]
This don't explain why this one works though and the others don't

./castle_download https://mtgatool.com/database/latest/en

**Comment by peardox** [comment]
New discovery regarding SSL on Apple (may also affect #185)

There's a problem with fphttpclient which I've bug-track-submitted

Basically this appears to be a whitelisting issue as google.com if fine for https while freepascal.org is not

See https://bugs.freepascal.org/view.php?id=37747 for details

**Comment by michaliskambi** [comment]
Very curious. What happens when you try to use wget or curl from Homebrew? In principle they should work the same.

Unless they use custom ssl library to avoid the filtering.

Or unless it matters that application is "signed" (I'm not sure does it matter for command-line apps on macOS, I'm not sure whether Homebrew command-line apps are signed either).

I'm just speculating here. It is interesting if macOS ssl would do such filtering by default. And it's very interesting if it happens at ssl library, which seems like a wrong place to do such filtering, as ssl library doesn't know the domain name (only ip), and would only filter https not http... So why would they make filtering there?

Maybe the default ssl on macOS doesn't include some common certificate authorities, e.g. maybe it doesn't honor LetsEncrypt or Cloudflare certs? But that would also be crazy (a lot of sites would fail, even some big ones) so it doesn't seem likely either. I'm just guessing:)

**Comment by peardox** [comment]
Yeah, I tried wget on failing URLs while analysing the issue. It gets them perfectly.

I know that, e.g. Cordova gets you to whitelist domains for mobile bundling as they demand an app whitelist (even if it's * - which is discouraged). I thought that maybe they started using this is in desktop apps as well. There are some mentions of whitelisting but nothing definitive.

Something that'll be worth trying is a quick test with Delphi's inbuilt rest stuff going to a known current fail with fphttp - I'll install Delphi on one of the spare (crap) machines in a bit + give it a try

**Comment by peardox** [comment]
Well, after much messing around I've got the openssl with bugfix included in my project and it's merrily downloading a very large number files over https without any problem.

I ended up using a somewhat hacky way of overriding the openssl package and using my big-fix-applied one (stuck it in a subdir and added the subdir to the search path (well, it worked so I'm happy...)

After my test has done it's full 1.5 Gb run I'll see what happens with iOS using a hacked example download

**Comment by michaliskambi** [comment]
Testing now,
- with latest CGE,
- with latest FPC 3.3.1-r47824 [2020/12/20] for x86_64,
- on macOS Catalina

all work fine out-of-the-box:

```
./castle_download https://github.com/castle-engine/castle-engine/releases/download/snapshot/castle-engine-6.5-linux-x86_64.zip > cge-release.zip
./castle_download https://mtgatool.com/database/latest/en
./castle_download https://mtgjson.com/api/v5/Meta.json.gz
./castle_download https://decknet.co.uk/api/v5/Meta.json.gz
```

I see that https://bugs.freepascal.org/view.php?id=37747 is also marked as fixed on FPC side. I see from https://forum.lazarus.freepascal.org/index.php/topic,50350.msg373929.html that it's an issue with choosing SSL library  on macOS.

Testing with FPC 3.2.0, and (as you reported) only 2nd works.

```
$ ./castle_download https://github.com/castle-engine/castle-engine/releases/download/snapshot/castle-engine-6.5-linux-x86_64.zip > cge-release.zip
Error when downloading "https://github.com/castle-engine/castle-engine/releases/download/snapshot/castle-engine-6.5-linux-x86_64.zip": Exception "ESocketError":
Connect to github.com:443 failed.

$ ./castle_download https://mtgatool.com/database/latest/en
{"latest":"106","lang":"en","updated":1607301598319,"size":7589781}

$ ./castle_download https://mtgjson.com/api/v5/Meta.json.gz
Error when downloading "https://mtgjson.com/api/v5/Meta.json.gz": Exception "ESocketError":
Connect to mtgjson.com:443 failed.

$ ./castle_download https://decknet.co.uk/api/v5/Meta.json.gz
Error when downloading "https://decknet.co.uk/api/v5/Meta.json.gz": Exception "ESocketError":
Connect to decknet.co.uk:443 failed.
```

I don't think there's much more we can do with it on CGE side (I don't want to go into elaborate workaround in CGE, when FPC already fixed it), so I just expanded the error message, you will now get:

```
$ ./castle_download https://github.com/castle-engine/castle-engine/releases/download/snapshot/castle-engine-6$
Error when downloading "https://github.com/castle-engine/castle-engine/releases/download/snapshot/castle-engine-6.5-linux-x86_64.zip": Exception "ESocketError":
Connect to github.com:443 failed.
Warning: Https downloading with FPC 3.2.0 on macOS is broken for many hosts.
Upgrade to FPC 3.3.1.
See https://bugs.freepascal.org/view.php?id=37747 , https://github.com/castle-engine/castle-engine/issues/184 .
```
