### ISSUE TITLE
ExtractURIName with a query

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#190]
Pedantic hardly-a-bug time...

ExtractURIName() doesn't strictly do what it is documented as doing when it comes to Downloaded files.

For example I download https://c2.scryfall.com/file/scryfall-symbols/sets/cc1.svg?1598241600

ExtractURIName() returns cc1.svg?1598241600 which is an illegal filename

Of course, what's needed is either a URIExcludeQuery() or, more likely, default to doing that anyway...

Came across this when downloading hundreds of files named like the example so wrapped it in a URIExcludeQuery function.

**Comment by michaliskambi** [comment]
The family of functions `ChangeURIExt`, `DeleteURIExt`, `ExtractURIName`, `ExtractURIPath` was introduced to be a direct analogy of corresponding filename operations. In case of `ExtractURIName`, it is as simple as the docs say: `Extract filename (last part after slash) from URL.` ( It actually just calls `ExtractFileName` now, because it does what it should in case of both Windows and Unix. )

For now I prefer to keep this simplicity.

FPC features a `URIParser` unit, with `ParseURI`, `EncodeURI` routines that you can use for richer API to extract URL parts. See https://www.freepascal.org/docs-html/fcl/uriparser/index-5.html . This seems like more suitable in your case.
