### ISSUE TITLE
F1 in CGE editor should link to member correctly, even when member is part of an ancestor

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#191]
I think this modification should be pretty trivial

When using Design View of Castle Editor it would be extremely useful if pressing e.g. [F1] for help loaded the API page for the currently focused component in an external web browser.

I just found myself googling TCastleVerticalGroup for example (it didn't help much in this case)

The information provided would be improved if #177 was implemented - I'd hopefully get to see the documentation for the 'TODO: it's not possible to assign the events using the CGE editor' section here for example.

**Comment by michaliskambi** [comment]
Agreed, absolutely. I already had this in TODO.

- F1 on _Object Inspector_ should go straight to the documentation of proper property/event.
- F1 anywhere else when a design is open should open the documentation of given component.

This requires using RTTI to get the name of the unit where component resides (as PasDoc links contain unit name, since in Pascal the same class name can be repeated in multiple units) -- this should be definitely possible.

**Comment by michaliskambi** [comment]
BTW 

- This issue is not much related to #177 (which is about showing inherited member in PasDoc documentation, and is actually a ticket for PasDoc). Doing #177 is independent to this F1 feature. Of course both would improve the user experience of API docs.

- It's not related to search. Which is working fine in my tests:

    - If you search using DuckDuckGo for https://duckduckgo.com/?q=TCastleVerticalGroup it's actually quite useful. It shows 1st a wiki page where it's mentioned, 2nd commit where it's mentioned, and at 3rd place the API documentation page of it. 

    - Google shows the API documentation at 1st place.

    - Using our (PasDoc, Tipue) docs search also works OK if you just use the component name, https://castle-engine.io/apidoc-unstable/html/_tipue_results.html?q=tcastleverticalgroup .

**Comment by eugeneloza** [comment]
> I just found myself googling TCastleVerticalGroup for example (it didn't help much in this case)

I personally always have https://castle-engine.io/apidoc-unstable/html/ClassHierarchy.html as my first bookmark :) Using `ctrl+F` there can save a lot of time.

But yeah, backing this up. It's a very nice-to-have feature.

**Comment by michaliskambi** [comment]
Done. 

- F1 when some object inspector is focused -> goes to the member (property/event) of selected component
- F1 when no object inspector is focused, but design is open -> goes to the selected component
- otherwise it just goes to the homepage of API reference

There is one TODO remaining: right now it assumes that the current member is part of the selected component class. If it is a member of ancestor, then the URL is not correct (it will lead to the selected component, and anchor will be useless; instead it should link to ancestor). That is, e.g. F1 on `TCastleLabel.Text` correctly leads to the "Text" property docs. But F1 on `TCastleLabel.Exists` leads to `..../CastleControls.TCastleLabel.html#Exists` which is not correct (so it will just open the top of "TCastleLabel" docs), because `Exists`is part of ancestor `TCastleUserInterface`.

So in a way it's somewhat related to https://github.com/castle-engine/castle-engine/issues/177 after all, although I would not use https://github.com/castle-engine/castle-engine/issues/177 resolution for this anyway (the inherited members will be shown like JavaDoc after https://github.com/castle-engine/castle-engine/issues/177 , just a list that still links to ancestor, because that's both easier to do in PasDoc, and better for users to know what is where).

Leaving this issue open (but renamed title) until that last part is solved.

**Comment by peardox** [comment]
Hmm - Just tried it on Win10. Pressing F1 does nothing for me.

Recompiled everything

**Comment by michaliskambi** [comment]
> Hmm - Just tried it on Win10. Pressing F1 does nothing for me.
> Recompiled everything

It's definitely there. Even the binary release on https://castle-engine.io/ now contains the relevant commit. Just tested through WINE, pressing F1 works. Also menu item "Help -> API Reference of Current Component / Property" appears. 

Check do you have "Help -> API Reference of Current Component / Property" menu item. If not, you accidentally used the old editor exe.

**Comment by peardox** [comment]
Well, I dunno what went wrong with my earlier test but everything now works after another re-build

The addition of ancestor hierarchy (you mention above this is sorta #177 related) is the only missing feature I can see although my test did produce a sensible appearing URL - in my case https://castle-engine.io/apidoc-unstable/html/CastleControls.TCastleScrollView.html#WidthFraction.

One unintended consequence here is that now I'm taken directly to the (almost right) location I suddenly see where my little editor test is likely failing :)

**Comment by michaliskambi** [comment]
- F1 works now cool even when property belongs to ancestor, e.g. using it on `TCastleScene.Url` will correctly go to `TCastleSceneCore.Url`.

- As a bonus, we even go to FPC or LCL reference, as needed. If you use F1 on `Name` or `Tag` (from `TComponent`), we will go to proper FPC page.

- Also fixed behavior for vector properties, so that e.g. F1 on `TCastleScene.Translation` works as expected (internally this case is resolved specially, as we publish vector properties through special `XxxPersistent` instances, but engine user should not even notice this).
