### ISSUE TITLE
Castle Editor Tab Order

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#193]
This one is really trivial (but also important of course)

When you create a New Project in CGE Editor the tab order is 'annoying' making Editor feel like a work in progress (which it is, and always will be, I guess).

1 - You click on a Template (this is not a tab stop)

2 - Tab skips past project location and goes to Project name (this is actually OK as you'll rarely want to alter the root project directory)
3 - Tab now takes you up one one to Project name  - there is no way to click on the 'Choose Directory' button without a mouse.
4 - Tab now skips down two to Project Title
5 - Tab takes you to create project but there is no visual indication that you're on that tab (there probably should be)
6 - Tab takes you to cancel (this is visually indicated)

[Loop to 2]

I imagine the really annoying bit (2 - 4) crept in when you added the Project Title input

Oh, just noticed that without a mouse you can only ever select 'Empty Project'.

**Comment by michaliskambi** [comment]
Yeah totally agreed. The bug is a consequence of 2 things

1. I used TSpeedButton (that is not selectable by keyboard, i.e. Tab). I do not recall the details now, but for some reason I could not get the right button class in LCL (TGlyphButton) to have a look I desired.

2. And yes, I also just forgot to adjust tab order after adding "Project Title" :)

Will fix it ASAP.

**Comment by peardox** [comment]
AS @eugeneloza is hoping to finish off the right-click stuff this w/e the editor should suddenly be a lot more usable

**Comment by michaliskambi** [comment]
The proper tab order on "New Project" form is now fixed. 

Button "Choose Directory" is now also in tab order, and can be activated by keyboard. (It is no longer TEditButton, which was using TSpeedButton.)

The buttons to choose the project template will unfortunately stay selectable only by the mouse. There  is no sane way to do these buttons otherwise in Lazarus.

- Only TSpeedButton can be in pressed/released state (`Down`) and has an image `Glyph`. But it doesn't get keyboard focus.
- TButton has no way to set pressed/released state or image.
- TBitBtn has no way to set pressed/released state.
- TToggleBox has no way to set image.You cannot workaround it by adding image as a child (in LCL, you cannot make arbitrary UI control a child of another) or making image control in front (for some inexplicable reason, image control is always in the back).

So there is just no button class that does what we need, as far as I see.

**Comment by peardox** [comment]
Menu ShortCuts...
