### ISSUE TITLE
TCastleDownload leaks if HttpResponseCode <> 200

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#199]
You've got the fixed code from #198 - this is perfect to illustrate this issue as I left an exception handler in there.

Change the URL you download in (fixed) dltest to https://peardox.com/HTTPErrorCode/404

https://peardox.com/HTTPErrorCode/<come error code> is something I threw together to test HTTP  errors, it's very simplistic ATM simply returning whatever code you ask it for.

Anyway it looks like you're not cleaning up after you raise the exception - something is left hanging around (I think the culprit is in castledownload_url_http_fphttpclient.inc - you raise an exception at line 254, possibly Client is left dangling?)

**Comment by michaliskambi** [comment]
It's an error in your code. Early on you set `fDownload.OwnsContents := False` but when `dsError` occurs, you ignore the `fDownload.Contents` (you do not copy it to `Stream` or `Result` variables and you never free it).

Remember that when HTTP error occurs, the `fDownload.Contents` still contains some content (because that's how HTTP works, server may still send some answer along with non-200 code, in fact it's normal with REST communication). It's documented at `TCastleDownload.Contents` explicitly.

The straightforward (working but ugly) solution is to replace

```
        dsError:
            Memo1.Lines.Add('Download error : ' + fDownload.ErrorMessage);
```

into

```
        dsError:
          begin
            Memo1.Lines.Add('Download error : ' + fDownload.ErrorMessage);
            fDownload.Contents.Free;
          end;
```

( I just tested and it indeed removes the leak. But it's ugly solution, as it leaves for some time dangling pointer in `fDownload.Contents`, even though it is not accessed by anything anymore. )

The better solution, that I would advise, is to *not* set `fDownload.OwnsContents := False` early. Instead, leave `fDownload.OwnsContents` at default (`true`) until you receive `dsSuccess`. Then copy the `fDownload.Contents` and at the (almost) same time set `fDownload.OwnsContents`. So instead of

```
        dsSuccess:
          Stream := fDownload.Contents;
```

you would make

```
        dsSuccess:
          begin
            Stream := fDownload.Contents;
            fDownload.OwnsContents := False;
          end;
```
