### ISSUE TITLE
TCastleImage overrides mouselook=true cursor

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#2]
By default mouselook:=true hides the cursor (which is right), but if there is a transparent TCastleImage crossing the center of the viewport, then the cursor becomes visible.
(not really important, just to keep track of that issue)

**Comment by michaliskambi** [comment]
I initially wrote here an elaborate answer how it's "by design": the front-most control dictates the cursor look, and MouseLook is only a property of a camera (and then viewport) that can be covered by other UI controls.

But then I realized that we can nicely solve it. Done:)

If you're curious, it's in https://sourceforge.net/p/castle-engine/code/14868/ , I added a Cursor mode "mcForceNone", which allows to hide the cursor --- regardless if the control is front-most or not.

**Comment by eugeneloza** [comment]
Great! Thanks a lot!!! (Because eventually I'll have a crosshair right in the center of the viewport)
