### ISSUE TITLE
TCastleDownload is hiding exceptions

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#203]
The easiest way to see this is to deliberately try to download something from a non-existent host

I came across this while downloading a big stress test on my code, downloading 54,500 images. If those five returned an error on the first run (I only know there were four response 0 and one response 503). I updated the error reporting to include the ErrorMessage and re-ran the missing ones (code is a big cache so it skipped the 54,495 OK ones)

My tests show these results - artificially generated using a deliberate bad URI...

> Error Downloading : https://noapi.peardox.co.uk/prices/prices.json.gz
> ErrorMessage : Error when downloading "https://noapi.peardox.co.uk/prices/prices.json.gz": Exception "ESocketError":
> Host name resolution for "noapi.peardox.co.uk" failed.
> HttpResponseCode : 0
> 

Notice that the exception is an ESocketError, not the EDownloadError that replaces the original EClientError.

The result of this is that an exception is raised but then hidden again with a response code of zero.

The point here is that while I know if I got something OK or I got some bad HTTP response I can't tell if I got something weird

While 5 out of c55k is a small miss rate it's going to happen eventually. The URIs were all actually fine but something weird happened between making the request and getting something back (The debugger reported a host resolution error when first observed - hence choosing that for the example above)

**Comment by michaliskambi** [comment]
TCastleDownload indeed catches exceptions inside. Because otherwise they could occur from a point of your application where you cannot easily capture them. Also I wanted to avoid specifying the possible exception classes (as they are platform-dependent; we could alternatively wrap them all in EDownloadError, but then differentiating by looking at exception class would not be useful anyway).

So exceptions are converted into Status = `dsError` and the message is inside `ErrorMessage`. You detect failure by looking at `Status`.
 
The `HttpResponseCode` is 0 because there is no HTTP response when DNS fails. The request failed before any HTTP(S) communication occurred. Having `Status = dsError` and `HttpResponseCode = 0` tells you that something bad happened before HTTP request, or that HTTP answer was incorrect (0 is not a valid response from HTTP server). That is actually already hidden in `FpHttpClient`.
