### ISSUE TITLE
Confusing Editor Hierarchy

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#217]
Please note that the following is not about the superb work @eugeneloza has done on the Right-Click/Undo etc stuff.  

This is another usability issue.

This image was created at the end of July 2020 - can you spot the suspect layout? Note that this one has no Root (at least you can't do this any more)

![broken-tree-clipped](https://user-images.githubusercontent.com/1549219/97101063-f9167680-1691-11eb-9879-13d888e63c8f.png)

And here's one from latest (so three months later)

![broken-tree-2](https://user-images.githubusercontent.com/1549219/97101089-44308980-1692-11eb-9181-04dbab9974d4.png)

So, a button can contain anything? Well, actually of course it can. Can you think of any situation where you'd actually put a progress bar inside a button? Possibly but it's not overly useful.

IMHO there should be two modes of operation - one with a 'normal ownership' tree and an optional 'do whatever you like' mode (AKA - the current state). I do rather think that the DWYL option would actually only be use when testing the Editor...

The 'normal operation' tree should have a sensible structure showing only the controls that make sense as a child of the parent. A Button may have an image, I guess but definitely not a Vertical Group or Tiled Map as a child.

I suggest that each control have the minimal number of sensible children available.

One control that's always bugged me is the label as it can be the equivalent of a Lazarus TLabel or TMemo. The former shouldn't be allowed a button child while the latter is possible (not clever but not illegal)

As a general issue many controls actually I would guess are properly children of a TRectangle to some extent and used to build a UI. That kind of discussion is probably best left for now as It'll cause more confusion...

**Comment by eugeneloza** [comment]
> only the controls that make sense as a child of the parent. A Button may have an image, I guess but definitely not a Vertical Group or Tiled Map as a child.

Well, the fact here is that these things actually can and do happen. The button can literally contain... anything. The problem is that when we say "button" we don't actually mean real button - we mean an object with `OnClick` event. So in this case, yes, the button can contain `TCastleVerticalGroup`, e.g. listing the rewards the player gets for pressing this button, or even `TiledMap` which is a preview of the map the player returns to when pressing the button.

E.g. this is a button from Escape from the Universe: It contains at least `TCastleHorizontalGroup` and half a dozen of other UIs:

![Clipboard 1](https://user-images.githubusercontent.com/10726162/97105748-1107ed80-16c6-11eb-8054-6af77ef73cd7.png)

So, yeah, Button inside a Button may be confusing and is not recommended, but it's more up to the developer to choose what is good and what is bad. I can imagine a situation when the whole design is a button (e.g. a popup - click to close) but there are multiple other interactive elements inside.

I'm not sure about an option. "Sensible structure showing only the controls that make sense as a child of the parent" sounds really tempting, but I'm not exactly sure how it will perform from UX perspective. At which point the "convenience for an everyday task" (button with Image and Label) will force the user into confusing "How can I add a scrollbar to the button that would control how many resources will be sold when pressing this button" or "Why I can't add scrollable content to the button, but I can add an image to the button and add scrollable content inside this image"?

We might sort the possible children - so that the often used ones will come at the top of the list - that may cause more harm than good, e.g. when adding dozens of buttons you usually already know it's place in the list and surprise it's not there because in this situation it's a recommended component and it moved to the top.

Same goes with putting those into a deeper submenu. Just like "Basic" tab in Object Inspector does. I always lack some often-used features in "Basic" tab.

IMO the only way that this might provide better UX - is highlight "often used stuff" in bold.

On the other hand I'd rather vote out "Button Custom Image and Label" in favor of "Button with Rollover Image and Label as Children" - because usually the first thing I do with button design is remove initial image to use Custom images and remove the button Caption to place a more versatile Label inside. Yes, it's not easy to alter this design pattern, including the fact that Rollover Image does not exist yet, so I'm not proposing this change just yet.

**Comment by michaliskambi** [comment]
Yes, any TCastleUserInterface can contain any other TCastleUserInterface. This is useful. The fact that a button can contain other controls is actually very useful and has real use-cases. Eugene above already mentioned this. In general, TCastleButton may be used as just "anything that reliably captures OnClick event".

Having a root that is any TCastleUserInterface is also useful. This allows to wrap any control hierarchy in a file. It's like a prefab in Unity for UI elements. It allows to reuse it later using TCastleDesign. So e.g. you can wrap this "button with extra controls inside" in a .castle-user-interface file, and then reuse it (loading from code by `UserInterfaceLoad` or by TCastleDesign).

And at least Unity has the same freedom. UI element is just a GameObject, and you can put any children there. I have not heard of this being any real problem for anyone.

That said, I get your problem with usability of this solution. We may think how to address this best. One way is simply to explain it, clearly, which comes down to making documentation and videos about the editor -> which is coming.

But the approach "anything can be inside anything" should stay, and should be allowed without any fuss (not hidden in any special 'do whatever you like' mode).
