### ISSUE TITLE
Exception when loading X3d File with sound

### ISSUE THREAD

**Issue by stievie** [castle-engine/castle-engine#23]
Hi,

first of all, this is an awesone engine!

For the moment i have a problem when loading a level with X3D models which contain sounds, e.g.:

~~~
PROTO Door [ ] {
  Group {
    children [
      DEF TimerOpen TimeSensor { 
        cycleInterval 0.5
      }
      DEF TimerClose TimeSensor { 
        cycleInterval 0.5
      }
      
      DEF DoorNode Inline { 
        url "door_final.x3d" 
      }
      
      Sound {
        intensity 0.5
        source DEF DoorOpenSound AudioClip {
          url "../sounds/door_open.wav"
        }
      }
      Sound {
        intensity 0.5
        source DEF DoorCloseSound AudioClip {
          url "../sounds/door_close.wav"
        }
      }
# Stuff...      
~~~

The problem is, when it loads the X3D model it calls `TRepoSoundEngine.LoadSoundsBuffers` which initialized the progress bar. But this progress bar is already active when loading a level. This means it raises an Exception.

To avoid this i don't call the progress bar in `TRepoSoundEngine.LoadSoundsBuffers` at all when its active:

~~~pas
procedure TRepoSoundEngine.LoadSoundsBuffers;
var
  ST: TSoundType;
  ProgressActive: boolean;
begin
  { load sound buffers and allocate sound for music. Only if we have any sound
    (other than stNone). }
  if ALActive and (Sounds.Count > 1) then
  begin
    ProgressActive := Progress.Active;
    if not ProgressActive then
      Progress.Init(Sounds.Count - 1, 'Loading sounds');
    try
      { We do progress to "Sounds.Count - 1" because we start
        iterating from ST = 1 because ST = 0 = stNone never exists. }
      Assert(Sounds[stNone].URL = '');
      for ST := 1 to Sounds.Count - 1 do
      begin
        if Sounds[ST].URL <> '' then
        try
          Sounds[ST].FBuffer := LoadBuffer(Sounds[ST].URL);
        except
          on E: Exception do
          begin
            Sounds[ST].FBuffer := 0;
            WritelnWarning('Sound', Format('Sound file "%s" cannot be loaded: %s',
              [Sounds[ST].URL, E.Message]));
          end;
        end;
        if not ProgressActive then
          Progress.Step;
      end;
    finally
      if not ProgressActive then
        Progress.Fini;
    end;

    MusicPlayer.AllocateSource;
  end;
end;
~~~

**Comment by michaliskambi** [comment]
Thank you for reporting *and* fixing this! I applied your correction exactly.

Yeah, that's an unfortunate problem with current Progress.Init / Fini API. A Progress cannot be used while another Progress is ongoing, and we cannot simply ignore this (because then one operation would shift the progress of another operation, they would "fight" for the progress UI). I could have designed the progress API better, probably. In the meantime, this is the necessary solution, to check whether Progress is Active before, exactly like you did.

Unrelated to this issue: I also read your https://0x2a.wtf/projects/cube/ . I will watch it with great interest:) You mention there the lighting quality -- for much more detailed lighting in our engine, try 

1. using "Scene.Attributes.Shaders := ssAlways". You can test it in view3dscene with "Shaders->Enable For Everything". This turns on Phong shading which often looks much better (and is much slower...). You can also turn Phong shading selectively only for some shapes using this extension: http://castle-engine.sourceforge.net/x3d_extensions.php#section_ext_shading .

2. using bump mapping. You will need to create extra normalmap textures, and indicate them using this extension to X3D http://castle-engine.sourceforge.net/x3d_implementation_texturing_extensions.php#section_ext_bump_mapping or by material_properties.xml file: http://castle-engine.sourceforge.net/creating_data_material_properties.php . The examples/fps_game/ data has a simple demo of it. Bump mapping also causes a Phong shading and related slowdown, unfortunately.

**Comment by stievie** [comment]
Great, thanks, now I can just pull from your repository again.

Oh, Cube is just a fun project, just playing around :-). What fascinated me was how easy it was to get it working so far with your engine compared to Unreal. There was almost no Pascal code required. It was basically put together in one day.

Also thanks for your advice concerning lightning, Ill try it. Of course it still needs a lot fine tuning.
