### ISSUE TITLE
Castle-engine build-tool blindly copies DLLs (Windows)

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#233]
This is specifically noticeable if you re-boot rarely (like me) and most easily replicated by bootstrapping castle-engine.

A new pull often requires a rebuild of castle-engine, on Windows the easiest method of doing this is to cd to tools\build-tool, rename castle-engine then use that renamed version to clean and build a new version.

i.e.

cd src\castle-engine
git pull
cd tools\build-tool
ren castle-engine.exe ce.exe
.\ce clean
.\ce compile

And... it won't work... IF you've run castle-engine/ce at all this boot

The reason for this is that tool (whatever it's named for this run) will try to over-write zlib1.dll and libpng14-14.dll. These dlls will, however, already be in use from any previous build so the compilation fails.

The only work-around is to reboot the PC and repeat the process. This time the DLLs ain't loaded and so are not a problem.

It seems to me that an 'identical file' check would be appropriate. e.g. if a zlib1.dll already exists only try to overwrite it if a sha512 check of source + destination differ (and inform user of the issue if it fails).

**Comment by michaliskambi** [comment]
You don't need to reboot, but you need to kill any other process using these DLLs.

For build tool locking itself -- hm, we already have a solution exactly for this: https://github.com/castle-engine/castle-engine/blob/master/tools/build-tool/code/tooldisabledynamiclibraries.pas . Build tool should not use these DLLs, thus it should not "lock" them on Windows.

I'll see if/why we broke it.

**Comment by michaliskambi** [comment]
I cannot reproduce the problem. Look into the "Process Manager", do you have some process running using these DLLs? Because 1. the build tool doesn't use these DLLs at all, 2. even if it did, it would only use them temporarily, so rebooting is not necessary, it's only a matter of killing the appropriate process. Our mechanism in https://github.com/castle-engine/castle-engine/blob/master/tools/build-tool/code/tooldisabledynamiclibraries.pas works OK.

Tested (note that I use Cygwin, so you see Unixisms here, but it's on Windows, so exe/dll locking is the same):

```
$ cd tools/build-tool/
$  ./castle-engine_compile.sh # this is the way to compile without starting with build tool, but it requires Cygwin
...
$ ./castle-engine compile # this will correctly fail, as castle-engine.exe is locked
...
Linking code\castle-engine.exe
777 lines compiled, 3.1 sec, 4208832 bytes code, 1320372 bytes data
Moving code/castle-engine.exe to castle-engine.exe
Exception "Exception":
Cannot rename/move from "....code/castle-engine.exe" to "..../castle-engine.exe"
$ mv castle-engine.exe ce.exe
$ ./ce.exe compile
... works OK
... I can repeat in any order 
      $ ./ce.exe compile
      $ ./ce.exe clean
      $ ./ce.exe --project ../../examples/fps_game/ compile # compile other projects 
      $ ./castle-engine.exe --project ../../examples/fps_game/ compile
```

Just to be sure, I repeated the process outside of Cygwin, with `cmd` on Windows.

An idea: do you maybe have some other process, like CGE game, or maybe something unrelated to CGE, using these DLLs? This is possible if you added the build tool directory to the `PATH`. I didn't observe it myself, but if you have 

- a CGE game (or any non-CGE application) using e.g. `zlib1.dll`, you keep this game running in the bv

**Comment by michaliskambi** [comment]
As for your last suggestion -- I would not like to have a mechanism that does "identical file check". It would be a band-aid, hiding the problem in 99% cases, but the problem would still be there (in case CGE update actually changes some DLL). These DLLs just cannot be "locked" to make building work OK.

**Comment by peardox** [comment]
I have ...

`the build tool directory is on $PATH,`
