### ISSUE TITLE
Forced "power-of-2" texture size of Starling sprite sheet

### ISSUE THREAD

**Issue by PNSee** [castle-engine/castle-engine#249]
I'm developing a simple 2D game with sprite sheet animations. Until now I've been using an old TSprite implementation. Now I've decided to load sprite as a scene (as described in the [recent wiki article](https://github.com/castle-engine/castle-engine/wiki/Sprite-sheets)). Having researched the specification of Starling sprite sheet, I've made XML file, set up a viewport with proper settings and successfully loaded the sprite with walk cycle animation. 

All seemed well until I noticed that the "scene" character looked more blurry than old "sprite character". I loaded the scene via view3dscene and noticed that there is more pixels in sprite than intended. Here's comparison between implementations:
![forced_power_of_2](https://user-images.githubusercontent.com/46522630/108592071-1546cd80-737d-11eb-8605-484a71e9932e.png)

Now, in static, it doesn't seem that bad. However, in motion, the sprite becomes shaky and blurry. I aimed at pixel-perfect implementation of character sprites, so that obviously wasn't the result I expected from TSprite substitute.

After digging into engine's source code I figured out that in [X3DLoadInternalImage unit](https://github.com/castle-engine/castle-engine/blob/8ddc36d2b9b7e5e6b3a088423f7e6dc3cfaa6c74/src/x3d/x3dloadinternalstarling.pas), in PrepareShape procedure I need to set a Texture Properties node (like in [X3DLoadInternalImage](https://github.com/castle-engine/castle-engine/blob/8ddc36d2b9b7e5e6b3a088423f7e6dc3cfaa6c74/src/x3d/x3dloadinternalimage.pas)), which would contain a GUITexture property set to True:
```
TexProperties := TTexturePropertiesNode.Create;
TexProperties.MagnificationFilter := magDefault;
TexProperties.MinificationFilter := minDefault;
{ Do not force "power of 2" size, which may prevent mipmaps.
  This seems like a better default (otherwise the resizing underneath
  may cause longer loading time, and loss of quality, if not expected). }
TexProperties.GuiTexture := true;
Tex.TextureProperties := TexProperties; 
```
In this case, the Starling sprite would be rendered as is, without any artifacts.

Now that begs the question: is there a feasible way to set sprite's texture into GUITexture mode on a high level (without the need for altering the engine itself)?

**Comment by and3md** [comment]
Hi @PNSee How about change `RenderOptions` in your sprite scene:

```
Scene.RenderOptions.MagnificationFilter := magNearest`
Scene.RenderOptions.MinificationFilter := minNearest
```

Is `play_animation` example (in examples/animations) working OK for your sprite sheet (with checked "Nearest" options in display section) ?

**Comment by PNSee** [comment]
Screenshots I've provided earlier were made in view3dscene with both magnification and minification filters set to Nearest.

**Comment by peardox** [comment]
As a general note you may also want to set [bs2D](https://castle-engine.io/apidoc-unstable/html/CastleRenderOptions.html#bs2D) for a 2D application using scenes

The power of 2 stuff is, I think, for the GPU to handle things better. One option that occurs to me is that you do something to bypass the forced power of 2, I have textures that are 745x1040, the dumb power of 2 stuff makes them 1024x2048. 1024x1024 in my case is much more sensible so I pre-size my texture in code to 1024x1024 before using the new TTexture.[LoadFromImage](https://castle-engine.io/apidoc-unstable/html/X3DNodes.TImageTextureNode.html#LoadFromImage) method.

In your case it seems feasible to simply re-construct the sprites adding a transparent border to make them power of 2 friendly. Yeah, experimentation hassle, but its automatable and you only have to do it once - when happy with the result you could 'bake' them to avoid the resize step (assuming you desire sizing flexibility)

**Comment by and3md** [comment]
@PNSee  Oh, I understand now. I usually use power of two sizes (many texture compression algorithms need that) so I never saw that bug. 
@michaliskambi Maybe we should set `GuiTexture` to `true` when image size is not power of two, by default?

**Comment by and3md** [comment]
> In your case it seems feasible to simply re-construct the sprites adding a transparent border to make them power of 2 friendly. Yeah, experimentation hassle, but its automatable and you only have to do it once

Exactly! I think this is the best solution and it will be even easier when the [Castle sheet sprite editor](https://github.com/castle-engine/castle-engine/pull/248) will be merged :)

**Comment by PNSee** [comment]
@and3md @peardox 
That may be the case. I know that sprites are evenly separated in 64x64 squares, but the sprite sheet itself does not comply to power of 2 rule, a.f.a.i.k. Once I get to my laptop, I should change sheet size and layout and check your suggestions.

**Comment by michaliskambi** [comment]
Fixed in https://github.com/castle-engine/castle-engine/commit/07c699646025221737412b8150f277fca0499455 . Both Castle Game Engine and view3dscene snapshots will be rebuild with this change soon automatically.

1. Setting `GUITexture` to `true` by default for sprite sheets (both Starling and Cocos2d) is indeed better, I agree with both @and3md and @PNSee about it.

   I did it for images in https://github.com/castle-engine/castle-engine/commit/bbf92589093d7f5fddf16f2eb32db75c3e9d5e72 , and the same reasoning applies for sprite sheets. *Not* resizing to power-of-2 is more natural in this case.

2. This is not related at all to the filtering (nearest etc.) settings, as far as I see.

3. This is also not related at all to the blending (bs2D mentioned). @peardox  The meaning of bs2D is explained in https://github.com/castle-engine/castle-engine/wiki/Blending (and API docs). The `RenderOptions.BlendingSort` doesn't matter at all for scenes loaded from sprite sheets -- it only matters for scenes where multiple polygons with transparency may be visible on top of each other. A "sprite sheet" is always only 1 visible polygon, so the issue doesn't exist.

4. The name `GuiTexture` is unfortunate, it should probably be more descriptive `ForcePowerOf2` with inverted meaning (by default `true`). I may change it some day.

5. The main reason why engine resizes textures to power of 2 by default is that *mipmaps* are only possible when the texture has power of 2. And mipmaps are critical to make textures in 3D games look good, from various distances. So when you're doing a typical 3D environment, you really should use power-of-2 textures (or let engine resize them to power of 2 -- which increases loading time, but at least they will look good).
   
    For typical 2D games and 2D assets like images / sprite sheets -> this argument doesn't apply of course.

    So it's difficult to have the best default :) For textures for 3D environment -> definitely the better default is "force power of 2, resize to power of 2 if not already". For 2D games or GUI -> the better default is usually "do not force power of 2".

    Historically, power-of-2 textures were also processed faster by GPU. Ancient OpenGL versions may not even support non-power-of-2 textures (in which case CGE will resize them anyway). But this is mostly history now, if you don't care about ancient GPUs then you can forget about this detail :) All reasonable GPUs nowadays will support non-power-of-2 textures without any fuss.

6. Note that in general you can also overcome such things by changing the X3D graph before loading. That is, without my fix, your other solution would be loading model like this (instead of `Scene.Load('....starling-xml'`):

```pascal
type
  { The node processing callback (given to Node.EnumerateNodes) must be a method
    (that is, inside a class).
    In case of this simple application, we don't have a natural class where to put it,
    so we use this TNodeHandler.
    In a "real" application, you usually have a natural class, like TStateXxx class. }
  TNodeHandler = class
    class procedure HandleImageTextureNode(Node: TX3DNode);
  end;

class procedure TNodeHandler.HandleImageTextureNode(Node: TX3DNode);
var
  ImageTexture: TImageTextureNode;
  TextureProperties: TTexturePropertiesNode;
begin
  ImageTexture := Node as TImageTextureNode;
  TextureProperties := TTexturePropertiesNode.Create;
  TextureProperties.GuiTexture := true;
  TextureProperties.MinificationFilter := minDefault;
  TextureProperties.MagnificationFilter := magDefault;
  ImageTexture.TextureProperties := TextureProperties;
end;

procedure MyLoading;
var
  Node: TX3DRootNode;
begin
  Node := LoadNode('....starling-xml');
  Node.EnumerateNodes(TImageTextureNode, @TNodeHandler(nil).HandleImageTextureNode, false);
  Scene.Load(Node, true { owns Node });
end;
```

( I hacked this sample code by modifying `examples/3d_rendering_processing/anisotropic_filtering/anisotropic_filtering.lpr` example. )

So it doesn't mater anymore (since GuiTexture for sprite sheets is now default), I'm just showing it for completeness.

**Comment by PNSee** [comment]
@michaliskambi Many thanks for resolving the issue and bringing up the explanation.  I've already played around atlas sizes in older version of CGE.
![image](https://user-images.githubusercontent.com/46522630/108609034-41456b80-73dc-11eb-97a2-d41b534717b4.png)
Indeed, a sprite taken from the atlas which size is power-of-2 compliant looks exactly as needed, while the same sprite from the atlas of non-standard size tend to be forcibly smoothed (if that could be applied to resizing algorithm).

Once again, thanks for taking your time!
