### ISSUE TITLE
2D / Starling-XML ValidateGeometryState SIGSEGV under Lazarus (noticed with Win10)

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#259]
Note that this doesn't appear to happen with a CastleWindowBase build

Sample project : https://github.com/peardox/IsometricTest - needs graphic assets adding (instructions in the README.md)

You can build the project with build-tool (which appears OK) but when built with the Lazarus IDE by opening IsometricLaz.lpr the project seemingly randomly does something nasty when the mouse is moved.

I've only tried this under Windows where it was causing me no-end of headaches when trying to get a screen grab for the repo.

Run the project then click on the Next Anim a few times then move the mouse around. It will (randomly) SIGSEVG and the IDE dumps you at...

procedure TShape.ValidateGeometryState(const OverTriangulate: boolean);

I am unsure if the problem is Starling or 2D. I've had issues with 2D before but that was down to too many messages being passed around (so I reduced the ocurrance of the messages)

**Comment by michaliskambi** [comment]
I cannot reproduce the problem now. 

- Tried with Lazarus 2.0.10 based on FPC 3.2.0 on both Windows and Linux.
- Clicked on "Next Anim", moved the mouse a lot :)
- Tried both the version compiled by `castle-engine compile` and `lazbuild IsometricLaz.lpi`

That being said, you really should heed the warning that floods the log:

```
Warning: ssStaticCollisions used on scene "" but the geometry changed. Freeing the spatial structure. You should use ssDynamicCollisions for this scene
```

Use ssDynamicCollisions. With ssStaticCollisions, it is possible that an error *exactly as you describe* happens: with ssStaticCollisions, we have a structure (octree) that keeps pointers to triangles, and assumes these pointers always remain valid, but if the scene actually changes then these pointers will become invalid. It may result in Access Violation when trying to resolve raycasts, like when moving the mouse (and we try to update `Viewport.MouseRayHit`).

I have an idea how to fix it, although I don't want to commit this without a reproduction. But one could call `PointingDeviceClear;` in `castlescenecore.pas` exactly after the warning 

```
WritelnWarning('ssStaticCollisions used on scene "' + Name + '" but the geometry changed. Freeing the spatial structure. You should use ssDynamicCollisions for this scene');
```

is done in `TCastleSceneCore.DoGeometryChanged`. This would possibly make this more robust, i.e. `ssStaticCollisions` should not crash (but you should still use `ssDynamicCollisions` for performance).

Can you test it, as I cannot reproduce?

1. See if adding `PointingDeviceClear` to `TCastleSceneCore.DoGeometryChanged`, as described above, avoids your crash.

2. Independently, see if changing `ssStaticCollisions` to `ssDynamicCollisions` helps. By this, I mean you should change 

    ```
    Scene.Spatial := [ssStaticCollisions, ssDynamicCollisions, ssRendering];
    ````

    into

    ```
    Scene.Spatial := [ssDynamicCollisions, ssRendering];
    ````

Using both ssStaticCollisions and ssDynamicCollisions makes no sense, only one of the octrees will be used. In this case, we will use the one based on `ssStaticCollisions` (just because that's the order chosen by `TCastleSceneCore.InternalOctreeCollisions`).

See the `TSceneSpatialStructure` API docs where I document the meaning of `ssXxx` enums.

It is possible I'll simplify this in the future, and I'll deprecate `Spatial` in favor of Boolean `PreciseCollisions` (that will toggle `Spatial` between `[]` and `[ssDynamicCollisions, ssRendering]`). In 90% cases these are the only `Spatial` values you need.

**Comment by peardox** [comment]
Yep, seems to work with ssStaticCollisions back in and PointingDeviceClear added to DoGeometryChanged

It's firing the routine very often - I stuck a logfile write in DoGeometryChanged to check it was getting there. A 30 second run has 1828 lines saying 'PointingDeviceClear;' :(

**Comment by michaliskambi** [comment]
Thanks for testing! I added `PointingDeviceClear` call to this (and some other similar places). So the code is now more robust, it will not crash if someone will do this in the future.

The recommendation remains to not use `ssStaticCollisions`, instead use `ssDynamicCollisions`. The use-case for `ssStaticCollisions` is very small. The warning `ssStaticCollisions used on scene ...` (and your log too, I guess) was happening every frame, matching 1828 / 30 ~= 60.93 = your FPS :) While the warning was spamming, underneath something even worse happened: we destroyed and recreated an "octree for collisions, that assumes scene is completely static" every frame. This recreation is in general somewhat costly, that is why the warning (and I :) ) advise to not use `ssStaticCollisions` in this case.

( In this case I see you still had 60 FPS -- likely because a scene from sprite sheets is very simple, and you had only 1 such scene, so this "recreation of octree" was not really a problem. But it would become a problem if you had more such sprite sheets, and/or did this with more complicated scenes than a sprite sheet. )
