### ISSUE TITLE
Android stream error with Starling-xml

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#260]
Same test project - https://github.com/peardox/IsometricTest

Note - it also loads a 4k jpeg background image before hitting the starling stuff

My screenshot...

![Screenshot_20210302-103444](https://user-images.githubusercontent.com/1549219/109658394-75e4c000-7b5e-11eb-89a4-b862814a86f7.png)

Your notes...

> You showed an exception from FPC TStream, I guess FpImage expects a TStream that can do Seek, but a stream from Android assets doesn't support it. This is unrelated to ssStaticCollisions troubles. Please make a separate ticket for Android problem -- I guess it just requires a PNG file, and a simplest application on Android reading it will show the stream error. And the solution will probably be just load with soForceMemoryStream.
> 
> My only wonder is why didn't we catch it earlier, I mean I did test loading PNG on Android from game data many times :slight_smile: So I would like a testcase.

**Comment by michaliskambi** [comment]
Fixed.

My initial guess was half-right, but the problem actually occurred at `BackScene.Load('castle-data:/tiles-iso.jpg')`, so with JPG.

Note that the project will still fail on Android because of invalid PNGs (you will get `Error loading image from URL "castle-data:/PVGames_ApexPredators/Apex_Hunter/Sprite_1.png": CRC check failed`). This is a completely independent problem, so I'll write about it separately on Discord.

**Comment by peardox** [comment]
I've re-saved all the PNGs so at least the Droid will build properly now.

I've mentioned the problem in the PV Games discord in detail and plugged CGE in several posts there (wonder if anyone will come and look us up?). They have a huge library of 2.5D art so I'm wondering how far the issue goes... Will build some more Texture Atlases + find investigate a bit.
