### ISSUE TITLE
Cannot read glTF extra "targetNames", unexpected type TPasJSONItemArray

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#269]
As per Discord here's a model that gives an error in view3dscene

```
3 warnings:

Cannot read glTF extra "targetNames", unexpected type TPasJSONItemArray
Cannot read glTF extra "targetNames", unexpected type TPasJSONItemArray
Cannot read glTF extra "targetNames", unexpected type TPasJSONItemArray

Scene URL: "C:\work\sprite\remy.gltf".
Use "File->View Warnings" menu to view these warnings again.

```
Model's a bit large (35 Mb)

https://peardox.com/script/remy.gltf

The plan here is to take a Mixamo model, pass it thru GodotGameTools to export the GLTF - which resulted in the file above

Next step is to convert it to a spritesheet

**Comment by michaliskambi** [comment]
I fixed this a week ago in https://github.com/castle-engine/castle-engine/commit/bd921182abd86a4bd3b52f20727731e6e5f64f8f . I experienced the warning also on other Blender models (exporting any Blender mesh with shape keys -> glTF will provoke this.)

Note that the warning was just indicating that we fail to parse some "metadata" (which is not interpreted in CGE in any way) from the glTF file. Now we parse it OK, preserving it using `Node.MetadataStringArray` and friends. If you don't read metadata from X3D nodes in your own application, then you will not notice any gain from this fix, aside from the cleaner logs because the warning is gone now :)
