### ISSUE TITLE
Add tools/update-castle-engine-version to update castleversion.inc (Original: Include Engine version in Logs?)

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#28]
I've thought it might be a good idea to include Castle Game Engine version in log similar to {$I %FPCVERSION%}.
However, it doesn't seem to be "as easy" in Git version (where this information would be most useful).
{$I %DATE%} + {$I %TIME%} Will provide date and time of the last compillation, but not of the date of "latest commit to master branch"
Anyway, it's not that important to make any complex solution. E.g. static constant like "5.2.0", "6.0.0" or "Git version no earlier than 1.11.2016" (e.g. the latest date you've remembered to change it :)) automatically inserted at log start will be enough.
Maybe, adding FPC information to log initialization, such as {$I %FPCTARGETCPU%}; {$I %FPCTARGETOS%}; {$I %FPCVERSION%}; might also be useful?

**Comment by michaliskambi** [comment]
Both useful suggestions.

- Yes to adding engine version. We can create a file src/version.inc, that can then be included in both fpmake.pp and in castlelog.pas, that defines a constant like CastleEngineVersion = 'xxx';

  As to it's contents: it would be best if it would contain a release number like "6.0.0" for the stable engine version, or the last version number  + commit hash + datetime of the last commit for the unstable version. I think I could do it, using small shell script, that depends that git "tags" are set at the release commits.

  You can get the current hash + datetime using a command like

  ~~~~
  $ git log --format="%h (date: %ci)" -n 1
  d1b7a52 (date: 2016-11-05 07:02:44 +0100)
  ~~~~

  (based on http://stackoverflow.com/questions/19176359/how-to-get-the-last-commit-id-of-a-remote-repo-using-curl-like-command )

  And you can use "git describe" to get the latest tag. (http://stackoverflow.com/questions/4277773/how-to-get-latest-tag-name , http://blog.getlooseleaf.com/post/122742606927/using-git-to-specify-the-version-of-your-app )

  So, writing a script that outputs src/version.inc is easy:)

- The question is, when to run it. We cannot run this during normal engine compilation (using whatever method: Lazarus, castle-engine build tool, manual fpc call...). Well, castle-engine build tool could do it, and Lazarus too, but not everyone will have git installed, or have engine from the git repo...

  So, my solution would be simple: src/version.inc that is committed to repo is like "6.0.0" (right at release) or like "6.0.0 - unstable" for commits following the 6.0.0 release. And everyone can optionally (e.g. right after getting engine from GIT) run the script (it would probably be in tools/update-castle-engine-version). This way you or I can get "6.0.0 - unstable (last git commit: d1b7a52 on 2016-11-05 07:02:44 +0100)" so we can have a version number with all the gory details.

  I don't think we would want to have the src/version.inc contain the GIT hash "when we last remembered to run it". This would be inconsistent, so possibly more harm than good. I would rather prefer to make engine releases *more* often than once a year, to make the version number more meaningful:) The new engine 6.0.0 has a ton of new features, but it's not good that we had more than a year of intenstive engine development without a new release --- my fault, due to lack of time, but I hope to improve this:)

- Yes to writing FPC, and also target OS/cpu information. This is simple thanks to the magic FPC directives you listed.

**Comment by michaliskambi** [comment]
For now, I did the simple things:

- CastleEngineVersion constant in CastleUtils unit.
- Internally, src/base/castleversion.inc file, used to define CastleEngineVersion in src/base/castleutils_miscella.inc, and also by fpmake.pp, and it could be overwritten by the future tools/update-castle-engine-version script.
- The log shows now CastleEngineVersion, along with FPC information (from SFPCVersion, an ancient function in CastleUtils, upgraded now). The beginning of the log looks like this now:

  ~~~~
  Log for "escape_universe". Started on 2016-11-09 at 04:02:10.
  Castle Game Engine version: 5.2.0 (unstable).
  Compiled with: FPC 3.0.0 (Linux / x86_64).
  ~~~~

So everything is done, except a script tools/update-castle-engine-version to update the src/base/castleversion.inc. For now, it just has to be updated manually, before and after every release.

**Comment by eugeneloza** [comment]
Thanks a lot!
That should put much more order into Logs :)
> Castle Game Engine version: 5.2.0 (unstable).
I think it should be 6.0.0 (unstable), because 5.2.0 is stable...

**Comment by michaliskambi** [comment]
> I think it should be 6.0.0 (unstable), because 5.2.0 is stable... At least I saw people do it that way...

It's an "unstable version derived from 5.2.0", not a "beta version of 6.0.0". Hence "5.2.0 (unstable)". Hm, but I can see that it's just my way of thinking, and it may be totally unclear for others.

I think that the best solution would be to just increment a version number. Like Linux or FPC --- in version X.Y.Z, the middle (Y) version number is *even for official releases*, and gets incremented immediately after the release, and once again incremented right before the release, so the *unstable version has always odd number at Y*. The release number (Z) too, so the released version has always both Y and Z even, while the version in SVN has (almost) always Y and Z odd.

Lazarus does it even simpler: it's version number is just two numbers X.Y. "Y even" => official release, "Y odd" => unstable version (changing after every commit). This is simpler if you don't plan to maintain many "fix releases" from a stable branch. It is also suitable for us, at least right now (we can always add ".Z" later).

So: 
- Let's go with Lazarus versioning scheme, as it's simple, may be familiar in FPC/Lazarus community, and it's also a subset of the FPC and Linux versioning scheme.
- The current version in Git should henceforth be referred to as "5.3 (unstable)". We add the word "(unstable)" just for clarity to newcomers, internally we know that the ".3" is already meaning "unstable".

**Comment by eugeneloza** [comment]
Absolutely agree :)

**Comment by eugeneloza** [comment]
I think the issue is perfectly solved :) Closing.
