### ISSUE TITLE
[info][unfixable?] Fundamental problem with VRML float type usage in Extrusion.

### ISSUE THREAD

**Issue by splace** [castle-engine/castle-engine#294]
## possible source of some historical/continuing Extrusion problems coming from a spec problem

_attempting clarity here by using step-by-step breakdown, numbered for easy reference_

1. floats are lossy.
2. this, intensionally, makes next to no difference, except when comparing them with each other.
3. points using float conordinates co-location/co-linearity require comparison of floats.
4. comparing floats is deterministic only when using the same sequence of operations and using the same 'standard' for the floats.
5. vrml doesn't specify all the operations, obviously, or the float standard.
6. but within a single code-base the other requirements would generally be met, and float comparison would be deterministic.
7. things tested in a viewer would always appear as they initially did.
8. although if the coded operations were even just reordered they wouldn't necessarily.
9. and different code-bases would not, in general, be able to agree with each other.
10. being deterministic isn't being defined
11. the results of vec3f co-location/co-linearity testing aren't defined.
12. Extrusion can have massive geometry changes depending on these.
13. so an Extrusions shape is undefined.
14. the specs job is to define consistency across code-bases.
15. the spec is broken.

this has been my conclusion for many years now and I've tried to communicate it in the appropriate places several times without response. but recently i have realised there might be a way to do this that is within the spec., is consistent and unsurprising and also as, it was surely, intended.

of course if the spec isn't excluding undefined behaviour then it is still broken, this is just a way of living with a broken spec. and since i can't really see this being implemented by any viewer, let along all of them, this is more just for info. maybe going some way to stopping it happening again? or preventing people wasting time doing anything with Extrusions.

## fixing within current spec.

since vrml 'float' isn't specified as a standardised type, you can make your own, one where you can fix float comparison.

this possibility is explicitly made clear here: X3D v3 def of SFloat

> Implementation of these fields is targeted at the single precision floating point capabilities of processors. However, it is allowable to implement this field using fixed point numbering provided at least six decimal digits  of precision are maintained and that exponents have range of at least [-12, 12] for both positive and negative numbers.

## possible implementations

- just use big types or long rational types throughout. probably killing performance unacceptably. 
- determine co-location/co-linearity status of just the spline points using one of above types and deal with all the complexity of the animation of these using values that might, or might not be, either type.
- determine co-location/co-linearity status of spline points using one of above types once and ignore if any animation changes it. (points still move just no flipping)

it seems to me this last one is useful, the second is more complete. but it seems to me that just retaining the original flips, caused by the original co-location/co-linearity would be significantly less surprising than the complete one.

but again this is really just academic.

**Comment by splace** [comment]
@michaliskambi quickly perusing the source it appears the use of 'iszero' is when the floats are compared

**Comment by michaliskambi** [comment]
Indeed, the float problems you list here are all correct. 

- Comparing floats needs to have some epsilon (`IsZero`, `SameValue` in CGE and Pascal account for that), 

- changing order of operations may change the outcome when dealing with floating-point numbers (even if, mathematically, operating on numbers with perfect precision, the outcome should be the same).
 
There are books about this subject, and pages like https://en.wikipedia.org/wiki/Floating-point_arithmetic :)

But it is not something I want to address with introducing a new format for numbers within CGE. Reasons:

- It would be a big burden to implement and maintain, even in 3rd case of "possible implementations" you mention (implement something like long rational type and only use locally, for necessary operations).

- And it would only address some edge-cases of `Extrusion`, which is not really our priority. As I mentioned in https://github.com/castle-engine/view3dscene/issues/35 , the reality is that most models come from glTF etc. as a set of polygons -- the geometry nodes like `Extrusion` are not found in actual 3D models exported from Blender/3dsMax/Maya etc.

    (Unless we would implement 1st point of "possible implementations" you mention. Then it's a general solution. And indeed it would be unacceptable loss of speed.)

If you have a particular testcase of `Extrusion` that fails, right now, in CGE/view3dscene then submit it. Possibly we can 

- Improve the algorithm to be more numerically stable. 

- Use the `Double` type (64-bit, much more precise floating point number) for some subset of calculations. This is much easier than inventing a new approach to numbers, we actually already do this in I think 2x places in CGE. That is, even when API uses `Single` type (equivalent to `float` in C) we do some internal calculations using `Double`.

I know it feels like "fighting windmills" -- we would try to improve the numerical stability of an algorithm, but still doing it on floats, which are inherently imprecise. But this is a practical solution, and from what I know this is also what everyone else is doing. 

Note that 99% of real-time graphic applications use floating-point numbers. GPUs use floating-point numbers actually, some with even less precision (16-bit half-float). Because they are fast, much faster than using custom "long rational types" not supported natively by CPU or GPU, and more universal than using fixed-point numbers (e.g. keeping stuff as `int`, and assuming it is a value * 1000).

**Comment by splace** [comment]
@michaliskambi 

(BTW really still not looking for this to be implemented.)

i'm not sure you understand the idea exactly; i'm only suggesting a small piece of lossless code working in parallel to the geometry setup float maths, specifically, and only, to accurately do the comparisons, (removing need for float comparisons) its just for the co-linearity/co-location, not for anything in the transform hierarchy.


>  If you have a particular testcase of Extrusion that fails, right now

i think, failures can be crafted for any precision/epsilon/algorithm as long as floats are used. that is why this is particularly pernicious type of bug, if you make the tests first you tend to adjust above to pass that test, but that doesn't actually mean what it appears too, you are just moving the problem around.
