### ISSUE TITLE
Badly behaving rectange drawing

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#311]
[badfuncts.zip](https://github.com/castle-engine/castle-engine/files/6717629/badfuncts.zip)

The code in the archive does the following - once with a Rectange and once with a FillRectangle outputting two pngs

```
  img := TRGBAlphaImage.Create(670, 670);
  img.FillRectangle(0, 0, 334, 334, Vector4( 1.0, 0.0, 0.0, 1.0));
  img.FillRectangle(335, 0, 669, 334, Vector4( 0.0, 0.0, 1.0, 1.0));
  img.FillRectangle(0, 335, 334, 669, Vector4( 0.0, 1.0, 0.0, 1.0));
  img.FillRectangle(335, 335, 669, 669, Vector4( 1.0, 1.0, 0.0, 1.0));
  SaveImage(img, 'filled.png');
  img.free;

```

Look very carefully - zoom in on the image in Gimp or whatever

In the case of FillRectange the second and fourth filled rectanged overflow back to column zero
In the case of the Rectanges - well, also funny - it's drawing 2px wide despite me asking for 1px and the middle lines are 3px?

When I use this stuff in my application with a Window things get really bad causing unexplained errors and doing some really wierd crap I haven't traced yet - I wanted to try out the root probem (as it may be causing the big problems in app)

**Comment by eugeneloza** [comment]
Attaching the images for convenience.

![filled](https://user-images.githubusercontent.com/10726162/123470322-eb3c3b00-d5fc-11eb-9b4c-eb5e003e239e.png)

![outline](https://user-images.githubusercontent.com/10726162/123470325-ebd4d180-d5fc-11eb-94d6-665c264bb8fc.png)

It's my fault. I've encountered a few problems with it myself in the past - but as no one complained, I had those in my backlog :) I'll look into it on the Weekends (we have a heat surge right now, but still I hope I'll be able to do something useful).

**Comment by peardox** [comment]
I gave the test code a bigger canvas to work with and it writes to co-ordinates outside the requested area

It appears to be writing as far as 671 when it should never go past 669 - harder to check in the Y axis cos of bottom left origin (guess I could to a vertical flip)

**Comment by peardox** [comment]
I had a quick play plotting a rectangle from 10, 10 to 10, 10 (1px) - result - a border of 1px all around my chosen pixel

![border](https://user-images.githubusercontent.com/1549219/123491615-0dd74f80-d60f-11eb-8599-48f9958c321d.png)

This explains why my app is freaking out when drawing filled rectangles to construct a pixel grid - it's writing to memory not in range of the image buffer

**Comment by peardox** [comment]
I needed a fillRectangle so wrote one

Its specific to what I require but here's a starter if its of any use (it works and is faster than the library code and seems ok so far)

[rgbalphaimagehelp.zip](https://github.com/castle-engine/castle-engine/files/6719964/rgbalphaimagehelp.zip)

Stupid git - dont accept .pas files ...

**Comment by michaliskambi** [comment]
I fixed now quickly the `FillRectangle` overflowing. 

I say "quickly", because I disregarded a small loss of performance in my fix. But I'm unsure if it's even measurable. I tested a different fix, to keep `Inc(p)` for performance, but it would possibly shift drawn rectangle 1px to the right. I'm not 100% clear if the current `FillRectangle` treatment of X coordinate is correct, but I know I don't want to break it.

Reasons:

- In the long run (think: 1-2 years), we want to recommend drawing using GPU-accelerated `TDrawableImage` and `TDrawableImage.RenderToImageBegin/End`, like `examples/images_videos/draw_images_on_gpu/draw_images_on_gpu.dpr` shows. 
 
    The CastleImages API should become more limited, to focus on loading and trivial data transferring, but no "intelligent" operating on colors (nothing that requires arithmetic or different code for RGBA/RGB/GA/G modes), no blending, no rasterization of primitives. I have a longer news post about the reasons behind it half-written. In short, OpenGL is more efficient at this, and it's easier for us to support (much less code to add/maintain), and it's already more flexible in some cases.

- I'm in the process of marking some methods as deprecated and making an example to better show "the better way".

- So while we're in this transitional period I know that I don't want to change how existing API functions. No point in big changes -- the new approach in `TDrawableImage.RenderToImageBegin/End` is a big change for users already.

   And I know this transition will take a long time -- I know many people, including both of you above in this issue, use CastleImages drawing API. We will not remove it overnight, there will be long time when we clearly signal what is deprecated but keep it working.
