### ISSUE TITLE
ApplicationTimer bug

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#32]
I've ran into a strange Application.OnTimer bug on Windows7x64 + Lazarus 32 bit 1.6.0, FPC 3.0.0. It skips some timer events (approx. 1 of 30) if there is a font output Window.OnRender - this bug is not caught in OpenGL graphics output.
This happens only when run inside Lazarus. The compiled program doesn't make any skips. In Linux everything works fine also both standalone and inside Lazarus.
Maybe something in my system conflicts with Application timer? The suspect is GDB vs ZoneAlarm firewall, there is a known issue between GDB and Comodo firewall, maybe it has some softer manifestation here.
The most simple program I could reproduce the bug is:
[AppTimerBug.tar.gz](https://github.com/castle-engine/castle-engine/files/574862/AppTimerBug.tar.gz)
Could anybody test it on another windows system? It should report something like "312ms" in dos-window, but 550 and higher shouldn't happen (I've experienced up to 1678ms versus demanded 300ms).

I've thought of implementing something similar to TTimer in LCL, looks relatively simple, we can even just include CustomTimer.pas from LCL without dragging the whole library. What do you think?

**Comment by michaliskambi** [comment]
> I've thought of implementing something similar to TTimer in LCL, looks relatively simple, we can even just include CustomTimer.pas from LCL without dragging the whole library. What do you think?

I also recently thought about implementing simple TCastleTimer. It can be done really trivially, as a descendant of TUIControl (on which I'm also writing a large tutorial page now:). We don't need to use anything from LCL for this, our TCastleTimer can expose simple properties and events like Interval, OnTimer (to be consistent with LCL TTimer names), and implementing them is really trivial inside the overridden TCastleTimer.Update implementation. Like this:

~~~~pascal
TCastleTimer.Update(const SecondsPassed: Single; var HandleInput: boolean);
begin
  inherited;
  if Interval <> 0 then
  begin
    CurrentRemainingInterval -= SecondsPassed;
    while CurrentRemainingInterval < 0 do
    begin
      CurrentRemainingInterval += Interval;
      if Assigned(OnTimer) then
        OnTimer(Self);
    end;
  end else
  begin
    { for Interval = 0, just call timer at every Update? }
    if Assigned(OnTimer) then
      OnTimer(Self);
  end;
end;
~~~~

(and initialize CurrentRemainingInterval to Interval, inside SetInterval, when interval changes.)

This is just a pseudocode, I did not test it yet.

I would place implementation inside the CastleControls unit. TCastleTimer would be ideally so simple that it doesn't deserve it's own unit:)

When we'll have TCastleTimer implemented, I would gladly deprecate TCastleApplication.OnTimer, as TCastleApplication.OnTimer is not a nice API (there is only a single global Application.TimerMilisec value, which makes it's usage limited to only simple cases).

**Comment by michaliskambi** [comment]
Addendum to my TCastleTimer notes:

- Our TUIControl.Exists already performs the use of LCL TTimer.Enabled (and "Exists" is consistent with the rest of engine stuff, it's  TUIControl and T3D)
- Our "Interval" should be in TFloatTime, not miliseconds (this is consistent with rest of the engine, I gradually eliminate miliseconds times as float times turned out easier to use --- the possible accuracy problems are eliminated by TFloatTime = Double instead of Single. This is also consistent with X3D.) Possibly I'll call it "IntervalSeconds", to avoid issues with people thinking it's in miliseconds like in LCL.

I'll implement this today evening probably:)

**Comment by michaliskambi** [comment]
1. I tested your application on Windows (Windows 7, 32-bit, Lazarus 1.7.0 from latest SVN, FPC 3.0.0).

  The timer works the same in both Lazarus debugger, and when run from exe. It's usually 312ms, although I can make it a little less stable (up to 468ms) by resizing the window like crazy.

  So I don't reproduce your observation of the 1678ms delay.

  That said,

  - I can still produce arbitrarily large timer delays if I pause the application by pressing Ctrl + Space (system menu) on Windows. That's a Windows-specific behavior, events do not reach us (we hang inside some WinAPI call) then.

  - The timer is not guaranteed to be absolutely reliable... delay 468ms instead of 300ms requested simply means that we had no chance to run it for 168ms between.

    *Large* timer delays are still a problem, as they mean that we also have large intervals between OnUpdate calls of everything, and so generally the application has probably low FPS or is hanging. So delay 1678ms is not good, it indicates we "hanged" for ~1300ms. But I have no clue for now how to improve or even debug this very specific case (only on debugger in Windows).

  You can shake things a bit by changing src/window/castlewindow_winsystem.inc: change

  ~~~~
  if not CheckMessage then
  begin
    { No messages to us, so call update/timer/render on everything. }
    UpdateAndRenderEverything(WasAnyRendering);
    ....
  ~~~~

  to

  ~~~~
  CheckMessage;

  begin
    { No messages to us, so call update/timer/render on everything. }
    UpdateAndRenderEverything(WasAnyRendering);
    ....
  ~~~~

  IOW, make UpdateAndRenderEverything execute regardless of the CheckMessage result.

  You can also set Application.LimitFPS to 0. By default it's 100, so we really have only 100 occasions to call the timer event at all. So it's responsible for delays within 1/100 of the second.

  Does it change your observations in Lazarus debugger?

2. Two small notes about your test program (totally unrelated to the timer question):

  - If you use TCastleWindowCustom, remember that you don't have any controls by default. So your screen is not cleared to anything reliable, it contains a memory "garbage", visible in some cases (depends on OS, GPU driver etc.).

    To counteract this, you should call CastleGLUtils.GLClear at the beginning of OnRender (not the adviced way -- it will cover any possible Controls you add in the future), or add TCastleSimpleBackground, or add any other non-transparent full-screen UI control to prevent that. Like "Window.Controls.InsertBack(TCastleSimpleBackground.Create(Window));".

    Or of course you can descend from TCastleWindow. It contains a SceneManager, that by default does nothing more than clearing your screen to black.

  - Be sure to add also castle_window.lpk (not only castle_base.lpk) to the program requirements, if you use CastleWindow unit. Sometimes it seems not necessary (as the castlewindow.ppu and friends are already found in the same output dir as castle_base output dir: castle-engine/packages/lib/...). But they are necessary (in case castlewindow.ppu was not compiled yet).

3. I implemented TCastleTimer:)

  Of interest:
  - a fun demo in examples/2d_standard_ui/timer_test/timer_test.lpr
  - an interesting property TCastleTimer.CounteractDelays, see it's docs and implementation if you're curious:)

  Note that, while it's a cool thing, it probably doesn't solve this particular problem. We can only fire events as often as we don't hang:) So if you can get large delays in Application.OnTimer, you will also be able to get large delays with TCastleTimer.

**Comment by eugeneloza** [comment]
> It's usually 312ms, although I can make it a little less stable (up to 468ms) by resizing the window like crazy.

I've had this problem without doing absolutely anything. Just sit down and wait until it pops up double values. P.S. The lesser the values of TimerMilisec the higher the delay is. E.g. I saw 1600ms delay for 30 ms timer, but never for 300 ms timer - at max I've encountered ~600.
Thanks a lot for the test, then I'll look for the problem on my side (I suspect GDB <-> ZoneAlarm).

> So your screen is not cleared to anything reliable

Yes, I was trying to make everything as minimalistic to reproduce the bug. I could have tons of graphics running, but no delays fired. As soon as I do UIFont.print(...) plus a "relatively heavy" load per frame - at least 30 outputs or a lot of calculations for each output, such as inttostr, or additional graphics drawing (the graphics itself doesn't trigger lags) I start getting lags which disappear when I comment out UIFont.print(...) lines.
I've come across this bug while compiling the snake game for Windows :)

I'll also test TCastleTimer asap.

Then, I think, this issue is "solved" as it is not the problem on engine-side. Closing.

**Comment by michaliskambi** [comment]
> P.S. The lesser the values of TimerMilisec the higher the delay is. E.g. I saw 1600ms delay for 30 ms timer, but never for 300 ms timer - at max I've encountered ~600.

This is extremely weird. Even if some application is interfering with your process (or just the whole OS), causing the system to be occasionally overloaded for a short time (which may be blamed on anti-virus or such software, indeed).. it should *not* be affected by the TimerMilisec.

Reason: The timer is not implemented using native OS "timer" mechanism, instead we simply watch out for the timer delay ourselves. This is a feasible approach for game engines, where almost always you have some visible animation running, so there's not much point in using OS "native timers" to conserve CPU usage. (To avoid exhausting your CPU or laptop battery, we have an unrelated "Application.LimitFPS mechanism".)

(In the past, I tried using native timers from WinAPI, or GTK... but it always turned out to be more trouble, for no gain.)

The side effect is that an outside application has no way of "knowing" or *being affected in any way* by the timer executing more of less often.

Hmmm, **idea!!**, unless the "Writeln()" you do in timer is actually causing some reaction... Maybe the Windows console is doing something unoptimal when it is buffering the text, or shifting the text upward? This would explain why smaller TimerMilisec -> causes more "Writelns" -> which causes more load on Windows console -> which changes the results.

What if you change your demo, to output the DoTimer results without doing any Writeln (or any WritelnLog, or anything that touches the OS). E.g. you could display last 10 results or such inside the OnRender callback.

> Yes, I was trying to make everything as minimalistic to reproduce the bug. I could have tons of graphics running, but no delays fired. As soon as I do UIFont.print(...) plus a "relatively heavy" load per frame

This is also weird. UIFont.Print does fairly straightforward drawing. I don't *think* it uses the CPU or GPU in any non-standard way. Especially since underneath it uses TGLImage for drawing.

**Comment by eugeneloza** [comment]
>  unless the "Writeln()" you do in timer is actually causing some reaction...

Nope. I've caught this bug in snake game, where the snake should advance a step each 300ms, but sometimes it was freezing in-place for visible amounts of time (almost doubling). I've started to seek for the reason and eventually ontimer revealed unexpected pauses.
I haven't seen it any before (e.g. FireMadness would also have suffered from such stuff, but it doesn't, thou it has enormous amount of graphics processing (mostly TGLImages with scaling) and game logic calculations each frame - requiring introducing special handling for frameskips - but it showed absolutely no visible delays).
But, maybe after upgrading Lazarus (1.6.0 RC2 -> 1.6.0 stable) or some ZoneAlarm update... I'll have to check up how it works with FireMadness...
