### ISSUE TITLE
Implement TTexturePropertiesNode.BoundaryModeXxx and MIRRORED_REPEAT mode

### ISSUE THREAD

**Issue by Free-Pascal-meets-SDL-Website** [castle-engine/castle-engine#324]
Hi there,

well, title says it all. I wonder if the wrap mode MIRRORED_REPEAT (see https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD/Part01/components/texturing.html#t-TextureBoundaryModes) is implemented?

On
`TextureNode.TextureProperties.BoundaryModeS := 'MIRRORED_REPEAT';`
and
`TextureNode.TextureProperties.BoundaryModeT := 'MIRRORED_REPEAT';`

 and translating the texture out of the base S,T-space, the texture just repeats but isn't mirrored.

And there doesn't seem to be any kind of error checking of sensible inputs, as "fantasy modes" are also accepted and returned.

So, that is why I'm asking. :)

Best regards
Matthias

**Comment by michaliskambi** [comment]
The `TTexturePropertiesNode.BoundaryModeXxx` is right now completely ignored (which is also why we don't even make a warning in case of invalid values, in Pascal or in X3D file).

If you need it, let me know -- I'll leave this issue open :) It is rather easy to add support for it. (Note that it will override the `repeatS/T/R` settings at texture nodes.) The property will become a Pascal enumerated value then, not a String.

And we can implement "mirrored repeat". Note that some very old versions of desktop OpenGL may not support it, but it is supported on modern desktops and on all mobile devices we support (as it is present in OpenGLES 2):
- https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_texture_mirrored_repeat.txt
- http://docs.gl/gl4/glTexParameter
- https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glTexParameter.xml

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Thanks for your reply.

> If you need it, let me know -- I'll leave this issue open :) It is rather easy to add support for it. (Note that it will override the `repeatS/T/R` settings at texture nodes.) 

This mode would be highly useful to implement support for flipped tiles in the converter (https://github.com/Free-Pascal-meets-SDL-Website/CastleConvertTiledMap).

> The property will become a Pascal enumerated value then, not a String.

I appreciate this :).

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Was checking if I could get _mirrored repeat_ implemented. But even when modifying the file [castleinternalrenderer_texture.inc](https://github.com/castle-engine/castle-engine/blob/master/src/x3d/opengl/castleinternalrenderer_texture.inc) just a little bit (just overloading method HandleTextureProperties from line 33 with empty `TGLTextureNode.HandleTextureProperties(
  TextureProperties: TTexturePropertiesNode; out Filter: TTextureFilter; out
  Anisotropy: TGLfloat; out BoundaryModeS: TGLenum; out GUITexture: boolean)`), I get on clean + build:

> castleshapes.pas(35,1) Error: Internal error 200611031

As this is a method from a GLNode and no X3DNode, I thought it isn't necessary to use the node tools. What am I doing wrong or missing?

Best regards

**Comment by michaliskambi** [comment]
Are you sure you did a "clean recompile"?

FPC occasionally makes "Internal Error" in castleshapes or x3dnodes units when modifying some CGE code. Just clean and recompile, it should be gone. Our build tool does it automatically.

If problem persists, please show the exact code of your modifications. If you have a reproducible FPC internal error, it can likely be submitted to FPC and fixed there :)

**Comment by Free-Pascal-meets-SDL-Website** [comment]
You were right. My clean compile hasn't been clean enough...

Anyway, I struggle to understand something:
The file [tools\internal\x3d-nodes-to-pascal\nodes-specification\Texturing.txt](https://github.com/castle-engine/castle-engine/blob/master/tools/internal/x3d-nodes-to-pascal/nodes-specification/Texturing.txt) contains the description for the textureproperties node. The magnification and minification filters are present as SFString types.

The file [src\x3d\auto_generated_node_helper\x3dnodes_textureproperties.inc](https://github.com/castle-engine/castle-engine/blob/master/src/x3d/auto_generated_node_helpers/x3dnodes_textureproperties.inc) which has been generated from the file above does not contain these two properties anymore.

Obviously they where added manually in file [\src\x3d\x3dnodes_standard_texturing.inc](https://github.com/castle-engine/castle-engine/blob/master/src/x3d/x3dnodes_standard_texturing.inc) to have the Pascal enum types TAutoMagnificationFilter/TAutoMinificationFilter. 

My question is. where they removed manually from the auto-generated x3dnodes_textureproperties.inc, which contradicts the idea of never manually editing these files. Or is there a specific parameter to achieve this result in the x3d-nodes-to-pascal tool? Or am I missing anything else?

I'm a asking to find the right way of implementing the boundary mode fields. 

Best regards

**Comment by michaliskambi** [comment]
> My question is. where they removed manually from the auto-generated x3dnodes_textureproperties.inc, which contradicts the idea of never manually editing these files. Or is there a specific parameter to achieve this result in the x3d-nodes-to-pascal tool? Or am I missing anything else?

Ah, sorry -- you stumbled on a work-in-progress :)

Some nodes in these text files, the ones with `auto-generate-more: true` declaration, have all their fields with getters/setters auto-generated. See e.g. `MovieTexture` node in that text file, and how generated `x3d/auto_generated_node_helpers/x3dnodes_movietexture.inc` for it looks like.

Some other nodes (like `TextureProperties `, *for now*) have only some helpers autogenerated. 

So, 

- We didn't edit the autogenerated files afterwards. If you rerun the application `tools/internal/x3d-nodes-to-pascal/`, it will regenerate all the files, and you can confirm there will be no changes to what you already have in repo.
 
- However, the autogeneration of `TextureProperties` is just "dumber", it expects a lot of things to be manually added.

And this is of course just a temporary state :) 

In the near future (I hope in this month, January 2022) I want to 

- Have 100% nodes generated with `auto-generate-more: true` declaration . We're almost done, the only X3D sections missing now are

```
x3dnodes_1.inc
x3dnodes_97_nurbs.inc
x3dnodes_inventor.inc
x3dnodes_castle.inc
x3dnodes_standard_interpolation.inc
x3dnodes_standard_grouping.inc
x3dnodes_standard_shaders.inc
x3dnodes_standard_texturing.inc
x3dnodes_instantreality.inc
x3dnodes_standard_cubemaptexturing.inc
```

- Then, the `auto-generate-more: true` declaration will stop being used at all.  Every node will behave like `auto-generate-more: true` , no exceptions.

- Having 100% of X3D nodes auto-generated is a first step to make a big X3D nodes memory optimization, that I mentioned on https://castle-engine.io/wp/2021/11/02/optimizing-memory-usage-part-1-efficient-step-animation-using-component-system-in-x3d-nodes-no-interfaces-less-memory-used-by-sprite-sheets/ , it is also a "definitely" point on our 2022 plans https://castle-engine.io/wp/2022/01/01/summary-of-2021-plans-for-2022/ . Once they are auto-generated, I can make a big split (to have very small per-node-instance data, linking to larger "field information that can be shared by all nodes of given type").

For your task, I'd say to fix the `TextureProperties` definition in `Texturing.txt`, so that it will follow already the "best practices" (`auto-generate-more: true`) after your modifications. That is, 

- make `TextureProperties` have `auto-generate-more: true` in `Texturing.txt`

- remove most of `TTexturePropertiesNode` interface and implementation from `x3dnodes_standard_texturing.inc`

- moreover, change the things that are `SFString` in X3D but actually they have a limited set of values (so we want to express them as enums in Pascal) to use the `enumerated-type` syntax in text file to autogenerate Pascal enumeration from X3D SFString.

- once done, you should not only make sure it compiles, also make sure existing demos with `TextureProperties` work OK. What I recommend for such test is:
    - recompile https://github.com/castle-engine/view3dscene with my modified CGE version
    - grep https://github.com/castle-engine/demo-models for word `TextureProperties`. I see it found many TextureProperties tests, like `compositing_shaders\noise.x3dv`, `texturing_advanced\tex_anisotropic.x3dv`. If you're not sure what they should display, keep the original view3dscene (from the unmodified CGE :) ) on the side :)
    - Compare whether new view3dscene handles these testcases, just like the old one.

I know, it is not very well documented yet, you have to look at `tools/internal/x3d-nodes-to-pascal/code/` source code to understand what happens. This should be improved (and simplfied) once I'll finish my big rework... Quick intro for now:

Look `X3DColorNode` in `Rendering.txt` as a simple example. It just has one field, `mode`, defined like this:

```
  SFString   []   mode   "REPLACE"
    range: ["REPLACE","MODULATE"]
    enumerated-type: TColorMode ColorModeNames cmReplace
```

So X3D specification (well, actually CGE extension to X3D specification in this case: https://castle-engine.io/x3d_implementation_rendering_extensions.php#section_ext_color_mode ) says that this is SFString, and it only has 2 allowed values: REPLACE and MODULATE.

The `enumerated-type: TColorMode ColorModeNames cmReplace` line says to translate this to Pascal code such that:

- The `Mode` property in Pascal should get/set the Pascal enum type `TColorMode`.

- The `ColorModeNames` is a constant array mapping Pascal enum value TColorMode -> String.

- The default field value is `cmReplace` in Pascal. This must correspond to `"REPLACE"` default field value in X3D.

And the tool to auto-generate Pascal code from nodes does almost all the rest :)

In the manually-writted Pascal code in x3dnodes_standard_rendering.inc we just need to:

- declare the node like this:

    ```
    { Base node for color specifications. }
    TAbstractColorNode = class(TAbstractGeometricPropertyNode)
    {$I auto_generated_node_helpers/x3dnodes_x3dcolornode.inc}
    end;
    ```

    As you see, 100% of it is actually auto-generated, we just include it.

- Declare `TColorMode` enum, `TColorMode = (cmReplace, cmModulate)`. The usual place to do it is "right before the node using it". But in this case, I need this enum in some units that are "lower" than `X3DNodes` unit, so I moved the enum definition to CastleRenderOptions unit. But you should start by adding your enums right next to the `TTexturePropertiesNode`, and only move them somewhere more general (like CastleRenderOptions unit) if necessary.
- We also define a trivial map
 
    ```
    const
      ColorModeNames: array [TColorMode] of string =
      ('REPLACE', 'MODULATE');
    ```

    in the implementation section of castleinternalarraysgenerator_rendering.inc .

I hope this is useful :)

I see you have started this in https://github.com/castle-engine/castle-engine/pull/358 . Please let me know are my above comments enough to understand how to modify the `Texturing.txt` file? I can also do this myself (though I will likely in effect make a conflict with your PR https://github.com/castle-engine/castle-engine/pull/358 then).

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Thanks for these very interesting details. :-) I'm gonna try to digest everyting and update the PR, when I got some spare time. Maybe next weekend already.
