### ISSUE TITLE
Bug report: (Tiled) Rotations are not correctly shown.

### ISSUE THREAD

**Issue by Free-Pascal-meets-SDL-Website** [castle-engine/castle-engine#325]
The Tiled editor (mapeditor.org) allows for some transformations like rotation and mirroring of tiles from the tileset to be placed in the map.

Some transformations are not correctly translated into the TCastleMapControl. 

Tiled Editor:
![grafik](https://user-images.githubusercontent.com/16453692/126908592-1e7c8665-edd8-46d3-9f43-8a1a85633db6.png)

CGE (TCastleMapControl):
![grafik](https://user-images.githubusercontent.com/16453692/126908557-482543fe-527a-49c3-8f65-d6216fa1dd23.png)

(1) + (2): Correctly transformed (singly vertical/horizontal mirroring).

(3) + (4): Wrongly transformed (90° rotation left and right).

(5) + (6): Correctly transformed (vertical and horizontal mirroring after each other, and vice versa)

(7) + (8): Wrongly transformed (Vertical or horizontal morriring followed by 90° rotation). 

I assume the rotation is not implemented correctly.

Best regards,
Matthias

You may use the following test code and the attached files:

`program flipped_tiles;

{$mode objfpc}{$H+} // you can also set ObjFpc and long strings in project compiler options

uses CastleWindow, CastleTiledMap, CastleLog, CastleRectangles;
var
  Window: TCastleWindowBase;
  TiledMap: TCastleTiledMapControl;

begin
  SetHeapTraceOutput('heaptrc.log');
  InitializeLog;

  Window := TCastleWindowBase.Create(Application);
  Window.Open;

  TiledMap := TCastleTiledMapControl.Create(Application);

  { Contains flipped and rotated and flip-rotated tiles. }
  TiledMap.URL := 'castle-data:/map64-flipped-tiles.tmx';

  TiledMap.Anchor(hpMiddle);
  TiledMap.Anchor(vpMiddle);
  Window.Controls.InsertFront(TiledMap);

  Application.Run;
end.` 

![image3x3](https://user-images.githubusercontent.com/16453692/126908791-5b3ef36d-01cc-4b86-9304-df0d78904866.png)
[image3x3.tsx.txt](https://github.com/castle-engine/castle-engine/files/6874312/image3x3.tsx.txt)
[map64-flipped-tiles.tmx.txt](https://github.com/castle-engine/castle-engine/files/6874313/map64-flipped-tiles.tmx.txt)

**Comment by michaliskambi** [comment]
Thanks for the perfect testcase! This makes it much easier to test and fix. I committed your testcase to `examples/tiled/map_viewer/data/maps/test_rotations.*` files.

Indeed the rotations were not implemented. They depend on a "diagonal flip" bit set by Tiled (see https://doc.mapeditor.org/en/stable/reference/tmx-map-format/ ) and were not properly handled.

I did a partial implementation: we now rotate by 90 when we should. The result is not yet absolutely correct, see the resulting screenshot, it doesn't match your reference. Combining diagonal flip + vertical/horizontal is not right (likely because we rotate/flip in a different order, or because our tile Y goes up). I'll experiment to make a 100% proper solution.

![Zrzut ekranu z 2021-07-26 03-55-24](https://user-images.githubusercontent.com/1076978/126922894-45e9fa56-b1ab-4537-a2da-f618748dc741.png)

**Comment by Free-Pascal-meets-SDL-Website** [comment]
I'm glad this helps.

For rotations: The Tiled editor allows for 90° right- and left-rotations. And I omitted this information above.

(for Tiled reference image)
(7): Horizontal flip + 90° left-rotation.
(8): Vertical flip + 90° right-rotation

Best regards,
Matthias

**Comment by michaliskambi** [comment]
With new X3D conversion code, Tiled rotations are now perfectly reflected if you load map to TCastleScene or TCastleTiledMap ( https://castle-engine.io/tiled_maps ).

![obraz](https://user-images.githubusercontent.com/1076978/220804233-fc834516-a34c-40cf-af9d-199c177497cb.png)

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Hi there!
I saw the massive improvements on the Tiled map loader unit. Excellent work!

Best regards
Matthias
