### ISSUE TITLE
OBJ files don't support texture options

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#332]
See https://en.wikipedia.org/wiki/Wavefront_.obj_file#Texture_options

Extract the attached and open brick_tent_8.obj to see the issue

Refer to brick_tent_8.mtl - remove the -s float float float and the model works

[seperates.zip](https://github.com/castle-engine/castle-engine/files/7027103/seperates.zip)

**Comment by michaliskambi** [comment]
Fixed. 

- We parse all texture options from http://paulbourke.net/dataformats/mtl/ , https://en.wikipedia.org/wiki/Wavefront_.obj_file#Texture_options
 
- We actually handle (i.e. render) options for scale, offset and clamp.
- 
- The `map_Kd -s 2.000000 2.000000 1.000000 concrete_BaseColor.jpg` in your file is now correctly interpreted as diffuse texture, with file from `concrete_BaseColor.jpg`, with texture coordinate scale 2,2,1.

**Comment by peardox** [comment]
Did you also enable roughness mapping?

Try this as a replacement mtl - in theory the obj and gltf should look identical (they didn't before this commit)

`# Blender MTL File: 'None'
# Material Count: 2

newmtl Bricks
Ns 225.000000
Ka 1.000000 1.000000 1.000000
Kd 0.800000 0.800000 0.800000
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.450000
d 1.000000
illum 2
map_Bump Bricks_Normal.jpg
map_Kd Bricks_Color.jpg
map_Pr Bricks_Roughness.jpg

newmtl Old_concrete
Ns 225.000000
Ka 1.000000 1.000000 1.000000
Kd 0.800000 0.800000 0.800000
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.450000
d 1.000000
illum 2
map_Bump concrete_Normal.jpg
map_Kd concrete_BaseColor.jpg
map_Pr concrete_Roughness.jpg
`

*** Note that this is a corrected obj export pre-commit with map_Pr added even though Blender didn't export that definition

**Comment by michaliskambi** [comment]
P.S. I noted that your `seperates.zip` also contains the glTF version.

- It makes a warning when reading, and I think CGE is right here:

    ```
    glTF: Node index invalid: 1
    glTF: Node index invalid: 2
    ```

    That is because indeed glTF is invalid. It specifies a scene with nodes 0,1,2:

    ```
    "scenes" : [
        {
            "name" : "Scene",
            "nodes" : [
                0,
                1,
                2
            ]
        }
    ],
    ```

    ... but the `"nodes"` list has only one node, index 0.

    I see you have made this glTF file with "Khronos glTF Blender I/O v1.6.16". Please submit a bug (to Blender or directly to https://github.com/KhronosGroup/glTF-Blender-IO , after making sure it is also present in latest version), along with .blend file to reproduce it.

- Regardless of above, we don't support `KHR_texture_transform` in glTF for now, so we don't support texture transformation.

    This is just a missing (for now!) feature from CGE. It will be added.
 
Yes, it's a little weird -- in case of this particular model, the OBJ actually works better, without any warnings and with texture transformation. In general I would definitely encourage glTF over OBJ, due to lots more features, better spec etc.

**Comment by michaliskambi** [comment]
> Did you also enable roughness mapping?

Our current OBJ reader makes a Phong material (with diffuse color and texture). This is fundamentally different than a physical (PBR) material. And roughness only makes sense for PBR.

Hm, I see extensions on https://en.wikipedia.org/wiki/Wavefront_.obj_file#Physically-based_Rendering .

Hm, let me experiment. Maybe we should just use PBR for OBJ now, by default. It is more modern.

**Comment by peardox** [comment]
The original was fine (I edited it but missed a few nodes)
The missing ones are just light + cam defs so no prob - I should have deleted nodes 1 + 2

Note that Blender doesn't acrually export the PBR ATM, I did that manually.

And, yeah, I see no reason not to include PBR in OBJ - CGE can do it, Blender may catch up and other exports may already handle PBR OBJs (Assimp springs to mind)

**Comment by michaliskambi** [comment]
> And, yeah, I see no reason not to include PBR in OBJ - CGE can do it, Blender may catch up and other exports may already handle PBR OBJs (Assimp springs to mind)

The problem is that OBJ material definition is not really suited for PBR. Addition of `map_Pr` in https://en.wikipedia.org/wiki/Wavefront_.obj_file#Physically-based_Rendering is not a complete solution for "PBR in OBJ".

- It is under-specified. In what channel is roughness kept? What is the relation to metallic? It is not obvious at all that this is equivalent to glTF `metallicRoughnessTexture` that combines both roughness and metallic in the same channels on one texture.

- Various OBJ Phong parameters have to be ignored in case of PBR, which may be surprising to people. E.g. specular, shininess, ambient (for which OBJ has parameters to define as a vector or texture) all have to be just ignored when doing PBR. There is no notion in OBJ / MTL file to say "ignore Phong parameters, use PBR parameters, this is what author wants".

For these reasons, I now implemented PBR in OBJ but it is disabled by default. Set global `WavefrontPhongMaterials` to `false` in `X3DLoadInternalOBJ` to change it.

Depending on what other software does / will do, we may change this default at some point of course. And make PBR default in OBJ, and generalize `GltfForcePhongMaterials` -> `LoadForcePhongMaterials` to force Phong on all imported models.

**Comment by peardox** [comment]
It seems more sensible to default to the existing but if the model includes experimental PBR defs then use PBR instead with the new globlal essentially meaning never / always use PBR (they look different - right?).

I'll have a little play to see what happens

I always wondered why the OBJ looked drastically different to other models..
