### ISSUE TITLE
Project caption: should be editable in GCE, should be stored once

### ISSUE THREAD

**Issue by the-Arioch** [castle-engine/castle-engine#361]
As of now there seems to be no way to change project caption in GCE after the project was created.

_Same for main state name, but i am not sure if that is user-readable text or technical object id, so if changing main state name post-factum even has any sense._

The caption itself gets stored into two different files:

- CastleEngineManifest.xml
- castleautogenerated.pas

Duplication of data said to be kept "to support easy complications from outside of CGE editor"
https://github.com/castle-engine/castle-engine/issues/360#issuecomment-1008299759

Personally i do not see how it helps.
If XML file with settings and other contents is removed "outside GCE editor" there will be far worse problems, than main form caption.
And currently this duplication confuses newbs trying to understaaned "where to change that title" or trying to find where to put breakpoints to see how this value travels through Castle Engine internals.

I can see a point though, in having at least some caption, in case settings XML can not be loaded/parsed, then at the moment of bad crash the application would have at least some preliminary caption. Still would be nice if that caption was overrode from XML settings later

**Comment by michaliskambi** [comment]
As I i answered already on the forum, of course there's a way to change the caption:

- edit the `caption` in `CastleEngineManifest.xml`

- use _"Regenerate Project (overwrites LPI, DPR, DPROJ, CastleAutoGenerated)"_

We want to make it better, but not in the way you request here (by removing the duplication). Instead:

- at some point, everything from `CastleEngineManifest.xml` should be editable using some CGE editor GUI

- and the `castleauotgenerated.pas` will be regenerated automatically.

I also don't like the duplication, but in practice we need it.

- We need to keep the caption, version in `CastleEngineManifest.xml`, because we need to know them in CGE build tool / editor to create packages for all platforms. E.g. caption is also used for Android / iOS / Nintendo Switch application caption. And we don't want to add parsing (even hacky parsing specialized for `castleauotgenerated.pas`) to CGE build tool / editor. They need this information in `CastleEngineManifest.xml` in our format.
 
- We need to keep them in Pascal, because we need to know them even before we can access the filesystem. E.g. on Android we cannot read anything too early, so we need such basic information (to even start a useful log, with valid information) available in code.

    And this Pascal file has to be present in some directory visible to Lazarus / Delphi immediately (not e.g. only created temporarily in `castle-engine-output`). That allows to open the project in Lazarus / Delphi, hit F9, and it works.

I'm closing this issue, in favor of https://github.com/castle-engine/castle-engine/issues/363 with a description reflecting how I plan to do it.
