### ISSUE TITLE
The new version of `castlewindow_winapi.inc` breaks TCastleWindow entirely on 64-bit Windows 10

### ISSUE THREAD

**Issue by Akira13641** [castle-engine/castle-engine#364]
All applications immediately raise an `ECheckFailed` on startup now, saying specifically "CreateWindowEx failed", when built with FPC 3.3.1.

Basically it would seem that whatever you were already doing previously was actually correct, while the new way isn't. Likely has something to do with strings not being converted properly before getting passed into WinAPI functions, or something like that.

I can personally verify the following:
- reverting just that file and nothing else to the previous revision makes everything work properly again
- if you actually set the off-by-default `CASTLE_WINAPI_UNICODE` define that existed in the previous revision to be on, you get the exact same `CreateWindowEx` exception as seen with the new revision.

**Comment by the-Arioch** [comment]
Should be related to FPC version rather than Windows.

Can you check in FPC 3.2.2 ?

**Comment by Akira13641** [comment]
I don't have that installed, however, I can do you one better and tell you exactly what the issue is, as I figured it out after debugging a bit.

It's actually caused by the change of `Application.WndClassname` in `castlewindow_winapi.inc` from `String` to `UnicodeString` impacting code elsewhere in `castlewindow_wgl.inc`.

Specifically, at the moment, non-wide `CreateWindowEx` is still being called in `castlewindow_wgl.inc` starting at line 129, with the following bit at line 130 being the overall culprit:

`PChar(Application.wndClassName),`

That's not a valid cast obviously when `Application.WndClassName` is a `UnicodeString.` Changing the line to:

`PChar(UTF8Encode(Application.wndClassName)),`

completely fixes this issue for me.

**Comment by michaliskambi** [comment]
@Akira13641 Thanks for the report and finding the culprit, fixed!

The problem was not related to FPC version. It was visible only when (and always when) you used multi-sampling, i.e. anti-aliasing. Only then `castlewindow_wgl.inc` did an extra `CreateWindowEx` call, which was now wrong.

I upgraded it now to use Unicode version.

In general: Please provide as much information -- how do you encounter the bug, which application do you run -- when you have an error like this :) Writing """breaks TCastleWindow entirely""" left us wondering, as both me and @the-Arioch tested the modified version. You must have tested on an example / application using multi-sampling (maybe view3dscene with anti-aliasing active), only then the bug was visible.
