### ISSUE TITLE
type conversion warning

### ISSUE THREAD

**Issue by the-Arioch** [castle-engine/castle-engine#366]
Proper Delphi64/FPC types to be:
```
     LONG_PTR = PtrInt;
     ULONG_PTR = PtrUInt;
```
code: D:\DelphiProjects\Libs\Games\castle-engine\src\deprecated_units\castlewindowsfonts.pas
```
    EnumFontFamiliesEx(Dc, {$ifdef FPC} @ {$endif} LogFont,
      { TODO: temporary, I just make this unchecked } @EnumFontFamExProc_ByObject,
      Integer(@InternalInfo), 0);
```
> castlewindowsfonts.pas(267,7) Warning: Conversion between ordinals and pointers is not portable

AFAIR it is true, in Win64 models Integers are still 32-bit yet pointers are 64-bit, but you can check `SizeOf`, i did not.

**Comment by michaliskambi** [comment]
Thanks, fixed.

Indeed `Integer` is 32-bit, on all platforms and all compilers. That typecast was wrong.

See also our notes on integer types on https://castle-engine.io/coding_conventions#_do_not_use_longint_longword_use_int32uint32_int64uint64_integercardinal .

Though please note that this unit (`CastleWindowsFonts`) is deprecated. It hasn't been tested in quite a while, and we really discourage using it. It's a Windows-specific way of loading system fonts, and it didn't get much usage in cross-platform games, which should rather load fonts from TTF/OTF using FreeType using existing `TCastleFont.Load`.

**Comment by the-Arioch** [comment]
> Though please note that this unit (CastleWindowsFonts) is deprecated

I was surprised by it. Still, i saw (for a split second) that warning when
was compiling GCE which triggered compiling base and component packages. It
took a while to figure out how to find that warning.


> It's a Windows-specific way of loading system fonts,

Well, you know i think loading OS-provided fonts is actually a good idea :-D

Maybe there could be some simple extension API and then optional
per-platform packages?
Extending internal URI-s with custom non-GC and non-HTTP schemes seems a
potentially good feature. I thought about a scheme followed with a CSS-like
specification of fonts to fetch it from OS

**Comment by michaliskambi** [comment]
> Maybe there could be some simple extension API and then optional per-platform packages?

You can freely create additional components on top of CGE already. You can already define your own protocol schemes, and register them so that CGE `CastleDownload` unit with everything inisde will handle it. There are examples on it in CGE.

Same answer for OS-specific fonts. I don't object to anyone adding more ways to add fonts, on top of CGE. 

But loading system-specific fonts is not something I want to support, in core CGE repo. Because it's a non-trivial task (esp. if you don't want to limit to just Windows), and it is inherently useless for cross-platform games, where you cannot depend on same system fonts existing on all platforms, you cannot even depend that there are any loadable system-wide fonts on some exotic platforms.
