### ISSUE TITLE
Wiki example - broken link

### ISSUE THREAD

**Issue by the-Arioch** [castle-engine/castle-engine#369]
https://castle-engine.io/how_to_render_2d

End of chapter 1.

>  This is documented at the bottom of http://castle-engine.io/manual_2d_ui_custom_drawn.php — basically, look at your ScreenRect and scale all....

The " — basically" part was erratically made into part of URL.

P.S. i get that you hate focusless long forum threads that "no one would manafge to learn from"
But is creating tickets over so trivial fix-and-forget lapses realyl better?

P.P.S.  `2. Why there are 2 approches` - approAches.

Maybe it would make sense to add some typo easy-reporting script to the wiki?
Like orphus.ru - there are other scripts like that too, but this one was once most advertized one.
I dislike that Orphus seeking simplicity and maybe preventing spam does not allow reader to add his free-form notes to webmaster, only to mark the wrong text and send it. There were other similar scripts though.

**Comment by michaliskambi** [comment]
> P.S. i get that you hate focusless long forum threads that "no one would manafge to learn from"
> But is creating tickets over so trivial fix-and-forget lapses realyl better?

It is better. It means that this issue is isolated, it is clear what to do (and when it is solved), it doesn't just make a noise in other threads.

> Maybe it would make sense to add some typo easy-reporting script to the wiki?

You can follow the links at the bottom - proposing a fix to docs (the ones converted to AsciiDoctor, which is not all for now, but it will be, as per my notes on https://castle-engine.io/wp/2021/12/31/many-documentation-upgrades-using-asciidoctor-as-our-primary-way-to-write-documentation-michalis-thoughts-and-plans-about-our-documentation/ ) is quite easy, just edit the file (you can even do it through GitHub website, and it can preview AsciiDoctor) and make a PR.

For now I don't plan to add more ways.
