### ISSUE TITLE
[info] view3dscene 4.1 lighting on dae import, but OK when using "nice headlight"

### ISSUE THREAD

**Issue by splace** [castle-engine/castle-engine#385]
with highlight...

![rocinante_0](https://user-images.githubusercontent.com/1234848/156089389-b141d846-b083-440c-87b4-4377d500f070.png)

with nice headlight...

![rocinante_0 (1)](https://user-images.githubusercontent.com/1234848/156089392-ab2cefd8-0ee6-47fb-bfa5-79d0505ed713.png)

source file (dae)..

[rocinante.zip](https://github.com/castle-engine/castle-engine/files/8158188/rocinante.zip)

**Comment by michaliskambi** [comment]
I see the model has a negative scale on some shapes, this causes incorrect lighting. If this is your model, I'd suggest to avoid negative scale -- it doesn't play nicely with lighting, and negative scale inverts normal vectors.

That said, we do have a solution for this, but it is not yet merged to master as it requires more testing (that it will not cause any regressions). It's on branch https://github.com/castle-engine/castle-engine/compare/lighting-with-negative-scale , it's a really simple change.

With this, view3dscene shows correct lighting immediately, see this screenshot:
![rocinante_0](https://user-images.githubusercontent.com/1076978/156188187-d05dbe39-71da-43e5-a0fe-0b0d0980ee14.png)

Note that some materials still don't look good on the other side (the model doesn't look completely symmetric anyway). I didn't investigate it, my first guess would be that it's a problem in model. If you have a corresponding Blender file and can attach it, I would appreciate it -- this would allow to easily investigate.

**Comment by splace** [comment]
model was free from sketchfab, for 3d printing.

but, i am confused...

your 'fixed' screenshot shows asymmetry, as you mentioned, but, to me, this just looks identical to the 'unfixed'.

the 'nice headlight' clearly shows, what i think are, the correct colours, ie symmetric.

**Comment by michaliskambi** [comment]
In the version without the fix (rendered with view3dscene using CGE `master` branch), some parts (with negative scale) are just completely black. The diffuse and specular light components are always pure black, because normal vectors point to the wrong side (after they are transformed by negative scale).

In the version with fix (rendered with view3dscene using CGE `lighting-with-negative-scale` branch) these parts are not black anymore. Some are light, some are dark but correctly lit (the model just uses some dark colors for diffuse).

So there is a definite difference, although it may be hard to see on screenshots -- I annotated them below. It's easy to see once you play with view3dscene and rotate around, the lighting in `lighting-with-negative-scale` branch works OK on all sides.

![1_unfixed](https://user-images.githubusercontent.com/1076978/156259450-88b1f480-9cbb-4ea5-9c58-8ad68e67a9b7.png)
![2_fixed](https://user-images.githubusercontent.com/1076978/156259467-81338d16-916c-4c69-8173-26e51944566c.png)

If you turn off the regular headlight (by Ctrl+H in view3dscene) and use the "Screen Effects -> Flashlight (Nice Headlight)" then it renders the model without light (so only the ambient term is visible, because there are no normal lights) and the ambient term is just increased by "color=pow(color,1/4)" operation in the middle of the screen. The name "Flashlight (Nice Headlight)" may be misleading, it's really just a cheap trick in screen-space -- it's not at all a correct simulation of lighting. See https://github.com/castle-engine/view3dscene/blob/master/embedded_data/screen_effects/flashlight.x3dv . The effect is more a demo of https://castle-engine.io/x3d_extensions_screen_effects.php than a generally-useful headlight calculation.

But, note: it is interesting that actually for me, "Screen Effects -> Flashlight (Nice Headlight)" effect is also worse than for you. The model is not symmetric anyway, attaching screenshot.

![3_headlight_effect](https://user-images.githubusercontent.com/1076978/156259561-3942584a-e1d4-4820-897b-3b8d32164643.png)

Testing it out in https://www.3dviewer.net/ and https://www.creators3d.com/online-viewer , similar artifacts are visible.

![Zrzut ekranu z 2022-03-01 23-14-29](https://user-images.githubusercontent.com/1076978/156260352-66a4fdb6-dd5f-4edb-bf39-d543a560723c.png)
![Zrzut ekranu z 2022-03-01 23-13-15](https://user-images.githubusercontent.com/1076978/156260355-8b25892e-f152-4b54-9bcd-ee39c37ba04d.png)



Importing it to Blender, exporting to DAE again, also shows the same artifacts. 

Interestingly, exporting it to glTF from Blender makes everything good -- somehow something along the glTF conversion fixes the problems.

Still, the original DAE seems to have something wrong, and evidently Blender can even preserve this "incorrectness" when doing DAE->Blender->DAE. I wasn't able to find anything weird in Blender materials though, all I got was confirmation that shapes have negative scale.

![Zrzut ekranu z 2022-03-01 23-12-00](https://user-images.githubusercontent.com/1076978/156259655-5e92d650-1f7d-4a38-967a-b29ef95e6bd2.png)

So, the summary of my thoughts:

1. CGE problem is indeed caused by negative shape scale, and `lighting-with-negative-scale` fixes this OK.

2. The model has problems with materials anyway, that I don't fully understand. But other software ( https://www.3dviewer.net/ , https://www.creators3d.com/online-viewer , Blender) shows it too.

3. I do not understand why for you, "Flashlight" shows a symmetric model. It doesn't for me. Is it possible the material has some weird parameter outside of normal range, that causes some undefined behavior on various GPUs?

If you get it from SketchFab: is there a glTF alternative? We recommend using glTF over Collada anyway. And SketchFab autogenerates glTF from what I've seen for all (or some?) models.

**Comment by splace** [comment]
thanks, i thought the difference, between 'headlight' and  'nice headlight' might be something significant.

> But, note: it is interesting that actually for me, "Screen Effects -> Flashlight (Nice Headlight)" effect is also worse than for you. 

i guess its shader code? that is working as intended for my gpu for the negative faces and for the 'flat' lighting of 'nice headlight'.  also happens for 'brighten'

info....
```
OpenGL information (detected by view3dscene):

--------
Version:
  Version string: 4.5 (Compatibility Profile) Mesa 21.3.6
  Version parsed: major: 4, minor: 5, release exists: False, release: 0, vendor-specific information: "(Compatibility Profile) Mesa 21.3.6"
  Vendor-specific version parsed: major: 21, minor: 3, release: 6
  Vendor: AMD
  Vendor type: Unknown

  Renderer: AMD OLAND (DRM 2.50.0, 5.14.21-210.current, LLVM 13.0.0)
  Fglrx (ATI on Linux): False
  Mesa: True

  Buggy glGenerateMipmap(EXT): False
  Buggy GL_LIGHT_MODEL_TWO_SIDE: False
  Buggy VBO: False
  Buggy shader shadow map: False
  Buggy FBO rendering to multi-sampling texture: False
  Buggy FBO rendering to cube map texture: False
  Buggy swap buffers with non-standard glViewport: False
  Buggy 32-bit depth buffer: False
  Buggy GLSL gl_FrontFacing: False
  Buggy GLSL read varying: False
  Buggy Pure Shader Pipeline: False
  Buggy Texture Size Above 2048: False
  Buggy Shader Bump Mapping num_steps: False

------------------------
Real versions available:
(checks both version string and actual functions availability in GL library, to secure from buggy implementations)

  1.2: True
  1.3: True
  1.4: True
  1.5: True
  2.0: True
  2.1: True
  3.0: True
  3.1: True
  3.2: True
  3.3: True
  4.0: True

---------
Features:
  Shaders (GLSL) support: Standard
  => Enable deprecated (fixed-function) support: False
  Multi-texturing: True
  Framebuffer Object: Standard (or ARB "core extension")
  Multi-sampling for FBO buffers and textures: True
  Vertex Buffer Object: True
  GenerateMipmap available (and reliable): True
  Cube map textures: Standard
  Compressed textures supported: [DXT1_RGB, DXT1_RGBA, DXT3, DXT5, ASTC_4x4_RGBA, ASTC_5x4_RGBA, ASTC_5x5_RGBA, ASTC_6x5_RGBA, ASTC_6x6_RGBA, ASTC_8x5_RGBA, ASTC_8x6_RGBA, ASTC_8x8_RGBA, ASTC_10x5_RGBA, ASTC_10x6_RGBA, ASTC_10x8_RGBA, ASTC_10x10_RGBA, ASTC_12x10_RGBA, ASTC_12x12_RGBA, ASTC_4x4_SRGB8_ALPHA8, ASTC_5x4_SRGB8_ALPHA8, ASTC_5x5_SRGB8_ALPHA8, ASTC_6x5_SRGB8_ALPHA8, ASTC_6x6_SRGB8_ALPHA8, ASTC_8x5_SRGB8_ALPHA8, ASTC_8x6_SRGB8_ALPHA8, ASTC_8x8_SRGB8_ALPHA8, ASTC_10x5_SRGB8_ALPHA8, ASTC_10x6_SRGB8_ALPHA8, ASTC_10x8_SRGB8_ALPHA8, ASTC_10x10_SRGB8_ALPHA8, ASTC_12x10_SRGB8_ALPHA8, ASTC_12x12_SRGB8_ALPHA8]
  3D textures: Standard
  Textures non-power-of-2: True
  Blend constant parameter: True
  Float textures: True
  Depth textures: True
  Packed depth + stencil: True

  All extensions: GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_copy_depth_to_color GL_NV_depth_clamp GL_NV_fog_distance GL_NV_half_float GL_APPLE_packed_pixels GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_depth_bounds_test GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_ATI_texture_compression_3dc GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_ATI_texture_mirror_once GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_texture_array GL_EXT_texture_compression_latc GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_AMD_performance_monitor GL_EXT_texture_buffer_object GL_AMD_texture_texture4 GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_buffer_object GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_compatibility GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_ATI_meminfo GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_copy_image GL_NV_texture_barrier GL_ARB_draw_indirect GL_ARB_get_program_binary GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_precision GL_ARB_shader_subroutine GL_ARB_texture_compression_bptc GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_viewport_array GL_EXT_direct_state_access GL_EXT_shader_image_load_store GL_EXT_vertex_attrib_64bit GL_NV_vdpau_interop GL_AMD_multi_draw_indirect GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_base_instance GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shader_atomic_counters GL_ARB_shader_image_load_store GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_query_buffer_object GL_AMD_shader_trinary_minmax GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_compute_shader GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_fragment_layer_viewport GL_ARB_framebuffer_no_attachments GL_ARB_invalidate_subdata GL_ARB_multi_draw_indirect GL_ARB_program_interface_query GL_ARB_robust_buffer_access_behavior GL_ARB_shader_image_size GL_ARB_shader_storage_buffer_object GL_ARB_stencil_texturing GL_ARB_texture_buffer_range GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_AMD_pinned_memory GL_ARB_bindless_texture GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_compute_variable_group_size GL_ARB_enhanced_layouts GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_query_buffer_object GL_ARB_seamless_cubemap_per_texture GL_ARB_shader_group_vote GL_ARB_shading_language_include GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_NVX_gpu_memory_info GL_ARB_ES3_1_compatibility GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_cull_distance GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_get_texture_sub_image GL_ARB_pipeline_statistics_query GL_ARB_shader_texture_image_samples GL_ARB_texture_barrier GL_ARB_transform_feedback_overflow_query GL_EXT_polygon_offset_clamp GL_EXT_shader_image_load_formatted GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_NV_shader_atomic_int64 GL_ARB_ES3_2_compatibility GL_ARB_gpu_shader_int64 GL_ARB_parallel_shader_compile GL_ARB_shader_atomic_counter_ops GL_ARB_shader_ballot GL_ARB_shader_clock GL_ARB_shader_viewport_layer_array GL_EXT_shader_samples_identical GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_ARB_gl_spirv GL_ARB_spirv_extensions GL_EXT_window_rectangles GL_MESA_shader_integer_functions GL_ARB_polygon_offset_clamp GL_ARB_texture_filter_anisotropic GL_EXT_memory_object GL_EXT_memory_object_fd GL_KHR_parallel_shader_compile GL_NV_alpha_to_coverage_dither_control GL_EXT_EGL_image_storage GL_EXT_texture_shadow_lod GL_INTEL_blackhole_render GL_MESA_framebuffer_flip_y GL_NV_compute_shader_derivatives GL_EXT_EGL_sync GL_EXT_demote_to_helper_invocation 

---------------------------
Current buffers bit depths:
  Color (red / green / blue / alpha): 8 / 8 / 8 / 0
  Depth: 24
  Index: 0
  Stencil: 8
  Accumulation (red / green / blue / alpha): 0 / 0 / 0 / 0
  Double buffer: True
  Multi-sampling (full-screen anti-aliasing) possible: True
    Current: 8 samples per pixel

-------------
Stack depths:
  Attributes: 16
  Client attributes: 16
  Modelview: 32
  Projection: 32
  Texture: 10
  Name: 64

-------
Limits:
  Max clip planes: 8
  Max lights (fixed-function limit): 8
  Max eval order: 30
  Max list nesting: 64
  Max pixel map table: 256
  Max texture size: 16384
  Max viewport dims (width, height): 16384 16384
  Max texture units (shader pipeline): 32
  Max texture units (fixed-function): 8
  Max cube map texture size: 16384
  Max 3d texture size: 2048
  Max texture max anisotropy: 16
  Query counter bits (for occlusion query): 64
  Max renderbuffer size: 16384

-------
Memory (in Kb):
  Total: 3141432
  Current: 963124
  Current for VBO: 963124
  Current for Textures: 963124
  Current for Renderbuffers: 963124

```

> CGE problem is indeed caused by negative shape scale, and lighting-with-negative-scale fixes this OK.

nice.

i will try to remember to select glTF, if not, then inspect for issues.

**Comment by michaliskambi** [comment]
view3dscene now has a menu item "View -> Robust Negative Scale" to activate the "fix for lighting in case of negative scale".

I hope to one day just make it a default -- but for now, it is disabled by default, as it has a small performance cost and is not necessary on most models.
