### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by limelect** [castle-engine/castle-engine#386]
Downloaded 7 and D10.2.3 and Lazarus' latest
On Delphi wile in debug
Run outside ID almost OK some problems
procedure TTextureFontData.TGlyphDictionary.SetItems(const AKey: TUnicodeChar; const AValue: TGlyph);
begin
  AddOrSetValue(AKey, AValue);<<<<Access violation All demos
end;

All new Lazarus
On Lazarus compiling package
   Empty: TRectangle = (Left: 0; Bottom: 0; Width: 0; Height: 0); 

Compile package castle_base 6.2: Exit code 1, Errors: 2, Warnings: 3
castlegenericlists.pas(56,40) Warning: Symbol "MaxGListSize" is deprecated
castlerectangles.pas(120,14) Error: Type "TRectangle" is not completely defined
castlerectangles.pas(302,14) Error: Type "TFloatRectangle" is not completely defined
castlegenericlists.pas(56,40) Warning: Symbol "MaxGListSize" is deprecated
castlegenericlists.pas(56,40) Warning: Symbol "MaxGListSize" is deprecated

So no demo can be compiled

**Comment by michaliskambi** [comment]
As for Delphi 10.2.3:

Hm, admittedly I have no idea why it causes Access Violation there. It's a call to standard method `AddOrSetValue` of `TDictionary<TUnicodeChar, TGlyph>`. It works with later Delphi and all FPC versions we tested.

I do not have access to this Delphi version now. Can you upgrade to Delphi 10.4 (free community edition is OK) or 11? These are the versions we tested, see https://castle-engine.io/supported_compilers.php#section_platforms . I hoped that a few older Delphi versions could also "work out of the box", but obviously this is not the case.  Maybe we should just officially say that we support only Delphi >= 10.4.

As for Lazarus:

Looking at the message, you compile "package castle_base 6.2". This is a really old CGE version. The line numbers is error messages confirm it, and in the latest CGE the `TRectangle.Empty` is not even defined using `Empty: TRectangle = (Left: 0; Bottom: 0; Width: 0; Height: 0);` , see https://github.com/castle-engine/castle-engine/blob/master/src/base/castlerectangles.pas . 

It should say "package castle_base 6.5" (for CGE 7.0-alpha-xxx versions, as we cannot express "7.0 alpha" in LPK settings). 

Assuming you have downloaded recently a fresh version of CGE from https://castle-engine.io/ (and you must have, otherwise it would not compile at all with Delphi :) ), it means that you have some old CGE version laying around on your disk, registered with Lazarus. Please follow https://castle-engine.io/install to register latest CGE LPK versions with Lazarus. It's best to just use "Register Lazarus Packages" from CGE editor.
