### ISSUE TITLE
Dynamic Batching doesn't batch all shapes in certain Spine models

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#388]
Not sure if this is a bug, or a limitation that I am not aware of, but some of my Spine models doesn't have all of its shapes combined even though they should share the same material.

Some of the public available tests:
- The `girl.json` model from `demo-models`: Has 37 shapes. After enable Dynamic Batching `view3dscene` reports it still has 22/37 shapes render on screen.
- `satania` model from my toy project `satania-buddy`: Has 36 shapes. After enable Dynamic Batching `view3dscene` reports it still has 23/36 shapes render on screen.

For comparison, `dragon.json` from `demo-models` has 57 shapes. After enable Dynamic Batching `view3dscene` reports only 1/57 shapes render on screen.

The common thing in these models is that they both contain weighted meshes and perform free-form deformation/skinned animations.

**Comment by michaliskambi** [comment]
I found the culprit. It was a limitation in the CGE batching algorithm... a limitation that I could overcome :)

Long story short, if you open the girl from https://github.com/castle-engine/demo-models/tree/master/spine/weighted_mesh/girl now, with latest CGE master branch, and activate dynamic batching, you will see 1 shape rendered :)

Details, if you're curious:

1. The biggest issue was that CGE batching couldn't combine nodes other than `IndexedFaceSet`. And the "mesh" attachment in Spine caused creation of `IndexedTriangleSet`. So resulting Spine model had a combination of `IndexedTriangleSet` and `IndexedFaceSet` which we couldn't merge (we also cannot merge them "out of order" due to rendering with blending when we must respect order).

2. Minor issue was also that "region" generated `IndexedFaceSet` but with different `NormalPerVertex` which also caused dynamic batching to break merging.

Solutions I considered/done:

A. *(done and rejected)* My initial quick solution to confirm that this is the case (that fixing 1 and 2 above is enough) was changing Spine import to generate always `IndexedFaceSet`, never `IndexedTriangleSet`.

I'm attaching a patch just for historians, I'm not going to commit it (because it's not optimal to convert triangles to more generic `IndexedFaceSet` that will then be split back into triangles). This quickly proved I can get 1 shape from 37, for girl from https://github.com/castle-engine/demo-models/tree/master/spine/weighted_mesh/girl . So I know I found all culprits.

B. *(done and committed)* The solution I did was to allow merging `IndexedTriangleSet` with `IndexedTriangleSet`, and make Spine import always produce `IndexedTriangleSet`.

This was a bit more work but also more optimal, and also good for glTF files (which is probably CGE most important format right now) -- the most common node type resulting from glTF import (Blender-> exporter always seems to use this) is `IndexedTriangleSet`.

So we want to have dynamic batching support `IndexedTriangleSet` nicely.

C. *(not done, maybe in the future but low priority)* In the future we could allow merging `IndexedFaceSet` with `IndexedTriangleSet`. It is possible, in the end polygons in `IndexedFaceSet` can be split into triangles at the moment of merging. It would require some new code, and I'm not sure is it worth the trouble now, but it is something we could attempt in the future.

P.S. As for Satania testcase, I see in https://github.com/Kagamma/satania-buddy-data/tree/master/sprites/satania you keep generated X3D versions. I looked inside them (in Emacs and view3dscene) and it looks like the same culprit, thus the same fix should help. To test it definitely, you should open in view3dscene the original JSON, to convert them all to `IndexedTriangleSet` that we can merge perfectly now. I could not find original JSON in https://github.com/Kagamma/satania-buddy or other repos referenced by `install-submodules.sh` .

**Comment by michaliskambi** [comment]
[spine_generate_indexed_face_sets.patch.txt](https://github.com/castle-engine/castle-engine/files/9227756/spine_generate_indexed_face_sets.patch.txt)

**Comment by michaliskambi** [comment]
![test_1](https://user-images.githubusercontent.com/1076978/182003678-6c8374e9-a405-4e06-b67a-3740cc5aef5d.png)

**Comment by Kagamma** [comment]
Thanks! I use generated X3D instead of JSON in my projects because X3D loads way faster than JSON, especially when the model contains weighted meshes / free-form deformation (which is understandable, given on how we handle those in CGE at the moment)

I also start integrating my official spine runtime component (just done it yesterday), so all these limitations should not affect me anymore :)
