### ISSUE TITLE
Issue with textures when using with PROTO

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#398]
I assume this bug related to how CGE cache things. See `model.x3dv` for reference.
[palette.zip](https://github.com/castle-engine/castle-engine/files/9164079/palette.zip)

![image](https://user-images.githubusercontent.com/7451778/180351384-ac5c721f-dd16-44ac-84ac-8dccb4091c08.png)

**Comment by michaliskambi** [comment]
Thank you! Fixed. I also added an automatic test (using your testcase) to make sure this bug never returns :)

Details: Expanding PROTO should in general create copies of the relevant nodes (unconnected to originals). But here mistakenly the `ImageTexture` nodes were shared between 2 instances of prototype `PaletteModel`. I.e. we had

- 2x Transform (good)
- 2x ComposedShader (good)
- But only 2x ImageTexture (while we should have 4x ImageTexture, 2 for each ComposedShader)

That's because expanding prototypes didn't account for X3D "interface declarations" which is a fancy name for "extra/custom fields" specified in ComposedShader.

Now they are expanded OK.
