### ISSUE TITLE
Make TCastleSceneCore methods virtual and protected

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#401]
This feature request is based on my experience when working with custom components like https://github.com/Kagamma/cge-3d-particle-emitter and https://github.com/Kagamma/spine-runtimes

Background: I often create components that behave similar to `TCastleScene`. To do that, all of my components inherited from `TCastleSceneCore`, and try to recreate the same API interface as close to `TCastleScene` as possible. As many methods in `TCastleSceneCore` are not virtual, I have to create similar methods with the same name. This of course raise an issue:

- If users declare variable of type `TCastleSceneCore`, then later assign it to one of my components, then whenever they use, for example, `URL` to assign resources, they have to explicit cast it, like `TCastleSpine(model).URL := 'path-to-resource'`, otherwise it will call `TCastleSceneCore`'s `SetURL()` instead of `TCastleSpine`'s `SetURL()`. See https://github.com/Kagamma/satania-buddy/blob/master/src/satania/mcdowell.pas#L254 for one real-world example.

**Comment by michaliskambi** [comment]
( I'm closing this, giving reasons below, but of course feel welcome to discuss below if this doesn't seem like a good answer. I can always be wrong and no decision is set in stone :) )

1. Basically, I don't want to do this because `TCastleSceneCore` interface (and implementation) defines _"a scene loaded from a graph of X3D nodes"_. It is a not a generic class to define _"any content loaded from URL that can be rendered"_. So it's not a good class to derive new classes from it, and e.g. `TCastleParticleEmitter` should not descend from it, it should descend from `TCastleTransform` (as it does now, https://github.com/Kagamma/cge-3d-particle-emitter/blob/master/src/CastleParticleEmitter.pas , I recall that was after my suggestion in the past).

    `TCastleSceneCore`, aside from `URL` property, has stuff like `Time`, `PlayAnimation`, `Node`, `AnimationTimeSensor`, `Spatial`, `ProcessEvents`, `ExposeTransforms`, `Load(TX3DRootNode, ...)`. Most these things are specific to "a scene that is a graph of X3D". You should not try to reuse this class for other purposes, as then some of the API would not make sense, and some of the implementation (the whole X3D events processing done by `TCastleSceneCore`) would be unnecessry.

    The class that you should use to derive new things from (that are not "a graph of X3D nodes") is `TCastleTransform`. This has a lot of protected and virtual methods, and it is tested as a a good base class. E.g. `TCastleImageTransform` ( https://castle-engine.io/viewport_and_scenes#_image_tcastleimagetransform ) derives from `TCastleTransform`, defining own `TCastleImageTransform.URL`. It does indeed cause some additional work (the `TCastleImageTransform.URL` and `TCastleSceneCore.URL` are independent properties) but it makes a good separation (these URLs accept different file types and they behave differently).

    So, in short, I believe the `TCastleParticleEmitter` and your new Spine renderer (using Spine runtime, without conversion to X3D nodes) should just descend from `TCastleTransform`.

    Indeed it means that `URL` property is repeated, independently, in a number of classes -- but this makes sense in my eyes, each time `URL` property accepts different file types. 

    We could think of introducing `TCastleTransformFromUrl` in the future, though for now it seems like a complication without a big use-case for me. I didn't find a need to e.g. unify `TCastleTransformImage` and `TCastleSceneCore` like that.

2. Moreover (this is a minor argument, but I just want to communicate what are my plans for future):

    It is likely that `TCastleSceneCore` will disappear in the future, i.e. it will be a deprecated alias for `TCastleScene`. The current separation between `TCastleSceneCore` and `TCastleScene` is nice for implemetation (to keep big rendering code out of already-big `TCastleSceneCore` class), but in the long run it should be hidden better from user. We should just expose `TCastleScene`, and have internal `TCastleInternalSceneRenderer`. This would also lend itself nicely to future alternative renderers, like Vulkan.
