### ISSUE TITLE
Can't switch from TCastle2DNavigation to TCastleExamineNavigation

### ISSUE THREAD

**Issue by hertsog** [castle-engine/castle-engine#408]
Not sure if it is actually View3DScene of CastleEngine problem.

**How to reproduce:**
In View3DScene when 2D navigation mode is selected then it is not possible to select Examine mode. Nothing happens when Examine button is pressed or chosen from the menu.

**Code responsible for this behavior:**
In file castleviewport_autonavigation.inc, function TCastleAutoNavigationViewport.ExamineNavigation, line:
`if not (Navigation is TCastleExamineNavigation) then`.

The reason is that when Navigation is TCastle2DNavigation then `Navigation is TCastleExamineNavigation` evaluates to _True_ thus not running the code under the **if** statement.

Also to verify the reason I tested that changing the **if** statement to
`if not (Navigation is TCastleExamineNavigation) or Navigation is TCastle2DNavigation then`
did solve the problem (but it probably is not the correct solution).

**Comment by michaliskambi** [comment]
Thank you for the report and great (and of course correct) analysis! I wish all bugreports came with such analysis to make my life easier :)

Indeed, the "2D" navigation is controlled in view3dscene a bit differently than other navigation types (because I didn't want to keep extending the deprecated TCastleAutoNavigationViewport ). And yeah, it interacted in a surprising way with the `TCastleAutoNavigationViewport.SetNavigationType` logic and things it calls -- everything in `TCastleAutoNavigationViewport` effectively thinks "we're already in Examine mode, no need to do anything".

I fixed it by explicit check at `SetNavigationType` to do the right thing, so the `TCastle2DNavigation` instance is freed near the code that creates it (`unt2D: Viewport.Navigation := TCastle2DNavigation.Create(Viewport)`).
