### ISSUE TITLE
[Feature Request] Make it possible to compile Castle Engine and use it as dynamic library

### ISSUE THREAD

**Issue by Grabli66** [castle-engine/castle-engine#416]
I think this will speed up the process of building the application. There will be no linking of the engine code with the application into one executable file.
I know there is a "cache" option for precompiling engine code. 
But even with that, a simple project compiles in about 7 seconds on my computer with SSD.

**Comment by michaliskambi** [comment]
Putting engine into a shared library would be non-trivial work:

- need to use shared memory manager,
- need to make sure FPC version used for library and application is precisely the same so that layout of classes in memory is equal,
- need to make sure things like "is" / "as" work across the application / library (your code can use `X is TCastleTransform`, and you compile it with `CastleTransform` unit, but the comparison must be done versus `TCastleTransform` class defined in the library),
- need to make sure exceptions raised by library land in application OK,
- other details, see recent Lazarus mailing list thread: https://lists.lazarus-ide.org/pipermail/lazarus/2022-November/239997.html with helpful links like https://wiki.freepascal.org/Lazarus/FPC_Libraries , https://wiki.freepascal.org/shared_library .

This is similar to a reoccuring question on FPC maling lists about putting FPC RTL in a shared library. It can be done... but there are lots of issues to take care of, new ways how things can break :)

So I do not want to go this route. Not before Lazarus is using libraries for it's packages (like Delphi BPL), and FPC RTL is distributed in a shared library, and in general Pascal (both FPC and Delphi) ecosystem decides that using shared libraries for every package is the convention.

Moreover, it's not obvious how much a shared library for CGE would really help with 7 seconds building on your system.

I tested on my oldest laptop, ~8 years old now, without SSD. Recompilation of ready application is 4.7 seconds. I didn't measure it precisely, but from a glance, only around half of it is spent in the linking phase, so we have ~2.5 seconds to save. (The rest of time is spent analyzing what needs to be recompiled (which wouldn't be faster when using a shared library) and recompiling the main program file code.) And when CGE is a shared library, note that we still have to link the final application, it's just smaller. So we will not save 2.5 seconds, we will save maybe 1.5 seconds from it.
 
The additional burden of having CGE as a shared library is not worth it. I.e. it would be really a lot of work just to save 1.5 seconds.

Note: If you didn't change any source code, you can always do "Run Without Recompiling" (Shift + F9) which is of course lighting fast from editor.
