### ISSUE TITLE
To have correct rendering order when blending, one should call SortBackToFront; this should not be necessary in future engine versions

### ISSUE THREAD

**Issue by Freedomax** [castle-engine/castle-engine#427]
![GIF 2022-12-23 21-19-29](https://user-images.githubusercontent.com/26040454/209343001-d4049079-0f14-433d-901b-ae1edc9d1988.gif)
The tree that were obscured were also all rendered.
test project:
[test.zip](https://github.com/castle-engine/castle-engine/files/10295310/test.zip)

**Comment by michaliskambi** [comment]
Ah, this is a consequence of our treatment of blending when various scenes contain partially transparent objects.

The (imperfect) solution for today:

Folow the https://castle-engine.io/blending manual, section _"However, the engine does not sort the list of TCastleScene instances by default"_ (I have just extended this section to mention 3D). That is, call

```
Viewport.Items.SortBackToFront(bs3D, Viewport.Camera.WorldTranslation)
```

Do it often, I would say to do it just from `TStateXxx.Update` method in the usual case.

I have added to CGE editor now the menu option "Viewport -> Sort Items For Correct 3D Blending (from current view)". You can use it after moving+rotating the camera, it will fix the issue.. but you will have to repeat this after moving+rotating the camera again. That's why in game, I would advise to just call `Viewport.Items.SortBackToFront...` every frame.

In the long run: The need to do this "manual sorting" should completely disappear. I added a section about it to our roadmap, https://castle-engine.io/roadmap#_related_to_above_possibility_to_reordermerge_all_shapes_across_all_scenes . 

I'm changing the issue title -- to reflect that the issue has an imperfect solution, but we want to make it better :)

**Comment by Freedomax** [comment]
But sometimes the 'SortBackToFront' sorting is also incorrect. I have made a demonstration where I only zoomed in on the camera's perspective.
![GIF 2022-12-27 19-43-01](https://user-images.githubusercontent.com/26040454/209664861-d3d54bad-1ccc-4f70-b0ed-8ee49449d4e4.gif)
test project:
[test1.zip](https://github.com/castle-engine/castle-engine/files/10308063/test1.zip)

**Comment by michaliskambi** [comment]
In short:

- get the latest CGE (improvements described below are already pushed to master branch, or wait ~6 hours until Jenkins builds them and they will be part of downloads on https://castle-engine.io/download )

- and set on `Viewport.Items` property `BlendingSort` to `bs3DGround`.

No need to call any `Viewport.Items.SortBackToFront` at run-time anymore, no need to repeat at design-time "Sort Items for Correct 3D Blending" :)

Details, what I did and why:

1. The default sorting algorithm (`bs3D`) failed for you, because it compares bounding boxes. And the billboarded tree gets a larger bounding box (because bounding box is enlarged by TCastleBillboard rotation), so it was considered "in front of player" even though you wanted it to be behind the player.

    While no algorithm for this sorting will be universally perfect, but we can make a good algorithm for this case.

    I experimented and added alternative sorting:

    - `bs3DOrigin` - Compare distance to object's origin (point (0,0,0)), ignoring bounding boxes.

        Unfortunately, this also failed in your case, but for completely different reason. Namely, player sprite vertical position (Y of the origin) is lower than tree.

    - `bs3DGround` - takes object's origin (point (0,0,0)) projected on the Y=0 ground, compares it. This is perfect for your case.

    - TODO: At some point, I will likely also rename bs3D to bs3DBox (to be unambiguous), though I'll have to check how to do an enum name change without breaking compatibility (the enum names are used to read/write values in design JSON files, so we cannot change them carelessly).

    P.S. Note that you can also invent your own sorting methods using a callback -- just do `Viewport.Items.List.Sort(...)`. It's a generic list (descends from list from `Generics.Collections`, see https://castle-engine.io/modern_pascal#generic-containers-section for examples). However, the advantage of having a "predefined" sorting done by `Items.BlendingSort` is that it allows to test it easily in CGE editor.

2. I thought about exposing it better. Initially I made more new menu items in editor:

    - _"Sort Items For Correct 3D Blending (from current view, using bounding box)"_
    - _"Sort Items For Correct 3D Blending (from current view, using origin point)"_
    - _"Sort Items For Correct 3D Blending (from current view, using origin point on ground)"_

    ... but eventually I decided that it's time to remove such hacks. And just give you an option that does the sorting, both at run-time and design-time, automatically.

    This is now exposed as `Viewport.Items.BlendingSort`.

    It also means that the sorting it does *does not* change the order of children in the hierarchy tree. You can safely e.g. rely on the fact that 1st child of `Viewport.Items` is Xxxx, regardless of the current camera (so, regardless of current sorting result).

    And also I have now removed _"Sort Items For Correct 3D Blending"_ menu options, including the option I exposed in my last  comment here. Changing `Viewport.Items.BlendingSort` is just universally better :) I only left the option to sort for 2D, because in case of 2D, sorting at design-time is in many cases all that is necessary.

**Comment by michaliskambi** [comment]
https://user-images.githubusercontent.com/1076978/209730299-84e8443a-6bfb-45e3-a6ab-ec311b99029e.mp4

Here's me playing with `Items.BlendingSort` on your testcase in latest CGE editor :)

**Comment by michaliskambi** [comment]
Finally, I improved docs on https://castle-engine.io/blending to reflect the latest state, and I added a screenshot based on your demo (because that page really needed some graphics, it was too much a "wall of text"). I hope you're OK with this :)

I'm very happy, this important missing piece of CGE just got better.

It's not the end, the "real" approach to automatic blending sorting (by sorting all shapes) is still a TODO on https://castle-engine.io/roadmap#_related_to_above_possibility_to_reordermerge_all_shapes_across_all_scenes . But I feel that current `Viewport.Items.BlendingSort` is an important step, it is nicely 100% automatic and easy to use from editor and code. It should be enough for your case.

**Comment by Freedomax** [comment]
Thank you! I have tested the latest version and everything is perfect.

**Comment by michaliskambi** [comment]
Note: Recent CGE upgrade in https://castle-engine.io/wp/2023/06/30/big-renderer-improvements-correct-and-automatic-blending-sorting-more-powerful-batching-now-cross-scene-easier-and-more-reliable-occlusion-culling-and-occlusion-sorting/ changes the resolution of this a bit.

Set now `Viewport.BlendingSort := sort3DGround`. This is somewhat equivalent (but better in some ways) to previous `Viewport.Items.BlendingSort := bs3DGround`.

There is also a `sortCustom` approach, that allows to specify a callback to compare shapes. I've added this exactly thinking about this ticket -- basically we cannot account for all possibilities with more and more `sortXxx` enums, so for non-trivial cases we allow you to specify sorting explicitly.
