### ISSUE TITLE
Tolerate ambiguous header when loading binary STL files

### ISSUE THREAD

**Issue by curtmcd** [castle-engine/castle-engine#433]
STL is not very well defined. Applications including SolidWorks write the binary format with the word "solid" in the header, whereas only ASCII files should start with "solid". Unfortunately, since x3dloadinternalstl.pas only checks for "solid", it fails to load such binary files. This means view3dscene does not work with 3.2% of the publicly available STL files from Thingiverse or elsewhere. Almost all 3D tools are tolerant of this problem, and view3dscene should be too.

One way to differentiate reliably is to check if the first 256 bytes of the file contain all of the substrings: "solid", "facet", "normal", "outer", "loop", "vertex". If so, it's ASCII, and if not, it's binary. I realize that x3dloadinternalstl.pas needs to load a stream, making lookahead an issue, but there must be a reasonably elegant way to do it.

**Comment by michaliskambi** [comment]
Thanks for reporting! 

Agreed, I mean we want to handle STL files "in the wild", so if this will require changing our simple check `if Header = 'solid' then` in `x3dloadinternalstl.pas` to something more involved, so be it :)

Lookahead is doable -- while `LoadSTL` takes a stream, it can require that this stream allows seeking forward and backward freely. Some other loaders already require this, in particular glTF and MD3, and we have code underneath to make sure we get such stream -- if the stream class would not allow seeking, we just load it to TMemoryStream and only starts processing once it's all available, this is e.g. what happens if you download the stream from http. See https://github.com/castle-engine/castle-engine/blob/master/src/scene/load/x3dload.pas#L315 .

Can you point me to exact STL files to reproduce the problem and test e.g. on https://www.thingiverse.com/ ?

**Comment by michaliskambi** [comment]
@curtmcd Pinging about this -- I would very much like to fix it, but for this I'd appreciate examples of invalid STL files, i.e. ones we cannot handle in view3dscene / Castle Game Engine. 

Since the solution will likely employ some heuristics, I will want to test it on real-life examples :)

I was recently looking at STL reader in Blender : https://github.com/blender/blender-addons/blob/main/io_mesh_stl/stl_utils.py#L60 , `_is_ascii_file`. Instead of looking for `solid` to detect ASCII, they look whether the file can be considered binary by checking the file size with a particular data that is recorded in the file (in case it is binary). This is also a heuristic, but seems a bit more reliable than proposed initially scanning "first 256 bytes" (because then the number "256" is arbitrary).

So I'm leaning toward implementing Blender solution. But, again, it would be best to test it on some models that fail our current `if Header = 'solid' then` test.

**Comment by curtmcd** [comment]
@michaliskambi Sorry it has taken so long before I noticed your request! I'll be happy to provide a few examples below.

The Blender heuristic you mentioned that relies on file length does work on all examples I've found. To be exact, the condition to detect a valid binary STL file is:
    stl_file_size_in_bytes == (BYTE[80] | BYTE[81]<<8 | BYTE[82] << 16 | BYTE[83] << 24)
where BYTE[n] is the nth byte of the file counting from 0.

- https://www.thingiverse.com/thing:763622 3DBenchy.stl
- https://www.thingiverse.com/thing:4139419 mantis_Fender.stl
- https://www.thingiverse.com/thing:1155687 Chirping Bird, all .STL files
- https://www.thingiverse.com/thing:27233 Nautilus_Gear.STL
- https://www.thingiverse.com/thing:2726918 T-REX_Base.STL
- Creality Ender-3 included example file 4.Model/vase.STL
- https://thangs.com/mythangs/file/51868 CHEP_bed_level_print.stl
- Cura git repo: resources/meshes/longer*.stl
- GAL git repo: Stream_support/test/Stream_support/data/binary-tetrahedron-non-standard-header-*.stl
- OpenSCAD git repo: openscad/tests/data/scad/3D/features/import_bin_solid.stl
- OpenSCAD git repo: openscad/tests/data/stl/unparseable.stl (this one is intentionally bad)

**Comment by michaliskambi** [comment]
Sorry for delay and thank you for testcases -- fixed, I tested the new view3dscene on 

https://www.thingiverse.com/thing:763622
https://www.thingiverse.com/thing:4139419
https://www.thingiverse.com/thing:1155687
https://www.thingiverse.com/thing:27233
https://www.thingiverse.com/thing:2726918
https://thangs.com/designer/CHEP/3d-model/CHEP%20Manual%20Bed%20Level%20for%20Ender%203%20Size%20Printers-51868
https://github.com/openscad/openscad/blob/master/tests/data/scad/3D/features/import_bin_solid.stl

Please give Jenkins a few hours from this post, and then Castle Game Engine and view3dscene "snapshot" downloads will contain the fix :)
