### ISSUE TITLE
Allow to access to loader instance after calling TCastleSceneCore.Load()

### ISSUE THREAD

**Issue by Kagamma** [castle-engine/castle-engine#44]
Now that we officially have tsr8's tiledmap loader in the engine code, I am planning on writing a tiledmap loader for X3D in the same way as how the engine handles non-X3D formats like 3DS or Spine. The problem is I also want to retain TTiledMap instance so that I can get informations that can't be translated directly to X3D nodes like the Object layer. So I am thinking of modifying TCastleSceneCore and add 2 new properties: 
- RetainLoaderInstance: A boolean field that tells the engine to keep loader instance after loading process is done, default is false.
- LoaderInstance: A TObject field that holds loader instance.

Of course we also need to modify all existing x3dloadinternal*.pas code to follow this changes.

What do you think Michalis?

**Comment by michaliskambi** [comment]
Hm, I'm unsure about adding such fields to the TCastleSceneCore, when it's only for TMX format. If in the future it will make sense for other formats, then I'm going to change my mind and do exactly like you propose:)

But for now, I would prefer a different way. Make the future tiledmap -> X3D loader as two overloads:

~~~~
function LoadTiledMap(const URL: string): TX3DRootNode;
function LoadTiledMap(const URL: string; out Map: TTiledMap): TX3DRootNode;
~~~~

If you want to keep the internal map instance, then instead of using

~~~~
Scene.Load('map.tmx');
~~~~

you would use:

~~~~
Scene.Load(LoadTiledMap('map.tmx', Map), true);
~~~~

and you get a <code>Map: TTiledMap;</code> instance, to use as you like:)

Oh, and a minor consequence of this: the unit to load TiledMaps should then not have "Internal" in it's name:) So, it should be named like <code>X3DLoadTiledMap</code> instead of <code>X3DLoadInternalTiledMap</code>. Since a user may have a good need to use <code>X3DLoadTiledMap</code>, to be able to call <code>LoadTiledMap</code> directly.

BTW, one can usually push a lot of information into the X3D graph, by adding them to the "metadata" field of X3D nodes. But in this case, this would be unnecessarily convoluted, it's much easier to just get TTiledMap instance indeed.
