### ISSUE TITLE
Tiledmap draws a 1-pixel black line

### ISSUE THREAD

**Issue by Freedomax** [castle-engine/castle-engine#447]
![extraline](https://user-images.githubusercontent.com/26040454/218477602-e5ff6e95-6217-4492-8963-ec02230bc1b0.png)

After a proper zoom, the black line may not appear. But if you move the camera, the black line will still appear at some point.
If I enable `SmoothScalingSafeBorder`, then the problem doesn't exist, but the image is artifacted (very important for pixel-art games), looks narrowed in the Y direction, missing a pixel.

**Comment by michaliskambi** [comment]
Hm, there are 2 possible causes for dark seams. 

I'm not sure what exactly test do you do, as you show image with `SmoothScaling` = `false` but mention `SmoothScalingSafeBorder` (which shouldn't be used, and shouldn't help for anything, if `SmoothScaling` = `false`).

Causes for dark seams:

1. If the texture doesn't have alpha bleeding ( https://castle-engine.io/manual_alpha_bleeding.php ) and you use `SmoothScaling` = `true`. In this case `SmoothScalingSafeBorder` = `true` is a workaround, but it is a workaround, it will indeed worsen the look (stretching texture a tiny bit).

    The only good solution for this (that doesn't involve tricks in shaders that would cost rendering time) is using a texture with alpha bleeding, i.e. you should add padding between tiles, and this padding should be filled with neighboring colors. This is a consequence of how GPU is sampling the texture (in case `SmoothScaling` = `true`).

    The alpha bleeding issue doesn't exist when using `SmoothScaling` = `false` (i.e pixel-art look).

2. If the numbers we generate for coordinates of tiles are not precisely matching, i.e. one tile ends at "Y", the other starts at "Y + epsilon" due to differences in floating point calculations, i.e. 2 ways to calculate the same number in floats may sometimes *seem* equivalent but actually they are not (will generate numbers that differ by some epsilon), unless they perform exactly the same operations, in the same order, with the same inputs. GPU rasterization doesn't guarantee that no seams occur, unless you provide really exactly the same numbers for neighbors.

    I'm aware we have this problem on master, I saw such seams. In the proper rendering, regardless of zoom, no such seams should be visible.

    For this kind of seams, the right solution is make sure we use proper numbers at CGE level. We cannot transform shapes (X3D shapes nodes) with different numbers, even by epsilon, if tiles between these shapes should match. Our geometry should use precisely the same coordinates, for neighboring tiles.

So, AD 2 is a known problem. That said, `SmoothScalingSafeBorder` shouldn't help here :) Can you share exactly the test you do? E.g. if this is just a modification of examples/tiled/map_viewer_in_viewport, can you post the modified `data/gameviewmain.castle-user-interface` from it?

**Comment by Freedomax** [comment]
![GIF 2023-02-13 22-30-40](https://user-images.githubusercontent.com/26040454/218486178-0ba86bcf-64b3-4619-b1da-bf68d6ca73e4.gif)

There is no modification , just run "map_viewer_in_viewport", open "desert.tmx" by default, and then a black line will appear when the mouse wheel zooms in. And I tested only when the width (or height) of the map on the screen is an odd number,Black lines may appear.

**Comment by Freedomax** [comment]
I tested again, my previous reply was incorrect, black lines will also appear if the width is even.

**Comment by michaliskambi** [comment]
I can reproduce it too, at certain zooms, confirmed.

Hm, and (most curious!) using `SmoothScalingSafeBorder` indeed makes the seams disappear. Which means that my suspicion for the fault ("If the numbers we generate for coordinates of tiles are not precisely matching...." in my earlier post) has to be incorrect. `SmoothScalingSafeBorder` indeed *does* help to avoid these seams (when even `SmoothScaling` = false), but it only changes texture coordinates.

So I did reach incorrect conclusion above. The problem is with `SmoothScaling` = `false`, and the problem comes from texture coordinates (not just positions), as `SmoothScalingSafeBorder` only changes texture coordinates. Neither my AD 1 nor AD 2 explains this, this is some other problem. I'll investigate, thanks :)

**Comment by Freedomax** [comment]
d71b7ec4e18c67587cf66066f4060dd2224a7553
Seems to have solved the problem easily.
