### ISSUE TITLE
[QUESTION] What do you think about being a mentor for a new engine?

### ISSUE THREAD

**Issue by ArtemkaKun** [castle-engine/castle-engine#449]
Hi Michalis,

I saw your [talk on GIC](https://youtu.be/Ad3UywYyRGU) and I think it was great. Always happy to see an enthusiastic senior developer who is dedicated to open source and creates things they like.

I never heard about Castle Engine, but I think it's very cool. It just has many of the things I'm dreaming of (one language for engine and scripts, Linux support, FOSS, glTF, strong idea/core, fast compilation, CD/CI, and it doesn't try to be as Unity).

I'm into game development too and want to create a game engine one day too. I'm also a member of the [V programming language](https://vlang.io/) community. Not sure if you heard about it, but a short description of this language would be "C but better". I do think this is a great language that has huge potential in game development.

There are a lot of enthusiastic game developers who already did a great job with porting/creating wrappers for well-known C libs like SDL, Sokol, and Raylib. There are also some homemade games and even proof-of-concept Vulkan game framework. There are a few strong members who implement their things in their spare time and would like to do even more.

Our problem right now is that we have no guru, who designed and implemented the whole game engine. I think about a person who will direct our development team in the right direction with a game engine and also a person who is interested in new game dev things and technologies.

I think that you are the right person for this place. What do you think about being a mentor for a new game engine created in V?
I can tell you more about the language, about game dev related libs and stuff we already have, and introduce you to a language creator and development team. We can have a chat or a video call if you want.

I duplicated this message to your email *michalis@castle-engine.io* and *michalis.kambi@gmail.com*

P.S. In the GIC talk video I saw you have a Polish language set up on your computer, so I assume you a fluent in Polish. I speak Polish too. So if you have a hard time understanding my English - we can switch to Polish anytime.

**Comment by michaliskambi** [comment]
Hi,

Thank you for great words about the engine! I'm happy you like what you see in Castle Game Engine and happy that my "message" from GIC came across -- I indeed wanted to emphasize the features you mentioned at "I'm dreaming of...".

And I'm really humbled by your high opinion of me :)

I looked at

- https://vlang.io/

- of course also at https://github.com/vlang/doom :)

- https://github.com/vlang/v/blob/master/doc/docs.md

- https://github.com/vlang/awesome-v , in particular game and game development tools mentioned there, I see https://github.com/LouisSchmieder/Varekat

- https://github.com/vlang/v/wiki/FAQ , https://vlang.io/compare , https://github.com/vlang/v/blob/master/README.md#stability-guarantee-and-future-changes

The feature set of what you do is great.

That being said, I am not the right person for mentor of a game engine in V. To be clear, I would love to throw myself into a big project where I could use my game-engine knowledge, and start building a new thing from a simpler cleaner slate (oh, how many things I did in an unoptimal way when developing CGE, because I was learning, and I know I could reach optimal solution so much faster now, and focus on right features...). But making a game engine is a big project, and at this point Castle Game Engine is consuming all my resources -- and it will likely continue to do so for a long time, as we just reach a point when a lot of the design and UX plays nicely together into a polished product. So making CGE is a long journey, and I cannot do 2 such journeys (CGE and another game engine) at the same time.

So, thank you a lot for the offer, and for positive words, but that is not something for me (now).

That being said,

- I will watch what you're doing :) I subscribed to various things at the bottom of https://blog.vlang.io/ :)

- I lately try to find time regularly for gamejams or other activities where I can learn something in a time-constrained box (so that I *do not* adopt another project :) ). If you'll organize anything like a gamejam / hackaton around V (or specifically around V + games / game engine), I'll be sure to join and learn.

Thanks again!

P.S. As for communication, all options are fine with me -- GitHub or any of the mails you used :) And both Polish and English are fine. I'm answering here publicly in English, so that anyone observing will know what's going on :)
