### ISSUE TITLE
Editor CPU usage is too high.

### ISSUE THREAD

**Issue by Freedomax** [castle-engine/castle-engine#453]
The CPU usage is only about 1% when running the game, but the CPU usage of the editor is always about 9%. What is the cause?

**Comment by michaliskambi** [comment]
Well, I would say 9% CPU usage for a game engine is really not much :)

That said, it is of course useful to explain the difference. On what operating system do you observe it, on what project, how do you measure it?

I just tested on Linux/x86_64, running "2D game" template (that shows a few animations), in CGE editor and in parallel running the executable (compiled with FPC in release mode). So they both show and animate the same thing. The CPU usage is similar, game is ~12-13 CPU while CGE editor is 13-15 CPU (they both change ~randomly over time). So I have rather small CPU usage difference, that seems ignorable (in the end, editor and game do a bit different things, and have different GUI around CGE rendering).

Note that game compiled in debug mode eats much more CPU (21%), this is expected. "Debug mode" activates various run-time checks (like for "range errors" in Pascal) that can indeed consume some time.

![Zrzut ekranu z 2023-02-23 00-56-32](https://user-images.githubusercontent.com/1076978/220791203-68121d41-e222-483f-bb1c-48b1eb71f5c9.png)

**Comment by Freedomax** [comment]
![GIF 2023-02-23 10-34-06](https://user-images.githubusercontent.com/26040454/220809556-33c69568-8358-4631-8774-63edc8822b67.gif)

Windows platform 64-bit, win11, laptop external monitor.
This is an empty project, open the default main view.
The editor cpu occupies about 8%, while the game cpu occupies only 0.5%.

8% is equivalent to a CPU core is basically fully occupied. If I run an infinite loop program, the CPU usage is also 9%.

**Comment by Freedomax** [comment]
Further confirmation is because `TCastleControl` has set `FAutoRedisplay := True`.

**Comment by michaliskambi** [comment]
Both `TCastleControl` and `TCastleWindow` have `AutoRedisplay = true`, they redisplay each frame. This is normal. AutoRedisplay means to redraw even if we didn't have any notification that "something visible changed" from any component (it's what we use, because optimizing for cases when "the displayed image is perfectly static" isn't very useful, so it's easier to not rely on "redisplay" notifications). 

That said, they both also have mechanism to not eat CPU needlessly (ApplicationProperties.LimitFps).

Testing on my system, the CPU usage on "Empty" template is almost none, from both game and CGE editor.

I'll test soon on Windows, maybe our usage of LCL ApplicationIdle is unoptimal. We wanted to change it anyway.

![Uploading Zrzut ekranu z 2023-02-23 04-31-29.png…]()

**Comment by michaliskambi** [comment]
1. I attempted to use a timer to manage CGE updates in case of TCastleControl.

    Unfortunately this failed. While it worked nicely on Windows, but then on Linux it seems hopeless. The timer implementation in LCL GTK widgetset doesn't interrupt `WidgetSet.AppWaitMessage`, it seems, and so application with timer with interval = 1... can actually hang for arbitrary long time, if you don't move the mouse or make any other input. So e.g. animation of TCastleScene in TCastleControl doesn't work then in CGE editor.

    So I reverted back to original approach. The timer attempt can be restored by defining `CASTLE_CONTROL_UPDATE_TIMER` at the top of `castlecontrol.pas`, for now it is undefined. While it is possible to enable `CASTLE_CONTROL_UPDATE_TIMER` only on Windows, I would consider it a "last resort" solution -- this will lead to more work at testing, if TCastleControl will behave more differently between Linux and Windows.

2. Can you test with and without `CASTLE_CONTROL_UPDATE_TIMER` on your system?

    - I suppose that without `CASTLE_CONTROL_UPDATE_TIMER` defined, it is as it was, so too large CPU usage.

    - I'm curious what do you experience with `CASTLE_CONTROL_UPDATE_TIMER` defined.

    While my attempt was different than your https://github.com/castle-engine/castle-engine/pull/456 , I hope to make it work -- the idea is that `DoLimitFps` should already make the correct job of saving CPU usage.

3. Note that I cannot reproduce this CPU usage on my Windows system, even before my work.

    Testing with game from "Empty" template, on Windows 10:

    - I see 1-3% CPU usage from CGE editor
    - and < 1% CPU from the actual game running

    With "2D game" it's a bit higher but still not like "one core is used fully".

    To be sure how much is "application eating all CPU cycles on some core" for me, I did test a simple "just loop" application that eats CPU in a loop, it eats 13-15% on my system. Windows confirms is detects 6 cores.

    I'm guessing this may be affected by what GPU do you have, how are OpenGL commands performed.

    On Linux OTOH, I can reproduce having 1 core exhausted if I run "2D game" template in CGE editor. Debugging, it seems the `LimitFps` mechanism works (CGE editor sleeps), so apparently OpenGL does some work on CPU eating it.

![cpu1](https://user-images.githubusercontent.com/1076978/221102500-1935efda-ba69-4a35-b610-36b1d19cb573.png)
![cpu2](https://user-images.githubusercontent.com/1076978/221102493-e67af62f-2afd-4131-978e-4fa0ddcd2ca9.png)
![cpu3](https://user-images.githubusercontent.com/1076978/221102486-fbeb28ae-2619-4ee8-8a54-32c04419c184.png)

**Comment by Freedomax** [comment]
you said "Note that I cannot reproduce this CPU usage on my Windows system, even before my work."
I forgot to state the key issue. The external monitor is the root cause. If I unplug the external monitor and use the laptop's own monitor the situation is as follows:
![no-monitor](https://user-images.githubusercontent.com/26040454/221108998-504c92ea-a125-4f84-be68-c6f5f47bcb88.gif)

If I use an external monitor, the cpu usage goes back to 8%.
I haven't tested the "with CASTLE_CONTROL_UPDATE_TIMER defined" case.

**Comment by Freedomax** [comment]
Internal display:
![1](https://user-images.githubusercontent.com/26040454/221111159-b7ef56ad-eab5-446c-967c-b1167ee2745a.png)

External display:
![2](https://user-images.githubusercontent.com/26040454/221111180-3caa4adf-03d6-4225-b1e1-d27a92052b14.png)

The refresh rate and bit depth of the two monitors, as well as the graphics card used are different

**Comment by Freedomax** [comment]
Thanks for testing this issue and updating the engine code.

I just tested the situation after defining `CASTLE_CONTROL_UPDATE_TIMER`. There is no improvement, and the CPU usage is still more than 8%. If I modify it to "`UpdatingTimer.Interval := 1000 div 60;`", then the CPU usage will be close to 0%.

So the crux of the problem is that `TWinControl.invalidate` cannot be called too many times per second, it consumes a lot of CPU time in some cases.
With CEG supporting multiple operating systems, this problem can get tricky and may indeed require different workarounds for different operating systems.
I don't think it's necessary for an editor to maintain a specified FPS. It might be nice to separate rendering and updating.

**Comment by michaliskambi** [comment]
Thank you for testing!

> It might be nice to separate rendering and updating.

To this sentence in particular:

- Indeed, we don't need to have rendering and updating synchronized. The CGE deliberately doesn't guarantee any strict order or synchronization for `Render` and `Update`, to allow us to make best and efficient choices for e.g. each platform.

- That said, in this particular case, the ideal would be to not only "stop doing too many Invalidate calls per second" but also "stop doing too many DoUpdate calls per second". Just like there's no point in doing Invalidate 6000x per second, there's also no point in updating e.g. animation 6000x per second.

> The refresh rate and bit depth of the two monitors, as well as the graphics card used are different

Thanks for the detailed information.

I see you have a peculiar case with the external monitor. 

Looks like I will not be able to reproduce it on my side, so I'll need more tests from you :) On my testing laptop, both internal and external monitors use the same GPU (Nvidia). My laptop has also an Intel GPU, but that is never used (because `castle-editor.lpr` includes `request_dedicated_gpu.inc` to always request the "more efficient" card when laptop uses NVidia Optimus / AMD PowerXPress technology). And in my tests, both internal and external monitor exhibit the same (low) CPU usage.

Can you test with `CASTLE_CONTROL_UPDATE_TIMER` defined and `UpdatingTimer.Interval := 1000 div ApplicationProperties.LimitFps` (ApplicationProperties.LimitFps are 100 by default)?

If it will work (i.e. make low CPU usage), can you do tests what happens with our `DoLimitFPS`? It has a code

```pascal
      if TimeRemainingFloat > 0.001 then
      begin
        Sleep(Round(1000 * TimeRemainingFloat));
        LastLimitFPSTime := Timer;
      end else
        LastLimitFPSTime := NowTime;
```

Can you measure how often (if at all) it enters the `Sleep(Round(1000 * TimeRemainingFloat));` condition? By adding some`Writeln('sleeping');` or maybe counting like `Inc(SleepCount)` while `Now` indicates we have the same second.

It should have "room to sleep" (since you have low CPU when `UpdatingTimer.Interval := 1000 div 60`). So I'm curious why it seems like it doesn't sleep.

My main concern here is that you wrote

> The ApplicationIdle method will be called thousands of times per second (about 6000 times on my computer), exhausting the CPU.

in https://github.com/castle-engine/castle-engine/pull/456 . This is most strange. Indeed it explains big CPU usage... but I don't yet understand why our `DoLimitFps` mechanism didn't prevent it. It was exactly implemented to avoid calling the update huge number of times (like 6000) per second, and wasting CPU (and laptop battery).

**Comment by Freedomax** [comment]
> Can you measure how often (if at all) it enters the Sleep(Round(1000 * TimeRemainingFloat)); condition? By adding someWriteln('sleeping'); or maybe counting like Inc(SleepCount) while Now indicates we have the same second.

I tested that `sleep` is called several times only when View is opening and closing, and `sleep` is not called once **during the running**. That is to say, on my computer, the function `DoLimitFPS` is completely useless.

**Comment by Freedomax** [comment]
I tested `UpdatingTimer.Interval := 1000 div Round(ApplicationProperties.LimitFps);`
The result is completely different from `UpdatingTimer.Interval := 1000 div 60;`. The CPU usage exceeds 8%.
Then I modify the value of 1000 div **xx**, and magic happens.
1000 div **62** has achieved a qualitative leap compared to 1000 div **63**. The cpu usage has gone from 8% to 0%.

**Comment by Freedomax** [comment]
I just used my PR #456 to test again.

If  set `FPaintTimer.Interval := 1; `CPU usage is only about 1%.
So here comes the problem, %8=>1% is just because the location of the `invalidate` call is different. I think I have found the root of the problem.

The code in lazarus is like this:
```
while not terminated do
begin
HandleMessages;
HandleIdle;
end;
```

If `invalidate` is called in `HandleIdle`, a `WM_PAINT` will be sent to the message queue, and then `HandleMessages` must handle `WM_PAINT`, so that the CPU will never be idle. If `invalidate` is called through `TCustomTimer`, it will not completely occupy the CPU (the message queue spends most of the time Is empty);

**Comment by Freedomax** [comment]
> Then I modify the value of 1000 div xx, and magic happens.
1000 div 62 has achieved a qualitative leap compared to 1000 div 63. The cpu usage has gone from 8% to 0%.

Regarding this magical value, I also found the reason.

Let **a**=1/fps, **b** is the time of `invalidate` once.
If **b**<**a**-0.001, the `sleep` in `DoLimitFPS` will be called all the time, so that the CPU usage is close to 0%.
If **b**>**a**-0.001, `sleep` will never be called and the CPU will be full.

The critical point is when fps = 1/(**b**+0.001), magic happens.

**Comment by Freedomax** [comment]
I just found out that with `DoLimitFPS` removed, the magical difference between **1000 div 62** and **1000 div 63** is still there. **So my speculation above is all wrong**.

I give up on this issue for now, I'll make a simple patch to the editor, use `1000 div 60`.
