### ISSUE TITLE
Fail to install TCastleControl  in Delphi 11

### ISSUE THREAD

**Issue by Ever-Bright-V** [castle-engine/castle-engine#472]
AllPackages.groupproj 
1. Build All  --> some warnings,no errors
2. Install -> Failed, Errors like this
![image](https://user-images.githubusercontent.com/57551787/230699863-7144046f-166a-40c2-b4a9-214dea3d61d2.png)

**Comment by michaliskambi** [comment]
I cannot reproduce the failure -- installation of `castle_fmx.bpl` (or any other CGE package) goes OK for me. 

The error from Delphi  you show says that `Register` call from CGE unit failed, causing access violation in Delphi RTL. I don't see how is this possible, on a valid Delphi installation.

( Note: a warning about `CastleProgress deprecated` is normal during package compilation. It will disappear at some point when we remove that deprecated unit. )

Please:

1. Provide more information about your version of Delphi. It's best if you can provide screenshot of your "Help -> About Embarcadero Delphi" window, this shows exact Delphi version, Windows version and some related components. I attach screenshot showing the version of Delphi 11 I used for testing now.

2. Do you have some Delphi additional plugins / components that could interfere with registration process of other components? Try disabling them if yes.

3. Try reinstalling Delphi. Maybe some Delphi installed files (RTL) got corrupted? I know it's a long shot, but I don't have any better clue now.

![d11](https://user-images.githubusercontent.com/1076978/230732830-c9479159-5936-4e41-99e2-db90cc6b9fb3.png)
![d11_2](https://user-images.githubusercontent.com/1076978/230732832-ceddedc8-4117-495f-b999-4194a7c1d8c2.png)

**Comment by Ever-Bright-V** [comment]
Sorry for replying too late. I try again and **success**. In my opinion, at that time, the available memory was too small (many programs were opened) or the available disk space was narrow. I clean up my pc and it goes well.
But Another Problem:
Run the example——**CastleVcl** , **delphi can‘t find X3DLoadInternalMD3.pas**.  I add the .pas to  Browser Path and Library Path, and it work well.
**Do i need to add the src dir of CGE to the Browser Path Firstly like some 3rd compnents?**

**Comment by michaliskambi** [comment]
> But Another Problem:
> Run the example——CastleVcl , delphi can‘t find X3DLoadInternalMD3.pas. I add the .pas to Browser Path and Library Path, and it work well.

Thank you, fixed!

We recently moved one unit into a subdirectory, and it was missing from the example DPROJ configuration. In new engine versions, the example should compile and run out-of-the-box. 

The fix is committed to the GitHub master branch, in a few hours (after it passes various automatic tests) it will be available to download on https://castle-engine.io/download too.

> Do i need to add the src dir of CGE to the Browser Path Firstly like some 3rd compnents?

For projects that are managed by CGE editor, i.e. have a corresponding `CastleEngineManifest.xml` file (like all examples in CGE repo) -> you don't need to worry about paths yourself. 

The DPROJ of these projects should automatically contain all the necessary engine paths. And in case we make a change in the engine, you can adjust your own project using CGE editor _"Code -> Regenerate Project (overwrites LPI, DPROJ...)"_.

That said, we don't force you to manage your projects this way. If you want to just manage project configuration yourself in Delphi, and you don't want to use CGE editor _"Code -> Regenerate Project (overwrites LPI, DPROJ...)"_, and you don't want to specify a lot of paths in each DPROJ... then yes, you can add all relevant CGE paths (all src/ subdirectories) to Delphi Units path.

**Comment by Ever-Bright-V** [comment]
Thank you!
