### ISSUE TITLE
Occasional Delphi Range Error when loading model

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#474]
This one had me stumped as I thought the error was something I'd done (so I was looking in the wrong place)

There exists some kind of edge case that affects Delphi but not Lazarus when loading gltf/glb that causes a range error (I guess it could also be affecting Laz but just not reporting it but this is less certain)

The issue occurs only with some larger models I've tried and it was happening on a licensed model

Fortunately I've found one of the Jose Diaz models that does the same (took some hunting) - I'll go ask Jose Diaz for permission to let you have a copy for debugging as he was fine with this last time.

**Comment by peardox** [comment]
Having just got Win64 to work I tested this bug again and it went away so the issue is length of Int (I guess) based as sanity checking the results proves that the model still fails under Win32

It is notable that the test model now in your possession is 17Mb (anything slightly over 16 hits the old alarm bells) but this is not relevant as another model (not available) also g#fails and that is 6Mb (and I've got other models of that size that work in Win32)

**Comment by michaliskambi** [comment]
Thank you very much for reporting, fixed! Tested on your test model passed to me in private, with Delphi 11, with platforms both Windows-32 and Windows-64.

> the issue is length of Int (I guess) based as sanity checking the results proves that the model still fails under Win32

Note that I could reproduce the Range Check Error in Windows-64 as well. I simply edited the URL of model in https://github.com/castle-engine/castle-engine/blob/master/examples/viewport_and_scenes/view_3d_model_basic/view_3d_model_basic.dpr , run it in Delphi 11, and debugger stopped at the proper line.

The issue was unrelated to `PtrInt` / `PtrUInt` changing size between 32-bit and 64-bit platforms. 

The cause:

Our `TStructList.List` is essentially not good in Delphi, when used with potentially really long lists, because Delphi doesn't support `SizeOf(T)` is generics. Our `TTypeList` may have too small size because of necessary "ifdef" for Delphi, https://github.com/castle-engine/castle-engine/blob/master/src/base/castleutils_struct_list.inc#L35 .

There's luckily another solution, and it is cleaner and also supported by FPC (activating Delphi "pointermath" and using `TStructList.L`, no need for "fake infinite arrays"; FPC supported it since ~always) so I happily migrate to it. I fixed the 2 affected places in https://github.com/castle-engine/castle-engine/commit/4fb67a3fa0f0e2032ac97366f206dbd7e478794b , and then I went ahead and updated *a lot* of other CGE code to avoid range check errors due to similar issues on Delphi in https://github.com/castle-engine/castle-engine/commit/e6d028fe22807b1230a70ff8ac8862373531f90a .

**Comment by eugeneloza** [comment]
An almost unrelated note: @michaliskambi I wonder if making `.L` into something longer might be a better idea? I mean `.L` is not greppable :D And I've just had a look at my game projects if I use `.List` or `.L` from the `TStructList` and for obvious reasons searching for `.L` returns way too many unrelated results. Obviously it's nothing important, just a note.

**Comment by michaliskambi** [comment]
@eugeneloza 
>  I wonder if making .L into something longer might be a better idea? I mean .L is not greppable :D And I've just had a look at my game projects if I use .List or .L from the TStructList and for obvious reasons searching for .L returns way too many unrelated results. Obviously it's nothing important, just a note.

Hm, while usually I prefer longer and descriptive, in this case I admit I like short `L` because it is usually something you don't want to think about -- you really want to access `MyList[I].MyField` but for "technical reasons", when dealing with records, you should write `MyList.L[I].MyField` (because it is more efficient and because it allows writing).

Note that most usage is greppable in practice using `.L[` :)

And I just deprecated `TStuctList.List` -- if it's clearly a trap for Delphi users, and `L` is just better for both FPC and Delphi users. So the compiler will warn about `List` usage.

**Comment by eugeneloza** [comment]
Makes sense, thank you!
