### ISSUE TITLE
cannot install (Delphi 10.2.3)

### ISSUE THREAD

**Issue by limelect** [castle-engine/castle-engine#478]
D10.2.3 compilation/build OK
![Screenshot - 07_05_2023 , 12_23_37](https://user-images.githubusercontent.com/4199131/236669080-eb02421b-e083-4ef3-814f-f446bcae9be0.jpg)

**Comment by michaliskambi** [comment]
Thanks for reporting. As per other ticket, I don't personally own Delphi 10.2.3 (I tested CGE on Delphi 10.4, and various 11.x -- including free Community Editions and Enterprise), so I need a bit more information.

1. When does the shown dialog appear?

    - Right when you click "Install"? Is the package installed afterwards or not?
    - Only when you rerun the IDE? Is it possible for you to uninstall the package?

2. Please test running example `examples/eye_of_beholder` . It doesn't matter if you have package in Delphi installed, as that example doesn't use TCastleControl. Just run the example and report if you have any crash, and if yes -- show where does the debugger point it.

3. Can you run `examples/delphi/vcl`? If yes, does it work or crash? If it crashes, show where. 

    This example uses `TCastleControl`, it is instantiated already at design-time on form, so opening it in Delphi IDE without the CGE package installed will make a big warning. If you can ignore it in Delphi 10.2.3 and run the example anyway, please do.

4. Same for `examples/delphi/fmx`?

5. Finally, please test commenting out contents of `procedure Register` in `src/delphi/fmx.castlecontrol.pas` and (separately( commenting out contents of `procedure Register` in `src/delphi/vcl.castlecontrol.pas`. Please test them separately and see what happens if you try to install the package (uninstall it first for these tests, if already installed):

    5.1. Comment out contents of `procedure Register` both in `fmx.castlecontrol.pas` and `vcl.castlecontrol.pas`. Reinstall package. Does Delphi IDE still show any error? (That would be very surprising, as we don't register any component then.)

    5.2. Comment out contents of `procedure Register` only  in `fmx.castlecontrol.pas`.

    5.3. Comment out contents of `procedure Register` only  in `vcl.castlecontrol.pas`.

Sorry for so many tasks, but I just cannot reproduce it without owning Delphi 10.2.3.

I assume you have some reason for not upgrading to latest Delphi (as mentioned above, CGE is tested on 10.4 or various 11.x). Of course if you can actually upgrade this would be easiest. Note that Delphi Community Edition (free) is at 11.3 now.

**Comment by peardox** [comment]
@michaliskambi I've got access to 10.2.3 (you should have too via https://my.embarcadero.com/#login) In fact if you check your DEVREL license you'll find you've got access as far back as XE2 (Help -> License Manager) [Note to others - a specific license is required which myself + Michalis have -  if you don't know what DEVREL is you prob ain't got the access in question)

10.4 started introducing auto versioning - {$VERSION AUTO} before then you'd usually rely on a huge ifdef ladder to identify versions. This is the most likely issue that immediately springs to mind.

If you want I can check installatioin on versions prior to 10.4 - there wiil be some specific version that fails and subsequent ones are OK (started doing this for Python4Delphi then they just went min = 10.4 so stopped).

**Comment by michaliskambi** [comment]
@peardox Thank you! Indeed I have access there -- didn't know they host old versions. I see a download link to Delphi 10.2 indeed there, and indeed my key should support this.

I'm not sure what do you mean by auto versioning (there's no such construct as `{$VERSION AUTO}`, I assume it was a mental shortcut but it elludes my knowlegle :) ). For detecting Delphi versions in CGE, we use `VERxxx` (and the change in https://github.com/castle-engine/castle-engine/commit/21b3c3fa464319e48053b3fc452ed589edc6d91b did fix Delphi 10.2 compilation) or `CompilerVersion` (which is since Delphi 6 from what I know). So we should be safe.

That being said, if you can help with testing older Delphi versions and reporting the issues -- I would be very very grateful :)

**Comment by peardox** [comment]
Thought so - You key should be good for all 10.x versions then. If you (or I) want to check the XE line then you need installation keys whuch are also available from same page - gimme a should if you need exact URL to get the install keys - did this ages ago so a buit rusty on where they are (wrote them all down though - not sure if they're linked to my DEVREL license though)

Sure - I'll run up some VMs and check when things fail and why

Yeah - that syntax is {$LIBSUFFIX AUTO} which basically removed the need for VERxxx define trees from 10.4 (but bugged on initial release - became stable with 10.4.2)

When going thru the https://github.com/Embarcadero/Lightweight-Python-Wrappers etc stuff which it began degrading badly prior to 10.4 (which could be helped with VERxxx but not eliminated). CGE should be a lot more Delphi-friendly than P4D was though.

Dunno what project / example that error mesage came from - I guess any CGE project would do the same of bad versions tho (although simply dropping a CastleWindow on a form seems a little on the inadequate testing side) - Guess I can use my Steam project to test :)

**Comment by michaliskambi** [comment]
@peardox Thank you, help with this is much appreciated.

> Dunno what project / example that error mesage came from - I guess any CGE project would do the same of bad versions tho (although simply dropping a CastleWindow on a form seems a little on the inadequate testing side) - Guess I can use my Steam project to test :)

That's a question to reporter, I also asked about it in AD 1. My understanding is that using "Install" on Delphi package in `packages/delphi/` results in this error. (I doubt our recent change to 1 design-time package in https://castle-engine.io/wp/2023/05/06/use-delphinus-to-install-castle-game-engine-in-delphi-also-simplified-delphi-packages/ helped this anyhow, but at least it will make testing easier.)

**Comment by peardox** [comment]
I'll test tomorrow and see what happens

**Comment by peardox** [comment]
Oh. yeah. There is a specific and valid reason why some people may prefer pre 10.4x versions ofd Delphi. 

If you purchase a license you get al updates for a year (plus any criticals). You license permits you the ability to sell your applications. CE, however, is licensed in such a way that you can also sell  your apps BUT after $5k sales (not profit) you have to purchase a license.

If someone had purchsed a license for e.g. 10.2.3 they could continue selling their apps without upgrading so as long as you didn't need any of the newer features it sorta makes sense to keep going with a full license rather than pay for updates - you've got a full dcc and source which are missing and partial respectively in CE.

Also 10.2.3 would have had access to Linux compiler which may be another critical decision in not desiring a newer version of CE. AFAIK the only stuff missing from 10.2.3 would be Mac desktop (10.3+) and iOS. 12+

**Comment by peardox** [comment]
@michaliskambi About to start version checking. What;'s the olderst version you've tried CGE on? To do this properly I should really test every xx.yy.zz release but wanna avoid pointless cases for now (as I know it works on 11.3.0 for example)

Will be using the Delphinius installer to check that out.

**Comment by peardox** [comment]
@limelect Have you recently installed Delphi 10.2.3 on n new PC? I ask as I've just installed the same version in a VM and the install is of the age that it doesn't install the Windows Platform SDK any more (URLs change in 5 years).

If this is the case SDK #1809 was current around the time of the 10.2.3 release and you can get a copy + install from https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/

I haven't installed CGE on that VM yet (about to) but it's the kind of thing that could very possibly cause problems. More news when I've installed and tested CGE

**Comment by peardox** [comment]
@michaliskambi Confirmed with a Delphinius install - inspecting further...
![d10 2 3](https://user-images.githubusercontent.com/1549219/236881342-eae219fb-be4a-41d3-b2c7-53a4f1605a4d.png)

**Comment by peardox** [comment]
Just tried a manual build. It compiled OK but the Install reised the same access violation so it appears to be in the registraion part. The implication here is that there's something in the dpk/dproj as register is far more unlikely (it's a keyword - nothing would work).
As it's now all one package hard to be more specific right now. I did spot something slightly concerning when Delphinius was installing so intend to go check 11.3 CE (not seen it yet so I'm interested anyway) next then 10.3 then back to this one (assumin no failures before)

**Comment by michaliskambi** [comment]
@peardox 

> What;'s the olderst version you've tried CGE on? 

The oldest I tested is on 10.4.

> Just tried a manual build. It compiled OK but the Install reised the same access violation so it appears to be in the registraion part.

Great, so you can reproduce the issue. If you can, go ahead and do experiments I outlined in my first comment, https://github.com/castle-engine/castle-engine/issues/478#issuecomment-1537548794 . These will pinpoint where the problem may be.

**Comment by peardox** [comment]
Will do.

> The oldest I tested is on 10.4.
Which specific version? 10.4.0, 10.4.1 or 10.4.2 (most likely the latter)

**Comment by michaliskambi** [comment]
> Which specific version? 10.4.0, 10.4.1, 10.4.2 or 10.4.3 (most likely the latter)

Looking into my early notes , I tested both Delphi 10.4.1 and 10.4.2.

That said, the oldest Delphi version that I actually have installed and so test regularly is 10.4.2. To make sure nothing went wrong (though Jenkins is testing Delphi compilation too, but only with 11.x now) I rechecked it today to make sure it all goes well. I can:

- build and run `examples/eye_of_beholder` (uses TCastleWindow)
- install package `packages/delphi/castle_engine.dproj` (installs TCastleControl for VCL and FMX)
- build and run `examples/delphi/vcl/` (uses TCastleControl in VCL, the animation in TCastleControl also plays at design-time)
- build and run `examples/delphi/fmx/` (uses TCastleControl in FMX, the TCastleControl at design-time shows text "Run the project to see actual rendering.." -- necessary on FMX)

Confirmed today with 10.4.2 and 11.2 (patch 1).

**Comment by limelect** [comment]
My 10.2.3 is old since 10.1
I jumped from 6 and 7 to 10
P.S I have been in Delphi since #1
I have a legal license 
I never updated as in my line of work I do not see
any reason to do so
As for the error, I cannot compile the demo as I do not have the component
I tried even loading the BPL and got the same error.

**Comment by peardox** [comment]
@limelect That's fine and I completeloy understand - I mentioned the most likely reason for not upgrading above (it's dead expensive too)

I'm about to try the tests @michaliskambi asks for on 10.3.3 (which also fails) - I do have an inkling as to why this is happening and will look at a solution later (I wanna test 10.4.2 as well first as I _think_ that one will install fine owing to a compiler switch added in 10.4).

**Comment by peardox** [comment]
> 1. When does the shown dialog appear?

After build when installing palette
Can't uninstall
Manual build confirms issue it at install

> 2. Please test running example examples/eye_of_beholder
Compiles but run shows no window

> 3+4 Can you run examples/delphi/vcl? If yes, does it work or crash? If it crashes, show where. + fmx
Crah with access violation - debugger shows it was trying this in both cases...

>>>  System.Generics.Collection

function TDictionary<TKey,TValue>.Hash(const Key: TKey): Integer;
const
  PositiveMask = not Integer($80000000);
begin
  // Double-Abs to avoid -MaxInt and MinInt problems.
  // Not using compiler-Abs because we *must* get a positive integer;
  // for compiler, Abs(Low(Integer)) is a null op.
  Result := PositiveMask and ((PositiveMask and FComparer.GetHashCode(Key)) + 1);
end;


> 5. Finally, please test commenting out contents of procedure Register
Leaving register proc but commenting out RegisterComponents = Access Violation on manual install

**Comment by limelect** [comment]
P.S i run castle-engine-delphi-10-2\examples\animations\animate_bones_by_code
(did not need a component) sam problem.

BP here
begin
  Application.MainWindow.OpenAndRun;
end.
cannot even start with F8 or F7

**Comment by limelect** [comment]
got it
it breaks here
procedure TTextureFontData.TGlyphDictionary.SetItems(const AKey: TUnicodeChar; const AValue: TGlyph);
begin
  AddOrSetValue(AKey, AValue);
end;

**Comment by peardox** [comment]
Same thing spotted here

![fonts](https://github.com/castle-engine/castle-engine/assets/1549219/daa7a97b-50ef-4a66-bfa4-e8b6d616f2f4)

**Comment by limelect** [comment]
Could not find AddOrSetValue implimantation

**Comment by peardox** [comment]
I presume they added AddOrSetValue to Delphi's TDictionary starting with 10.4 - should just need a repalcement {$IFDEF Delphi_Less_Than 10_4 } or similar.

[I should install XE2 as well then once tis one is fixed to find out how bad that is]

**Comment by limelect** [comment]
Back to the drawing board

**Comment by limelect** [comment]
May be add it here ?
 TTextureFontData = class

**Comment by peardox** [comment]
If you want to try CGE out then 11.3 CE (Free) will work while you're waiting - there is a installation issue there too though #479. 

Ask me if you want the full instructions (it's not obvious). That being said Michalis usually get's these kind of things fixed very quickly.

**Comment by limelect** [comment]
No thanks, I have 7 and 10.2.3 on this computer. this is my life I do not want
to change something working with no problems.
P.S My site for free goodies even for Delphi
www.limelect.com

**Comment by limelect** [comment]
I made a mess on Discord as it wants me to claim the account but I am
already registered with my mail (do not remember my password)
Impossible to get out of this situation

**Comment by peardox** [comment]
Discord is very unfriendly in that respect thugh I did see a join message for you. I recently had a laptop die - took me ages to get everything back to normal inc Discord (as I have >1 account it was a mess).

https://support.discord.com/hc/en-us/articles/218410947-I-forgot-my-Password-Where-can-I-set-a-new-one-

**Comment by limelect** [comment]
well it sees me (I am registered) but it wants >>> claim the account 
In any case, thanks as I do not see myself entering into another discussion.

**Comment by limelect** [comment]
I will wait for the fix

**Comment by michaliskambi** [comment]
Thank you both for investigation and finding the culprit.

As I needed to experiment, I finally installed Delphi 10.2.3. It took a long time, just finished.

( It's great I have access to all available Delphi versions, once this is fixed we'll have to go back in time and figure out how old Delphi versions we really want to support in CGE. And we'll document it on https://castle-engine.io/supported_compilers.php and test them with Jenkins.  )

I do not yet know what's the ultimate cause. The `AddOrSetValue` exists in Delphi 10.2 (it would not compile otherwise), but apparently just crashes, at least on certain cases where CGE is using it. I can reproduce it reliably at the same place you had. I tried simple workaround, only to find that 
- `TryAdd` is not available for Delphi 10.2
- `ContainsKey` on that dictionary crashes too
- once I workarounded `ContainsKey`, the `Add` crashes too...

So I have now a rather convoluted workaround that avoids using `AddOrSetValue`, avoids using `ContainsKey`, and in the end still crashes on `Add`.

More tomorrow. The really important thing to test will be whether this is some crash specific to this specialization (TTextureFontData.TGlyphDictionary) or context of it, or just all uses of generic `TDictionary` in CGE require some workaround.

**Comment by peardox** [comment]
> As I needed to experiment, I finally installed Delphi 10.2.3. It took a long time, just finished.

I've done that exact same thing six times for various versions of delphi and repeats in VMs - boring as hell ain't it :)

**Comment by peardox** [comment]
Wouldn't temporarily removing fonts from the local CGE identify if the problem exists onky in fonts rather than globally?

**Comment by peardox** [comment]
Is this fixed now then?

**Comment by michaliskambi** [comment]
Fixed!

In the end, the bug was only affecting 2 TDictionary usages in whole CGE (the ones that defined own constructor in descendant), and there was a simple workaround.

( We now pass explicit "comparer" instance, otherwise for unexplained reason FComparer (private in TDictionary) was nil. More comments in the commits attached to this issue. )

Tested and OK now (with Delphi 10.2.3):
- examples/eye_of_beholder/ builds and runs OK
- tests/ builds and runs OK
- packages/delphi/castle_engine.dproj compiles and installs without any issues.
- examples/delphi/vcl and examples/delphi/fmx can be both opened, TCastleControl is visible at design-time, and all works OK when you build and run them.

As usual, the fix is already in GitHub "master" branch (source code). It will be included in binary downloads available from https://castle-engine.io/download in a few hours, once Jenkins builds everything. You can watch the page https://github.com/castle-engine/castle-engine/compare/snapshot...master : when it will **no longer show the commit "Fix Delphi 10.2 crashes when using TTextureFontData.TGlyphDictionary..."** -> it means that the fix is included in downloads on https://castle-engine.io/download .

**Comment by peardox** [comment]
Righy. I'vr got 10,2,3 and 10.3.3 ready to test so I'll give it a go yjen start going backwards afain to see where next fail is (XE4 has compiler daiures for diferent reason  noted in Discord for now)
