### ISSUE TITLE
Delphi - TCastleControl greyed out in 64 bit Window palette

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#498]
[Via Delphinius Install on 10.2.3 as per recommended method]

![palette](https://github.com/castle-engine/castle-engine/assets/1549219/5eba953a-7405-47ea-b96c-440dfcd946a7)

This grab comes from setting the platform to Win64. You will notice that TCastleControl is greyed out - i.e. you can't add one. In Win32 it's fine. The work-around is to switch to Win32, stick a TCastleControl on the form. The component will now be added to the form and you can edit it's properties then switch back to Win64. The properties may also be edited in Win64.

In the event that you wish to add another TCastleControl to the form you have to switch back to 32 as even though the component is visible and editable Delphi still has it greyed out in Win64 palette.

The reason for this is appears to be that FMX/VCL are not split from the other code. AFAIK you ideally need a project group like this....

CastleEngine (CGE RTL without any FMX/VCL)
bpl.FMX.TCastleControl (RTL for  FMX TCastleControl - bpl prefix seems to be standard in Delphi)
FMX.TCastleControl (Design for FMX TCastleControl)
bpl.VCL.TCastleControl (RTL for  VCL TCastleControl - bpl prefix seems to be standard in Delphi)
VCL.TCastleControl (Design for VCL TCastleControl)

I actually have a project set up exactly like this (inc naming). That's the one that's complaining about inclusion of vcl in castle_engine280 actually (something I'm still investigating - it'll be something stupid by me probably when splitting RTL from Design

**Comment by michaliskambi** [comment]
Short answer: I made a fix (in branch split-delphi-design-time-package, commit linked above) but to merge it to master branch, we need first Delphinus fix https://github.com/Memnarch/Delphinus/issues/93 . Otherwise, by merging this change right now, I would fix this issue, but then break installation of CGE using Delphinus.

Longer answer:

The direct issue here is that castle_engine.dpk no longer (after this commit: https://github.com/castle-engine/castle-engine/commit/62b00ab9aca3566eab7d7e76b9438ef06fa741ba ) has Win64 in "Target Platforms". For Delphi this implies that package is not registered for Win64.

`<history>`

In the past, before https://github.com/castle-engine/castle-engine/commit/62b00ab9aca3566eab7d7e76b9438ef06fa741ba , it was half-working but in a dirty way. The package had Win64 in target platforms, but then it used unit `ToolsAPI` (which requires `designide` package which is, like Delphi IDE, only for Win32). So the package didn't actually compile for Win64, despite having it in Target platforms. This was dirty, and Delphinus rightly complained about it (Delphinus tries to recompile package for all platforms it declares). So I removed Win64 from target platforms.

`</history>`

The clean solution is to have finally a split design-time vs run-time, as we talked in many related threads now. I did this in branch now https://github.com/castle-engine/castle-engine/compare/split-delphi-design-time-package , splitting our package into castle_engine and castle_engine_design (to address this specific issue, no more is needed from what I can see).

- So we have 2 clean packages that compile for all platforms they declare, good (castle_engine compiled for Win32 and Win64, castle_engine_design only for Win32 and it can depend on `designide`)
- And this issue is solved (TCastleControl is not grayed out on Windows 64)
- ... but unfortunately we land in this Delphinus issue: https://github.com/castle-engine/castle-engine/issues/84#issuecomment-1537262037 . Delphinus doesn't handle correctly when one design-time package depends on another. This issue shows we simply cannot avoid it, we need a fix for this for Delphinus side. This has to wait on https://github.com/Memnarch/Delphinus/issues/93 .

**Comment by peardox** [comment]
What I'm aiming for is a package that could be submitted to GetIt (as you've already expressed this as a long-term goal).

As Jim is leaving (https://www.youtube.com/watch?v=-gtp9KQOOzE) I've contacted Ian Barker (he's the new Jim) asking about how GetIt wants the differing versions in genera (as it appears that GetIt provides version dependant downloads)

There's no documentation I can find on packaging for GetIt so guidance will prove useful (I'll let you know if he replies).

Essentially it should be possible to have an always latest GetIt version via the repo and just supply some LTS version for official GetIt at your discretion (I just wanna work out how o do it - actually doing it it of course your end)

I would assume that any GetIt package would also work with Delphinius - documentation will clarfy this I hope...

Of course, possible isn't always practical :( Hopefully I'll find out in the not too distant future.

I'll try out the branch after I've done the wrong version installed tests (almost ready to test it now - it's a long winded procedure setting this up non-destructively...)

**Comment by michaliskambi** [comment]
@peardox Thank you -- yeah, we very much want to be in GetIt too!

**Comment by peardox** [comment]
@michaliskambi I've asked @viniciusfbb for advice - he's been helpful in the past and Skia is on GetIt so seemed like a good person to ask for asdice

**Comment by checkdigits** [comment]
Hi folks. I was about to reply to @peardox email but I saw some alerts regarding this repo so I thought it made sense to reply here since there is a discussion going on.

I'm not sure if you're already in GetIt but a quick search in D11.3 and on GetItNow suggests you're not. Have you submitted at all yet to GetIt or is this the first time?

![image](https://github.com/castle-engine/castle-engine/assets/2126394/3636017e-37f5-4dbd-a463-1c8f43217e77)


If it's the first time I can reply to @peardox email with details on how to do it along with some contact information of someone who can give you very specific help (since he does the actual work behind the scenes of getting things to appear on GetIt).

I've flagged this repo so I get all activity alerts - I am on a lot of repos both internally to Embarcadero and externally for projects as well as for my own coding so I have to be a little choosy over what and who I follow 😉 

I'm really pleased the Castle Game Engine is heading towards GetIt - it's a great project and anything I can do to help is a pleasure.

![image](https://github.com/castle-engine/castle-engine/assets/2126394/9e6f6804-7bdc-4789-a8d1-7adb26746968)


LOL - yes I am the new Jim - or, more correctly, I am the Embarcadero Developer Advocate. 🤣 

You can reach me by email on ian.barker at Embarcadero dot com.

**Comment by peardox** [comment]
Thanks @checkdigits / Ian. Yeah, got your email - will fwd to @michaliskambi etc

And, no, not on GetIt yet. Michalis has mentioned this being desirable in the past so I'm just jumping in and getting the ball rolling plus testing everything.

CGE is currently compat with 10.2+ (Michalis is thinking of going back a little further too)

I'm basically taking point on discovering what we need to do so I can help Michalis get CGE on GetIt

**Comment by checkdigits** [comment]
Yes, I do not think it is a problem. We'll definitely get you on GetIt.  😃 👍

**Comment by michaliskambi** [comment]
@checkdigits Hello! 

Let's move the talk about GetIt to a different ticket, I created https://github.com/castle-engine/castle-engine/issues/500 -- where I also described some "high-level view" of what we want from GetIt , so that it's easier for you to digest. I guess we're just one of zillion people pinging you now about everything Delphi :), no rush, and I appreciate all the info. 

If you want to try Castle Game Engine as a "normal user" go ahead of course, follow downloads and manual from https://castle-engine.io/ , and let me know if you have any questions.

Let's leave this ticket for the original issue (TCastleControl grayed out on component palette). This solved in CGE branch now but needs Delphinus fix ( https://github.com/Memnarch/Delphinus/issues/93 ), so this is unrelated to GetIt :)

**Comment by peardox** [comment]
In my defense the mention is directly related to GetIt... But, yeah, I get your point...

Just loaded AllPackages as that contains the base - this is natural when using Delphi packages, ig a group ry that first +see what happens

**Comment by peardox** [comment]
Ahh - I see what's wrong - your output folder is castle-engine\packages\delphi\output

You'll already have that in your path but fresh installs won't

Changing these in line with #492 should make this problem disappear...

**Comment by peardox** [comment]
And...
castle_engine_design.dproj needs this

>		<DCC_UnitSearchPath>../../src/base;../../src/common_includes;../../src/scene;../../src/scene/glsl/generated-pascal;../../src/base_rendering/glsl/generated-pascal;../../src/base/windows;../../src/vampyre_imaginglib/src/Source;../../src/vampyre_imaginglib/src/Source/JpegLib;$(DCC_UnitSearchPath)</DCC_UnitSearchPath>

With that and the above changed in both dproj files it compiles without error under 10.4.2 in Win32 Debug and the resultant libraries are placed where Delphi can find them (version independanet)

- need to test Release + Win64 yet
- The DCUs could do with placing somewhere sensible. This is slightly more complex as there could be multiple files called foobar.dcu so ideally these want to be placed in a CGE-specific path under $(BDSCOMMONDIR) - this is something GetIt shuld be able to handle and additionally set the paths - more investigation required on this facet

**Comment by peardox** [comment]
Finally I loaded the simple test projects - everything is now fully compiled and visible

Nautrally it won't comple a test project yet (these eally should also be in libs) so I set....

Options -> Language -> Delphi

Win32 Library path
C:\git\castle-engine\packages\delphi\Win32\Release
Win32 DCU path
C:\git\castle-engine\packages\delphi\Win32\Debug
Win64 Library path
C:\git\castle-engine\packages\delphi\Win64\Release
Win64 DCU path
C:\git\castle-engine\packages\delphi\Win64\Debug

Now they will compile and indeed all tests on VCL + FMX pass

A good result and a alpha step towards GetIt :)

**Comment by peardox** [comment]
As a final tweak I changed both dproj files to this...

>         <DCC_DcuOutput>$(BDSCOMMONDIR)\CGE\$(Platform)\$(Config)</DCC_DcuOutput>
>         <DCC_ExeOutput>$(BDSCOMMONDIR)\CGE\$(Platform)\$(Config)</DCC_ExeOutput>

The effect of these lines is (of course) that the DCUs and up in a directory Delphi can find them in a version independant way PROVIDED that the above paths are set with $(BDSCOMMONDIR)\CGE\$(Platform)\Release and $(BDSCOMMONDIR)\CGE\$(Platform)\Debug - this is something that GetIt should be able to handle without user interaction

If a repo user uses this version then of course they have to set these manually (but only once)
Any fresh pulls ALSO REQUIRE package re-installation of course - not a huge problem for normal use. Problematic I would guess for library development tho.

Personally I like this specific version so much I'm going to use it on main machine for normal dev :)

**Comment by michaliskambi** [comment]
Thanks for testing -- looks like I didn't test split-delphi-design-time-package branch properly :), indeed I had "leftovers" after installing the package from Delphinus. 

My plan for this ticket (some time later this week):

- Fix https://github.com/castle-engine/castle-engine/compare/split-delphi-design-time-package
- Ping https://github.com/Memnarch/Delphinus/issues/93 again, but eventually we'll have to merge this to master without waiting for Delphinus.

**Comment by peardox** [comment]
> looks like I didn't test split-delphi-design-time-package branch properly

Hardly anyone does (so don't worry about it).
I wanna do a proper 'simulated' GetIt test - been on my todo for a week... I've outlined it in #500 (as it's directly related)

Working out the correct DCC_UnitSearchPath for the controls was a real chore but very worthwhile. TBH a similar process should be performed on the main package - which will prob be the one above plus a bunch more _BUT NOT_ the full list (there are almost certainly some paths that are not required - and every path you add will slow things down a bit)

I've verified [#93](https://github.com/Memnarch/Delphinus/issues/93) with the modified GetIt version. My thinking here is that the stuff that depends on FMX + VCL should be seperate so the non-VCL/FMX stuff only ever needs compiling once (which appears to cause the issue).

I wanna also try 'borrowing' the IDE helper from Skia and adapting it to do CGE stuff (copy optional libraries) - I'd just hack it into a semblance of 'working' so I could save you the hassle of working it out yourself (but you'd prob need to re-write).

One thing that sorta stands out in my mind is what happens if someone grabs the GetIt then wants to use the Git? There asre all sorts of potential problems here of course...

**Comment by michaliskambi** [comment]
> My thinking here is that the stuff that depends on FMX + VCL should be seperate so the non-VCL/FMX stuff only ever needs compiling once (which appears to cause the issue).

No. We had such layout at the start,

- castle_base
- castle_fmx
- castle_vcl

... and it was exactly causing Delphinus issues. This layout was changed to 1 design-time package exactly to accomodate this Delphinus shortcoming. See

- https://github.com/Memnarch/Delphinus/issues/93
- https://github.com/castle-engine/castle-engine/issues/84#issuecomment-1536988096
- https://github.com/castle-engine/castle-engine/issues/84#issuecomment-1537262037

Of course, as this ticket shows, 1 design-time package is really just not enough - we need at least 2, to have Win64 platform declared for package with TCastleControl. So we just really really need https://github.com/Memnarch/Delphinus/issues/93 fixed, or we'll have to break Delphinus,

( That's not to say we'll not go back to VCL/FMX split. If a practical reason for it will arise, then yes, sure. The split VCL/FMX certainly "feels" cleaner in terms of dependencies. )

**Comment by peardox** [comment]
It appears that Delphinius won't over-write an existing package while compiling via IDE is perfectly happy to. This is indicated by fixing split and trying both methods - IDE works while Delphinius don't

If the output DIR for the DCP is visually monitoered during compilation you can see that Delphi creates a temp ~castle_engine.dcp while building - the dcp is the design-time package from what I read (it says it contains executables - essentiaslly possibly multiple DLLs?)

**Comment by peardox** [comment]
Oh, yeah. I typically see packages that looik like this....

- package
- package.vcl.rtl
- package.vcl (the VCL design-time component)
- package.fmx.rtl
- package.fmx (the FMX design-time component)

So 1,2,3 are dependant on lower number and 1,4,5 are the same for FMX version with (1) having no VCL/FMX deps

**Comment by michaliskambi** [comment]
I'm moving forward with this. 

- I fixed various issues in packages to make all build and install without issues, without any preexisting paths set.

    I also removed usage of non-standard `packages/delphi/output`. 

    Note that I didn't do the split base/FMX/VCL. This split may happen in the future, for now I want to keep things as simple as possible. At a point when we'll be adding more platforms to Delphi (Linux, Android) -- we'll have a good knowledge whether the split base/FMX/VCL is really necessary and how to make it right, without speculating and creating too many packages.

- We cannot wait for Delphinus https://github.com/Memnarch/Delphinus/issues/93 . I commented section in `Delphinus.Install.json` so that it doesn't install the package. This makes Delphinus not very practical for CGE, I'll update our docs.

- Updated packages/delphi/README.md with various notes

- Merged it to master

The original thing reported here is fixed -- TCastleControl is (again) not dimmed for Windows 64.

**Comment by peardox** [comment]
Lemme know when you want ity testing again then

**Comment by michaliskambi** [comment]
> Lemme know when you want ity testing again then

The latest changes have been merged to master, and Jenkins also build them already into binary releases on https://castle-engine.io/download . 

I also updated some docs ( https://castle-engine.io/control_on_form , https://castle-engine.io/download , https://github.com/castle-engine/castle-engine/blob/master/packages/delphi/README.md , https://github.com/castle-engine/castle-engine/#readme ) to describe new layout (2 packages) and mostly remove Delphinus mentions. I hope we'll be able to restore Delphinus usage, but for this we need activity on issues we submitted lately ( https://github.com/Memnarch/Delphinus/issues ).

So if you're ready for another round of testing -> I will appreciate it, as always, and the time is now :) Thank you!

**Comment by peardox** [comment]
How far does this version go back then - 10.2 ? 10.1 needed - errm, some XML I think (I'd have to check)

I had an issue with DEVREL being installed too may times (it's bound to happen with clean testing). This has now been resolved by doubling my limit by Ian so full and complete tests are fine again.

**Comment by michaliskambi** [comment]
> How far does this version go back then - 10.2 ? 10.1 needed - errm, some XML I think (I'd have to check)

I didn't yet deal with older Delphi versions, leaving open the relevant issues:

- https://github.com/castle-engine/castle-engine/issues/488
- https://github.com/castle-engine/castle-engine/issues/486
- https://github.com/castle-engine/castle-engine/issues/482
- https://github.com/castle-engine/castle-engine/issues/481

So the current state supports Delphi >= 10.2, not older.

Documented on https://castle-engine.io/supported_compilers.php :

> The engine is tested and supported on all Delphi versions >= 10.2. It was actively tested on 10.2, 10.3, 10.4 (including CE), and all Delphi 11 editions (including 11.3 CE).
> 
> In the future, we could support Delphi versions >= XE 7.
> 
> Adjusting to Delphi XE 7 seems to require only a few local changes (see [XE7 test](https://github.com/castle-engine/castle-engine/issues/482), [10.0.1 test](https://github.com/castle-engine/castle-engine/issues/486), [10.1.2 test](https://github.com/castle-engine/castle-engine/issues/488)).
> 
> We do not plan to support older Delphi versions. They are really old ([Delphi XE6 is from 2014](https://en.wikipedia.org/wiki/History_of_Delphi_(software))) and would require more work (see [XE4 test](https://github.com/castle-engine/castle-engine/issues/481)). It doesn't seem wise to spend resources on maintaining (making and testing) compatibility with these ancient Delphi versions.
