### ISSUE TITLE
Shader doesn't log if missing files

### ISSUE THREAD

**Issue by RAT-Daddy01** [castle-engine/castle-engine#509]
When creating a new project I've added the default layout that comes with adding the 3d TCastleViewport.
In my GameViewMain unit I have added  CastleViewport & X3DLoad to my uses clause.
On TViewMain.Start
```
  MainViewport.AddScreenEffect
    (LoadNode('castle-data:/screen_effects/pixelate.x3dv'));
```

If the pixelate for example is missing .fs files I do get a warning but have to surf alot of log data as it outputs as follows.
[ShaderLog.txt](https://github.com/castle-engine/castle-engine/files/11931271/ShaderLog.txt)

Example project here:
https://mega.nz/file/NYQCVArS#MISEy_Nu6poS7QXr1GWf---vfPVRU-DrhDp9y5j0zWs

**Comment by michaliskambi** [comment]
Thank you for reporting!  Yeah, in this case we can make the log much simpler. 

Fixed, the log will look more readable now:

![obraz](https://github.com/castle-engine/castle-engine/assets/1076978/a133bf5f-c226-4afb-81be-af88124124ff)

The fix is committed to Castle Game Engine master branch. It will be available to download from https://castle-engine.io/download in a few hours automatically  (you can watch this page: https://github.com/castle-engine/castle-engine/compare/snapshot...master , when it will *no longer* contain the commit titled *_Better error reporting of missing fragment for screen effect_* then it means it's part of the released binary).
