### ISSUE TITLE
Create a testcase that local characters work after fixing: Warning: Implicit string type conversion

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#51]
I've got a lot of
```
Warning: (4104) Implicit string type conversion from "AnsiString" to "WideString" (30 times)
Warning: (4105) Implicit string type conversion with potential data loss from "WideString" to "AnsiString" (53 times)
```
when compiling the Engine in Lazarus. Still no problems ever occurred.
However, when I exported my Decoherence data to XML I've eventually remained without Cyrillic characters due to wrong `WideString` to `AnsiString` conversion :)
Making `AnsiString := UTF8encode(WideString)` and `TXMLDocument.CreateTextNode(UTF8decode(AnsiString))` solved the problem correctly (Cyrillic again displaying). Actually the last conversion was redundant - everything worked correctly without it, but, anyway, at least it removed the warning :)
Maybe, it's a correct way to solve the issue (if it needs to be solved)?
It's also possible just to remove the warnings by `{$WARN 4105 OFF}` and `{$WARN 4104 OFF}` if it's intended.

**Comment by michaliskambi** [comment]
This is due to the new encoding-aware strings in FPC >= 3.0.0, and due to the fact that FPC XML units (unlike everything else in FPC RTL) use WideStrings instead of AnsiStrings.

See
- http://wiki.freepascal.org/FPC_Unicode_support
- http://wiki.lazarus.freepascal.org/LCL_Unicode_Support (parts of it outdated, it seems, written before FPC 3.x)
- http://wiki.freepascal.org/Better_Unicode_Support_in_Lazarus (this seems more up-to-date)

I simply did not have the time to research yet how to *correctly* do everything, and avoid these warnings.  Our situation is complicated by the fact that 

- We want to work both with and without LCL. So we cannot blindly follow what LCL does, and we cannot ignore what LCL does either. And there are some "gotchas", see e.g. http://wiki.freepascal.org/Better_Unicode_Support_in_Lazarus#Why_not_use_UTF8String_in_Lazarus.3F .
- We want to work with FPC >= 3.x and FPC 2.6.4, for now.
- Our own code has problems too. We use AnsiStrings for everything, but sometimes we use AnsiStrings to hold always UTF-8 data (when dealing with X3D nodes and fields, when dealing with fonts in CastleFonts), and sometimes to hold "data in current OS codepage" (when we communicate with OS to open files). This needs to be correctly marked, to insert conversions (or to make compiler insert implicit conversions) where necessary.  Possibly, just changing AnsiString -> UTF8String everywhere where suitable would be OK... But I have not checked it.

I think that your solution with http://www.freepascal.org/docs-html/rtl/system/utf8encode.html is OK. But we should also check whether it works with FPC 2.6.4, on Linux and on Windows. Some problems may be visible only on Windows, as on Linux the "system encoding" is usually equal to UTF-8, so some problems are not visible.

Do you want to handle this? This would help me a lot.
- Can you submit your modifications with UTF8encode?
- And prepare a testcase? Simple example program, e.g. to engine examples/tools/check_string_encodings.lpr, that does some string operations using our routines (XML, font drawing, file opening), and from it's output we can see whether it's correct? This would be great!

I have FPC 2.6.4 installed on my system, as well as various other FPC versions, so once I have a simple testcase -- I can check everything with various compiler versions on various OSes!

See also https://github.com/castle-engine/castle-engine/issues/7 . It would be great to solve this too, along the way.

*The workaround for engine 6.0*: For engine 6.0, the warnings are hidden when compiling with build tool and xxx_compile.sh scripts (see the lines -vm4105, -vm4104 in `castle-fpc.cfg` and in `tools/build-tool/toolcompile.pas`).

But not when compiling with Lazarus, as I did not found a way to correctly do it (you cannot just use -vm4105 -vm4104 , as it would cause errors when compiling with FPC 2.6.4 that does not know these warning numbers).

Your approach is better, as now I can do:

~~~~
{$ifndef VER2}
  {$warn 4105 off}
  {$warn 4104 off}
{$endif}
~~~~

Unfortunately, doing it in `castleconf.inc` causes problems:

~~~~
Free Pascal Compiler version 3.0.2 [2017/02/05] for x86_64
castlegenericlists.pas(328,74) Error: Message recordind not yet supported
castlegenericlists.pas(376,74) Error: Message recordind not yet supported
castlegenericlists.pas(393,74) Error: Message recordind not yet supported
castlegenericlists.pas(401,72) Error: Message recordind not yet supported
castlegenericlists.pas(403,74) Error: Message recordind not yet supported
castlegenericlists.pas(410,74) Error: Message recordind not yet supported
castlegenericlists.pas(417,74) Error: Message recordind not yet supported
castlegenericlists.pas(424,74) Error: Message recordind not yet supported
castlegenericlists.pas(430,74) Error: Message recordind not yet supported
castlegenericlists.pas(437,74) Error: Message recordind not yet supported
castlegenericlists.pas(443,74) Error: Message recordind not yet supported
castlegenericlists.pas(450,76) Error: Message recordind not yet supported
castlegenericlists.pas(455,72) Error: Message recordind not yet supported
castlevectors.pas(2044,1) Fatal: There were 13 errors compiling module, stopping
~~~~

Arrgh, looks like the compiler is not ready to use `{$warn xxx off}` when dealing with generics. For some reason, the `-vm4105 -vm4104` don't cause such errors. So this workaround would have to be done only in some units....

For now, I did not pursue this. The *correct* solution is to not hide these warnings, but fix them, like with you UTF8Encode. To sum it up: help in fixing them would be very welcome:)

**Comment by eugeneloza** [comment]
Ok. I'll do it tomorrow (we have a day-off) and commit on Thursday :)
I'm not exactly sure about the testcase, but I'll see what I can do here.

**Comment by eugeneloza** [comment]
Well... It didn't appear as straight-forward as I expected :)
See commit: https://github.com/eugeneloza/castle-engine/commit/916868bca0b2e7a3b17cbcd1d1581b16111b1070
I've fixed all the issues, but not exactly sure about:
1. CastleXMLUtils.TDOMElementHelper.ChildElement - If it's used often (e.g. each frame), an additional string conversion might harm runtime efficiency. However, implicit conversion was still a conversion and should have also harmed efficiency, so there might be no loss.
2. CastleXMLUtils.TXMLElementFilteringIterator.GetNext - links to FTagName. I've changed it way FTagName remains an AnsiString. However, it seems that FTagName isn't used for other than internal purposes it might be more efficient to make FTagName a DOMString instead of converting it at each call - and convert it only once upon creation in TXMLElementFilteringIterator.Create.
I can fix it if you have nothing against FTagName: DOMString definition in TXMLElementFilteringIterator :)

Finally 85 warnings -> 1 warning :)

Here goes a list of all 40 functions affected:

CastleXMLUtils.TXMLElementFilteringIterator.GetNext
CastleXMLUtils.TXMLCDataIterator.GetNext
CastleXMLUtils.TDOMElementHelper.ChildElement
CastleXMLUtils.TDOMElementHelper.AttributeString
CastleXMLUtils.TDOMElementHelper.AttributeSet + all overloaded variants
CastleXMLUtils.DOMGetTextChild
CastleXMLCfgInternal.TXMLConfig.GetValue
CastleXMLCfgInternal.TXMLConfig.SetValue
CastleXMLCfgInternal.TXMLConfig.DeleteValue
CastleXMLCfgInternal.TXMLConfig.FindNode
CastleXMLConfig.TCastleConfig.MakePathElement
CastleXMLConfig.TCastleConfig.PathChildren
CastleXMLConfig.TCastleConfig.GetMultilineText
CastleSoundEngine.TRepoSoundEngine.SetRepositoryURL
CastleInternalNodeInterpolator.TNodeInterpolator.LoadAnimFramesToKeyNodes
CastleTiledMap.TTiledMap.LoadTileset
CastleTiledMap.TTiledMap.LoadProperty
CastleTiledMap.TTiledMap.LoadProperties
CastleTiledMap.TTiledMap.LoadImage
CastleTiledMap.TTiledMap.LoadLayer
CastleTiledMap.TTiledMap.LoadObjectGroup
CastleTiledMap.TTiledMap.LoadTiledObject
CastleTiledMap.TTiledMap.LoadImageLayer
CastleTiledMap.TTiledMap.LoadData
CastleTiledMap.TTiledMap.LoadTile
CastleTiledMap.TTiledMap.LoadAnimation
CastleTiledMap.TTiledMap.LoadTMXFile

x3dloadinternalcollada_integerparser.inc > TIntegersParser.Create
x3dloadinternalcollada_effects.inc > ReadColorOrTexture
x3dloadinternalcollada_effects.inc > ReadFloatOrParam
x3dloadinternalcollada_geometries.inc > ReadGeometry
x3dloadinternalcollada_matrix.inc > ReadMatrix
x3dloadinternalcollada_matrix.inc > ReadLookAt
x3dloadinternalcollada_read_helpers.inc > ReadChildText
x3dloadinternalcollada_read_helpers.inc > ReadChildFloat
x3dloadinternalcollada_read_helpers.inc > ReadChildVector
x3dloadinternalcollada_materials.inc > ReadMaterial
x3dloadinternalcollada_node.inc > ReadNodeElement
x3dnodes_encoding_xml.inc > ParseXMLNode
x3dnodes_node.inc > TX3DNode.ParseXML

**Comment by eugeneloza** [comment]
Continuing the issue:

There are 2 more string-conversion warnings in package castle_components in CastleLCLUtils:
Compile package castle_components 6.1: Success, Warnings: 2
castlelclutils.pas(425,31) Warning: Symbol "UTF8ToSys" is deprecated: "Use the function in LazUTF8 unit"
castlelclutils.pas(430,13) Warning: Symbol "SysToUTF8" is deprecated: "Use the function in LazUTF8 unit"
Changing the order of implementation... uses ... LazUTF8, FileUtil... should solve the issue (actually I've learned it from your book :D). I've made a commit: https://github.com/eugeneloza/castle-engine/commit/4123e164e00ad7787b5bd32020b97fdea648882f
However, I'm unsure if this is a correct way to do, as you might have had such order on purpose. We can also explicitly refer to LazUTF8.procedure to do the same thing.

Functions affected:
CastleLCLUtils.FilenameToURISafeUTF8
CastleLCLUtils.URIToFilenameSafeUTF8

**Comment by eugeneloza** [comment]
I'm still unsure about how to test these results (so, I don't create a pull request yet). All my programs and several examples I've tried run perfectly fine.
Basically we have a list of 40+2 functions listed above that should be "tested" against encoding conversion. And without "need" for any conversion they work as expected, but might have failed if using more complex alphabet like Cyrillic, Greek, Arabic or special symbols (e.g. in case a X3D node name contains a currency symbol).
The stuff is complicated by many READ functions not having their WRITE pair. E.g. CastleTiledMap READS Tiled map, but doesn't WRITE it. Same goes for Collada importer and others.
So, we can't make a simple "check" like s :='Съешь ещё этих мягких французских булочек, да выпей чаю!'; Write(s); Read(q); if q<>s then writeln('Cyrillic conversion failed!');.

**Comment by michaliskambi** [comment]
Everything looks cool! I'll do some tests (probably tomorrow), and merge:)

> If it's used often (e.g. each frame), an additional string conversion might harm runtime efficiency.

In a typical usecase, this is not used every frame, the XML file is read only once (when you run the game, when you load savegame etc.) So I would not worry about speed here.

> I can fix it if you have nothing against FTagName: DOMString definition in TXMLElementFilteringIterator 

This seems like a good idea.

> Changing the order of implementation... uses ... LazUTF8, FileUtil... should solve the issue (actually I've learned it from your book :D). I've made a commit: eugeneloza@4123e16 However, I'm unsure if this is a correct way to do, as you might have had such order on purpose. We can also explicitly refer to LazUTF8.procedure to do the same thing.

This solution is perfectly OK. I did not have any special intention when writing this, I was simply writing this code before the other version was deprecated :)

> I'm still unsure about how to test these results 

Indeed, some of these things cannot be checked automatically. But we can check them "visually". I imagined an example program that loads a TTF font that has some Cyrillic/Greek/Arabic special symbols, and then loads an X3D file using these characters (in the "Text" node), and also displays some strings (some hardcoded in the source file, some from text file, some from XML file) with TCastleLabel.

You could make a screenshot of it, and then other people could run it, and visually confirm that the characters look the same.

It's not really necessary to cover 100% of the affected functions -- it's enough to test some of them, to make sure that UTF8Encode / UTF8Decode work correctly. This would allow me to run various FPC versions (2.6.4, 3.0.0, 3.0.2, 3.1.1...) on various OS (Windows, Linux, MacOSX, Android, iOS...) and check that everything looks OK.

**Comment by eugeneloza** [comment]
I've fixed FTagName: DOMString, see https://github.com/eugeneloza/castle-engine/commit/a7923a03c42fbf94705d7a8f5dce5a2bd21eca1b. Looks like we're done with this part of the issue.

**Comment by michaliskambi** [comment]
> I've fixed FTagName: DOMString, see eugeneloza@a7923a0. Looks like we're done with this part of the issue.

I looked at the code, and I like everything you did. Can you submit a pull request? I would happily merge it:) 

Thank you!

Or do you want to write an example/test program first? Or, I could write a simple example/test program myself:)

For me, it's fine either way -- I can merge your current work now, and we will (you or me) add an example later. Or I can wait and merge everything later.

**Comment by eugeneloza** [comment]
Yes, everything looks clean and working for me without any issues. I've created a pull request https://github.com/castle-engine/castle-engine/pull/54
I should definitely try writing the test program (would be a very good practice for the future), however, I'm can't tell how "fast" will that be. I'm still unsure how exactly make it "the best and the most automatic way", I have some ideas, but not in "final stage".

**Comment by michaliskambi** [comment]
Thank you, the #54 is merged. I updated the title of this issue, to reflect that what remains is to write a test program. I may do it soon too:)

**Comment by michaliskambi** [comment]
I started something in examples/fonts/test_local_characters/ :)

**Comment by fredycc** [comment]
Hi, for this new example, where is automatic-windows-resources.res? Thanks

Regards

**Comment by fredycc** [comment]
Oh.. Thanks for the info 👍

**Comment by michaliskambi** [comment]
> Hi, for this new example, where is automatic-windows-resources.res? Thanks

Committed:)

Be aware that this is an early stage of the testcase for now, I plan to extend it during this weekend.

**Comment by michaliskambi** [comment]
The demo examples/fonts/test_local_characters/ is finished :)

It shows that we can 
- read the text with international characters (Chinese, Russian etc.) 
- from various sources (X3D scene, text file with TTextReader or TStringList, XML file with DOM or TCastleConfig, hardcoded in Pascal)
- and render it using TCastleLabel or X3D scene.
- And it works on both desktop and mobile (Android):)

That's enough for me for now:)

**Comment by eugeneloza** [comment]
Recompiled CGE today at Windows 7 * Lazarus 1.6.4 64 bit and got 6 more warnings in src\ui\windows\castleinternaltdxinput_tlb.pas
I'll fix it asap.
[castle_log_170321-CastleBase.txt](https://github.com/castle-engine/castle-engine/files/857466/castle_log_170321-CastleBase.txt)
[castle_log_170321-CastleComponents.txt](https://github.com/castle-engine/castle-engine/files/857465/castle_log_170321-CastleComponents.txt)
[castle_log_170321-CastleWindow.txt](https://github.com/castle-engine/castle-engine/files/857467/castle_log_170321-CastleWindow.txt)

**Comment by eugeneloza** [comment]
Looks like it's fixed:
castleinternaltdxinput_tlb.pas: class function CoAngleAxis.CreateRemote
castleinternaltdxinput_tlb.pas: class function CoVector3D.CreateRemote
castleinternaltdxinput_tlb.pas: class function CoSensor.CreateRemote
castleinternaltdxinput_tlb.pas: class function CoKeyboard.CreateRemote
castleinternaltdxinput_tlb.pas: class function CoDevice.CreateRemote
castleinternaltdxinput_tlb.pas: class function CoTDxInfo.CreateRemote
And:
castleinternalpk3dconnexion.pas: procedure T3DConnexionDevice.GetKeyboardKeyInfos
castleinternalpk3dconnexion.pas: procedure T3DConnexionDevice.GetKeyboardKeyLabels
castleinternalpk3dconnexion.pas: procedure T3DConnexionDevice.GetKeyboardKeyNames
(I'll push them in a minute)

**Comment by eugeneloza** [comment]
I'm not exactly sure about https://github.com/castle-engine/castle-engine/pull/61/commits/83ace14c50cbe44949111f59c5284b2824994c9c --- there were two ways of fixing the implicit conversion: either make s: string, or converting everything to s: widestring. I couldn't see any serious benefit of either approaches, so I did it with s: widestring.

**Comment by michaliskambi** [comment]
> I'm not exactly sure about 83ace14 --- there were two ways of fixing the implicit conversion: either make s: string, or converting everything to s: widestring. I couldn't see any serious benefit of either approaches, so I did it with s: widestring.

Ack.

I use "string" (which equals AnsiString) in all of the engine public API. But it's OK to use WideString or DOMString internally, when it makes more sense.

**Comment by eugeneloza** [comment]
So, I think it's solved then :)

**Comment by michaliskambi** [comment]
Yes:) I also checked the examples ("make examples") now:)
