### ISSUE TITLE
castle-editor for Delphi

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#516]
from #513

>The castle-editor will likely remain Lazarus-only for a longer time -- it would be a big effort to maintain an application for both FMX and LCL simultaneously. So we have to choose either only Lazarus, or only Delphi -- we prefer to choose the open-source dependency.

What are the issues here? I know you've got some editor components that would need FMX variants (VCL seems pointless)

From my own experiments with Delphi it appears that if developing a forms-based application (like Editor) a sensible way to do so is to divorce the UI from the TCastleControl and have a unit (or units) that interace UI to the CGE stuff. This is something that you'd naturally do if writing a game in any engine making for a View-Model-Control type of approach to dev easier to maintain.

Essentiaally the form-based UI is a bloody compilacted joystick / kb / mouse :)

**Comment by michaliskambi** [comment]
Some things related to TCastleControl usage, design cameras, undo system would indeed "just work" in Delphi.

But CGE editor is a significant piece of code that deals with UI, and that's largely LCL-specific at this point. Even porting it to VCL would likely be some effort (but as you say, and I agree, castle-editor on VCL would be pointless for us -- we don't want Windows-only editor). Porting it to FMX means changing all this UI code in castle-editor, and there's just a lot of it.

Moreover, and this really the bigger problem, there's no way then to maintain the project to support both FMX and LCL at the same time. Pascal code would need *a lot* of ifdefs and we'd need 2 separate sets of forms (LFM, FMX). This is not maintainable. 

So with the current approach, we have to make a choice, castle-editor compiles either Delphi or with Lazarus, but not both. And an open-source dependency that can be designed on any  platform is the winner.

**Comment by michaliskambi** [comment]
To be clear, as I wrote in https://github.com/castle-engine/castle-engine/issues/513 , there is a plan to have everything:

> At some point in the more distant future castle-editor will change to use CGE UI for everything, but that's a big road ahead before this can really happen. But at that point, castle-editor will be compileable with both Delphi and FPC, and work on mobile and web too, ...

So yes, eventually in the future we'll get castle-editor with Delphi, and with FPC, and lots of UI improvements to CGE UI (to have tree views, easy list boxes etc.), and as I wrote above -- it also opens the door for more platforms, e.g. web editor would be possible (since we know we'll put effort into CGE + WebAssembly soon).

But that's more distant future.

**Comment by peardox** [comment]
While you say build-tool (#515) should be firely easy to make Delphi friendly editor will take, presumably, somewhat longer and be in a constant state of development.

It would therefore seem sensible to make Editor available as a release binary so a Delphi developer can easily modify  /examples and compile with Delphi without the requirement of installing FPC + Laz

I intend to expand my testing and check ensure everything in /examples with a dproj compiles and runs as expected - I'll only do this for the lowest and highest supported versions of Delphi though (unless there's a simple way to batch build all dproj samples)

With Delphi a notable issue is CE of course. Ideally editor should be aware is the version of Delphi it's got is CE/Full although having said that simple user education will probably be OK (this won't compile from editor if using CE warning on first start?)

There are other tools but IMHO build-tool and editor are the only critical ones (plus view as an optional extra)

**Comment by michaliskambi** [comment]
> It would therefore seem sensible to make Editor available as a release binary so a Delphi developer can easily modify /examples and compile with Delphi without the requirement of installing FPC + Laz

Exactly, that's my intention for GetIt package. It will be a bit like CGE binary release on https://castle-engine.io/download , so with editor and build tool already precompiled to EXE. But of course without FPC bundled, and maybe with settings to automatically use Delphi by default (even if FPC is also installed on system and somehow detected -- if you installed CGE from GetIt, it should prefer to use Delphi regardless).

> I intend to expand my testing and check ensure everything in /examples with a dproj compiles and runs as expected - I'll only do this for the lowest and highest supported versions of Delphi though (unless there's a simple way to batch build all dproj samples)

Note that Jenkins already tests that all tools and examples compile with Delphi, though right now only with Delphi 11.3 installed on the Jenkins slave machine. I do intend to extend it, that machine should have more Delphi versions installed to perform tests on all versions we promise https://castle-engine.io/supported_compilers.php#section_platforms .

If you're curious how, you can take a look at `Jenkinsfile` (section `stage('Delphi on Windows')...`) and then `Makefile` have most of the commands. If you have proper Cygwin environment installed on your system, you can use it yourself on your machine too (in the end "Jenkins slave" is just a regular Windows machine with remote access) --- like

```
cd tests/
castle-engine clean
castle-engine compile --compiler=delphi --os=win64 --cpu=x86_64 --compiler-option=-dNO_WINDOW_SYSTEM
castle-engine run -- --console
cd ../

make examples-delphi CASTLE_ENGINE_TOOL_OPTIONS="--os=win64 --cpu=x86_64"
make examples-delphi CASTLE_ENGINE_TOOL_OPTIONS="--os=win32 --cpu=i386"
make test-editor-templates CASTLE_ENGINE_TOOL_OPTIONS="--compiler=delphi --os=win64 --cpu=x86_64"
make test-editor-templates CASTLE_ENGINE_TOOL_OPTIONS="--compiler=delphi --os=win32 --cpu=i386"
```

(the above is a subset what `Jenkinsfile` does with Delphi).

I don't really recommend you do this, because it requires to setup various things and in the end you will just so something that ultimately Jenkins should be doing, without any of us putting actual effort :) But anyhow, this is possible.

This depends on Delphi command-line compiler, though (called underneath by CGE build tool). So it is not possible to test Community Edition this way. With Community Edition, you can only compile from Delphi IDE interactively. I suppose creating a huge project group, maybe even auto-generating project group "AllExamples.projgroup", is an option. I''ll think about it. We naturally want to have  Community Edition tested -- as I know many people use it. 

> With Delphi a notable issue is CE of course. Ideally editor should be aware is the version of Delphi it's got is CE/Full although having said that simple user education will probably be OK (this won't compile from editor if using CE warning on first start?)

The CE doesn't have command-line compiler. We can detect it already -- "looks like you gave Delphi (looking at registry), but no command-line compiler -> OK, it's probably CE". Indeed we should display a clearer instructions to user then, like "you need to open this project in Delphi IDE, e.g. use Code->Open Project in Code Editor, and compile from there, you cannot compile directly from CGE editor with Delphi CE".

**Comment by peardox** [comment]
I've got Laz 2.2.6 / FPC 3.2.2 via FPCUpDeluxe on this machine so I'll build binaries for /tools and add them to a new /bin in CGE after pull as this will allow testing of Lazarus/FPC absent in my test VMs and should be similar to the layout used in the resultant Getit package

For testing all example dproj I can just create a groupproj in the /examples folder - I guess that should work and will simplify testing on earlier versions of Delphi
