### ISSUE TITLE
Missing castle-base package files

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#52]
While playing with string conversions I've found that
../src/x3d/x3d_node_helpers.inc
../src/ui/opengl/castlecontrols_tiledmap.inc
are missing in both CGE versions I have at my home PC. Everything compiles fine, so I think they just have been merged/renamed to other units and these links accidentally remained.
See screenshots attached.
![2017-03-08-074759_1366x768_scrot](https://cloud.githubusercontent.com/assets/10726162/23739258/3bee3d8c-04a6-11e7-8b76-1ad74d9dac1d.png)
![2017-03-08-074812_1366x768_scrot](https://cloud.githubusercontent.com/assets/10726162/23739259/3c157032-04a6-11e7-90da-a2050892c574.png)

**Comment by michaliskambi** [comment]
Yes,

* x3d_node_helpers.inc are removed now (they have been split into many (around 300!) .inc files inside src/x3d/auto_generated_node_helpers )
* src/ui/opengl/castlecontrols_tiledmap.inc was renamed to src/ui/opengl/castletiledmap_control.inc

They were also visible when using "More -> Show Missing Files" in Lazarus. I added a note to always check it before release. (I maintain a list of tests in https://github.com/castle-engine/cge-www in https://github.com/castle-engine/cge-www/blob/master/TESTS.txt ).

I updated the lpk, removing old and adding new .inc files. (Adding them allows Lazarus to know to recompile the package when a file changed, otherwise Lazarus doesn't run the compiler at all. So it is useful, although not strictly necessary.)

Thank you!
