### ISSUE TITLE
Null pointer exception when dragging "Behaviour" element between two TComponents in Editor

### ISSUE THREAD

**Issue by RAT-Daddy01** [castle-engine/castle-engine#520]
Reproduce Create a TCastleScene & a TCastleImageTransform
Add a physics collider box to TCastleImageTransform
Finally drag and drop the CastleBehavior from TCastleImageTransform to TCastleScene
Will throw an Access violation which loops regardless

Video from eugeneloza
https://github.com/castle-engine/castle-engine/assets/40525691/fd8a9d7b-b493-4913-b6ea-2f6ccc5966d2

**Comment by eugeneloza** [comment]
Thank you!

A tiny more detail: So, for some reason `Child in TCastleComponent(C).NonVisualComponentsEnumerate` returns `Child = nil` when `Behaviors` component is being dragged (not just behaviors themselves but the virtual container for the behaviors).

It crashes with `Child = nil` at this line:

![2023-07-06 22_56_34-Greenshot](https://github.com/castle-engine/castle-engine/assets/10726162/ee1ae1a0-f5e3-4212-bdb0-b274a2a69c03)

But it seems like the bug is not that simple as adding `and (Child <> nil)`. So, looks like `TNonVisualComponentsEnumerator` behaves incorrectly when it is built for `Behaviors` component.
