### ISSUE TITLE
"Copying "Behaviors" component also copies the parent in Editor"

### ISSUE THREAD

**Issue by RAT-Daddy01** [castle-engine/castle-engine#522]
Reproduce Create a TCastleScene & a TCastleImageTransform
Add a physics collider box to TCastleImageTransform

Copy the CastleBehavior to the TCastleScene, instead it will copy the CastleBehavior parent object too.
Another issue when copying both the TCastleRigidBody and TCastleBoxCollider, you can only copy one at a time.

Video from eugeneloza
https://github.com/castle-engine/castle-engine/assets/40525691/7f5074df-41f1-4d9f-bbbb-9d860434d960

eugeneloza created a ticket likely relatable here:
https://github.com/castle-engine/castle-engine/issues/521

**Comment by michaliskambi** [comment]
Thank you @RAT-Daddy01 @eugeneloza . I can reproduce the problem.

In all 3 issues ( https://github.com/castle-engine/castle-engine/issues/522 , https://github.com/castle-engine/castle-engine/issues/521 , https://github.com/castle-engine/castle-engine/issues/520 ) the root cause is the same: the "Behaviors" item in the hierarchy is not a real component. When you select it, most routines behave as if you have selected the parent TCastleTransform.

Sometimes this is intuitive (e.g. to display bounding box of selected transformation), sometimes it is weird ( https://github.com/castle-engine/castle-engine/issues/521 , https://github.com/castle-engine/castle-engine/issues/520 ) or just makes bug (as in this case).

I'll see how to fix it. We should just disable some operations on "Behaviors" tree item and/or treat the "Behaviors" tree item as the "multi-selection of all behaviors in this transform".

**Comment by eugeneloza** [comment]
> I'll see how to fix it. We should just disable some operations on "Behaviors" tree item and/or treat the "Behaviors" tree item as the "multi-selection of all behaviors in this transform".

Hmmm... I've just got an idea. Maybe we can "not have Behaviors" at all? Because it's not very intuitive for me altogether. And in turn differentiate "behaviors" from other 2D/3D elements by font or icon. I'm not sure if `TTreeView` supports that, but I've long ago was thinking about `TCastleTreeView` - maybe it'll be time to implement it? Should be relatively easy to.

**Comment by michaliskambi** [comment]
>  Hmmm... I've just got an idea. Maybe we can "not have Behaviors" at all? Because it's not very intuitive for me altogether. And in turn differentiate "behaviors" from other 2D/3D elements by font or icon. I'm not sure if TTreeView supports that, but I've long ago was thinking about TCastleTreeView - maybe it'll be time to implement it? Should be relatively easy to.

I don't think we want to "flatten" the behaviors, to be on the same indentation as children TCastleTransform and only differentiated by icons (if I understand your idea right). It would suggest to user that everything (children transforms, children behaviors, children Non-Visual Components) are part of one bag, can be reordered etc. 

And we will have even more such "lists of components" within component, e.g. list of `ScreenEffects` with `TCastleScreenEffect`, list of material overrides in TCastleScene etc. I want to also remake all these lists (current and planned) to descend from `TCastleComponentList<T>` to have uniform handling across editor, uniform drag-and-drop logic etc.

So we will not "get away" from such lists, because they are useful for more and more things :) And the "Behaviors" additional item clearly communicated that from code, this is (or rather will be) available as `MyTransform.Behaviors:TCastleComponentList<TCastleBehavior>` . 

I'm not saying we'll always have such extended hierarchy (maybe moving all these children from behaviors/non-visual components/screen effects/materials at some point to the right side will make sense? That's what Unity effectively has. But with current design we actually have more uniform treatment of all these components than Unity -- i.e. we have UI where you reorder TCastleBehaviors in the same way as you order TCastleTransforms.) But for now, I know I want to explore possibilities of this, not visually flatten it.

**Comment by eugeneloza** [comment]
But logic-wise they are flattened, aren't they? `TCastleScene.Items` is the same level as `TCastleScene.Behaviors`. If they look distinctive enough (e.g. blue cursive + different icon) they may be logical enough. Even can be a filter that will allow to show/hide behaviors; show/hide scene internals (like underlying root node tree).

**Comment by michaliskambi** [comment]
> But logic-wise they are flattened, aren't they? TCastleScene.Items is the same level as TCastleScene.Behaviors. If they look distinctive enough (e.g. blue cursive + different icon) they may be logical enough. Even can be a filter that will allow to show/hide behaviors; show/hide scene internals (like underlying root node tree).

They aren't "flattened" in the sense that `TCastleTransform` children (other `TCastleTransform`) and the behaviors are in different lists.

The way the design should be, eventually (quoting from my TODO, which in turn I posted once on Discord):

-------------

So we'll have

```pascal
TCastleComponent = class(TComponent)
  NonVisualComponents: TCastleComponentList<TCastleComponent>;
end;

TCastleUserInterface = class(TCastleComponent)
  Children: TCastleComponentList<TCastleUserInterface>;
end;

TCastleTransform =  = class(TCastleComponent)
  Children: TCastleComponentList<TCastleTransform>;
  Behaviors: TCastleComponentList<TCastleBehavior>;
end;
```

... and iterating with  `for .. in ... ` will be always equivalent to iterating over `Children`.

So

`for C in MyTransform do`

will be equivalent to

`for C in MyTransform.Children do`

Same

`for C in MyUserInterface do`

will be equivalent to

`for C in MyUserInterface.Children do`

And you can also do

`for C in MyTransform.Behaviors do...`

`for C in MyTransform.NonVisualComponents do...`


-------------

**Comment by michaliskambi** [comment]
Thank you very much for reporting, I remade the underlying code to not automatically select parent of "Behaviors" or "Non-visual components" in some cases. 

This avoids weird behavior at cut, delete, copy ( https://github.com/castle-engine/castle-engine/issues/522 , https://github.com/castle-engine/castle-engine/issues/521 ) and crashes when dragging ( https://github.com/castle-engine/castle-engine/issues/520 ).

Note: I created a new issue for one bit you mentioned: 

> Another issue when copying both the TCastleRigidBody and TCastleBoxCollider, you can only copy one at a time.

New issue is https://github.com/castle-engine/castle-engine/issues/525 .

For now, above fixes just block operations that were buggy / weird.
