### ISSUE TITLE
Tools pack for Delphi

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#524]
Taking snapshot as a base it appears as if the bin dir could do with being made available as a seperate download and / and as an extra dir in the getit package (which should be made publically available)

When I tried installing snapshot it decided it wanted to install in C:\Users\simon\AppData\Local\Programs\Castle Game Engine but castle-editor expects the bin dir to live in CGEDIR/bin (where CGEDIR is the dir getit installs it into)

If CGE is in a discoverable location then Delphi can have an IDE extension that includes any required DLLs as part of the build - this can work for all platfoms and prevents that wong zlib issue from a while back someone was having

As I'm looking specifically at Delphi here and getit can create a Delphi Environment Varable (note - this is not the same as an Environmrnt Variable - it's a reg key/value at HKCU\Software\Embarcadero\BDS\[Version]Environment Variables -> CGEDIR) - assuming CGEDIR is OK as a name of course.

If installed manually then the user should be advised to set this in Delphi Options to point at their chosen installation location (tutorial)

Castle-Editor could then locate the CGE installation by querying the registry by decending version until a CGEDIR was found that pointed to a valid directory

I want to write/video Delphi specific install instructions - an idiot's guide like the one I did for P4D (I still owe Jim, now Ian, some tutorials for my DEVREL...) so having the bin dir either in git or as a seperate release is desirable.

**Comment by michaliskambi** [comment]
> Taking snapshot as a base it appears as if the bin dir could do with being made available as a seperate download and / and as an extra dir in the getit package (which should be made publically available)

No, this would complicate downloads.

We want to make it simple for normal users: Download the engine from https://castle-engine.io/download , you have everything.

And if you want sources, there are instructions.

> When I tried installing snapshot it decided it wanted to install in C:\Users\simon\AppData\Local\Programs\Castle Game Engine but castle-editor expects the bin dir to live in CGEDIR/bin (where CGEDIR is the dir getit installs it into)

The fact that `bin` is a subdirectory of CGE dir is the basis of auto-detection of CGE location. 

I absolutely don't want to change this, it works nicely and is cross-platform.

We don't want to use registry for anything -- because it is not cross-platform, and because it relies on some install/uninstall step to setup registry.

> If CGE is in a discoverable location then Delphi can have an IDE extension that includes any required DLLs as part of the build - this can work for all platfoms and prevents that wong zlib issue from a while back someone was having

If we ever go with specialized Delphi tool for CGE (which I suppose we will - to install DLLs, also to update paths -- since Delphinus cannot be relied on this) it will have to know CGE location (and allow to switch it too).

I'm closing this ticket, but as said above: I actually think we'll indeed want to have a design-time CGE addition to set-up DLLs and update paths. I have this in my TODO. But the design of it is a bit different than what you propose.
