### ISSUE TITLE
For X3D 4.0, fields have changed, per Holger. Fixes needed for tovrmlx3d.

### ISSUE THREAD

**Issue by coderextreme** [castle-engine/castle-engine#530]

**Comment by michaliskambi** [comment]
This was moved to https://github.com/castle-engine/view3dscene/issues/59 .

@coderextreme You don't need to delete title, or contents :) of the old issue. It's enough to just provide a link to the new issue in a follow-up comment, if you close the old issue because you moved it to a better place.

For the future: It doesn't matter much whether you report X3D issues to CGE or view3dscene repo, both are cool for us. If you're not sure, and you observe the problem in view3dscene, then surely reporting to https://github.com/castle-engine/view3dscene/ is better, but this is no biggie.
