### ISSUE TITLE
LoadFromImage doing wierd things in Delphi TestCase

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#537]
https://github.com/peardox/SimpleDelphiTest01

Full notes in README.md

**Comment by michaliskambi** [comment]
Sorry it took so long, and thank you for the report. Fixed. 

Admittedly, `TImageTextureNode.LoadFromImage` was just broken for some time. Upon examination, it turned out that the contents of image, passed as TEncodedImage to `TImageTextureNode.LoadFromImage`, were... ignored, because immediately after loading them, we then discarded them (ouh...) and loaded whatever was specified in `UpdateUrl`. This was unexpected effect of one call.

This naturally should not happen -- `UpdateUrl` should not matter for immediate display, it should matter only if you later want to save this X3D to disk. 

Now it really behaves as it should.

P.S. Unrelated to this bugreport, 2 notes about the source code:

- Remember you can remove now kludges about data , https://github.com/peardox/SimpleDelphiTest01/blob/main/Unit1.pas#L134 . Engine automatically works EXE files in `platform/config` subdirs and detects data properly. I know, https://github.com/peardox/SimpleDelphiTest01/ was written before that :)

- I advise to activate log (InitializeLog). It contains some information, may also contain warnings. 

- In this case, log tells that textures are resized to power-of-2. This is nice if you want to display them later in 3D, with mipmaps, looking good from far away. But if you don't need it, then you may preserve to just keep your original resolution. For this, set `GuiTexture` to avoid this ( https://castle-engine.io/x3d_implementation_texturing_extensions.php#section_texture_properties_gui_texture ), like this done somewhere once:

    ```delphi
    TexProperties := TTexturePropertiesNode.Create;
    TexProperties.GuiTexture := true;
    MyImageTexture.TextureProperties := TexProperties;
    ```

**Comment by michaliskambi** [comment]
To be clear, after this fix, `UpdateUrl` you pass in `TCastleApp.MakeCard` doesn't really matter -- as long as you do not save this to X3D file. So all below are equivalent:

```delphi
MyImageTexture.LoadFromImage(NewFace, True, 'something random');
//MyImageTexture.LoadFromImage(NewFace, True, '');
//MyImageTexture.LoadFromImage(NewFace, True, CardFile);
```
