### ISSUE TITLE
ParseURI + others in Delphi

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#538]
I was just implementing custom urls in my project by pinching bits en-masse from network/custom_uri_handler

The code in gameinitialize wouldn't work as TURI and ParseURI have their own delphi-specific implementations in delphi-only/URIParser while the code should be in CastleURIUtils (for FPC)

This does mean that compiling that specific example will be problematic for those who don't know where to look

**Comment by michaliskambi** [comment]
I'm not sure what problem do you mean. The `URIParser` is a built-in unit in case of FPC (which is why we provide the source of it only for Delphi, in `delphi-only` subdir). The `network/custom_uri_handler` example compiles and works under Delphi and FPC both.

**Comment by peardox** [comment]
Only if the entire CGE source tree is in the path (and recompiled every time?)

Remember I'm using the Getit candidate version that only uses packages (thus CastleWindow don't currently work either as I previously informed you)  

On the whole the Getit Candidate is good with a few small issues like this you should be made aware of

**Comment by michaliskambi** [comment]
> Only if the entire CGE source tree is in the path (and recompiled every time?)
> 
> Remember I'm using the Getit candidate version that only uses packages (thus CastleWindow don't currently work either as I previously informed you)
> 
> On the whole the Getit Candidate is good with a few small issues like this you should be made aware of

Sorry, I don't follow, maybe this Monday was hard on my stamina, lots of issues everywhere I looked :) 

What is the problem you report here? What source code does not work in Delphi or in FPC? Can you show it exactly?

`URIParser` for Delphi applications is part of CGE. Yes, naturally it should be part of units path. We don't support now runtime Delphi packages (only design-time packages), but when we do, we will make sure to put `URIParser` so that it can be found. Just like `CastleWindow`. Our examples define paths that include these units, showing how Delphi users can use them now.

And `URIParser` for FPC is part of FPC.
