### ISSUE TITLE
Very Important Notice about `setup-lazarus`

### ISSUE THREAD

**Issue by gcarreno** [castle-engine/castle-engine#559]
## VERY IMPORTANT NOTICE

> When build for the `Qt5` widgetset, the combination of `stable`/`v3.0` and `ubuntu-latest`/`ubuntu-22.04` is going to fail.
>
> This is due to the fact that `libqt5pas` is outdated and does not support the new code delivered by Lazarus 3.0.
>
> This is a problem related to the Ubuntu distribution's repositories and the version of `libqt5pas` they carry, used by the GitHub runners.
>
> According to the maintainer of said `libqt5pas`, in [this answer](https://forum.lazarus.freepascal.org/index.php/topic,65619.msg500216.html#msg500216), one solution is to have the workflow script download and install a newer version.
>
> The newer version can be obtained here: https://github.com/davidbannon/libqt5pas/releases
>
> Thank you for your patience, continued support and please accept my deepest apologies for this inconvenience.

I will be monitoring this issue closely and will update everyone as I, myself, have more information.

Cheers,
Gus

**Comment by michaliskambi** [comment]
Thanks. 

This is important information in the context of CGE - while our default editor build for Linux still uses GTK2, but we do make alternative Qt5 editor version (i.e. Linux downloads https://castle-engine.io/download contain `bin/castle-editor-qt5`). This means we cannot upgrade to Lazarus 3.0, until reasonably all distributions (not only Ubuntu -- but anything that users may have) have upgraded libqt5pas. Since it's not only about libqt5pas available in CI environment, users must also have upgraded libqt5pas on systems where they run CGE editor.

It doesn't actually affect our https://github.com/gcarreno/setup-lazarus action usage, we don't build Qt5 editor in environment provided by this action. We have own Doker image ( https://castle-engine.io/docker ) where we do this. 

There's no immediately action for CGE here, we'll just not upgrade to Lazarus 3.0 before testing this super-carefully. Thank you for the notice.

**Comment by gcarreno** [comment]
Hey Michalis(@michaliskambi),

Awesome sauce!!

I was just trying to be as helpful as possible with this ongoing issue.
I'm glad it doesn't affect you guys!!

Cheers,
Gus
