### ISSUE TITLE
Converter should maintain or round off numeric values for best results

### ISSUE THREAD

**Issue by brutzman** [castle-engine/castle-engine#562]
Converter should round off numeric values for terser results.

An example that shows potential benefit:

- https://www.web3d.org/x3d/content/examples/HumanoidAnimation/WinterAndSpring/LilyAnimated.x3d

source:

`DEF r_carpal_proximal_interphalangeal_2Box Transform { translation -0.1566 0.3002 -0.0159 children [ Shape { geometry Box { size 0.01 0.01 0.01 } } ] }`
 
result:

```
<Transform DEF='r_carpal_proximal_interphalangeal_2Box' translation='-0.15659999847412109 0.30019998550415039 -0.015900000929832458'>
    <Shape>
          <Box size='0.0099999997764825821 0.0099999997764825821 0.0099999997764825821'/>
    </Shape>
</Transform>
```

With thanks, Joe Williams and Don Brutzman

**Comment by michaliskambi** [comment]
We've been talking about this on the x3d-public mailing list in the past ( http://web3d.org/pipermail/x3d-public_web3d.org/2023-February/018455.html ). The reasons for outputting floats (in text form) with maximum possible accuracy, by default, remain as they were.

That said, I can add an option to explicitly instruct `tovrmlx3d` to limit the output precision to e.g. 4 digits after the dot. This is in progress, I did some groundwork today, I'll try to finish tomorrow, I'll post more details then.

As for why the default is "maximum precision", I can reiterate and maybe phrase better my answer from the linked x3d-public thread:

- We cannot arbitrarily "round every float output to e.g. 4 decimal places after dot".
 
    Because for some people, 4 decimal places is good enough. But for other people they really need more decimal places. They store meaningful information there and depend on small epsilon differences between thin walls in 3D. They use all the precision they can get from 32-bit float data type. If we change input `0.123456` to `0.1234` on output, then it will be a bug for them. Because it will, in particular, mean that values like `0.00001`, `0.00002`, `0.00003` are all made exactly equal after conversion and rounding.

    So desires of people who "just want to see only 4 decimal digits after dot" (as Joe reported on x3d-public) must be balanced with desires of people who expect conversion process to preserve the numbers as accurately as it can.

- In general, "terser result" is not a primary goal of a converter. "Not losing any information, if possible" is more important.

    So while I will add an option to change the precision, the default will remain to output full possible precision.

- Note: we cannot just "output numbers with the same precision (decimal places) as they were in input". While it would be ideal, it is not practically implementable (in CGE/view3dscene or any other such 3D conversion software).

    These numbers are not stored in memory with the same precision as they were in input. See how computers store float (single-precision 32-bit float values). The CPU and GPU floating-point types cannot represent exact `-0.1566`. (This is how all 3D software works, to be clear, not just CGE/view3dscen, not just X3D.)

    At the moment when we output the data, we don't have the knowledge how many decimal digits have been specified in the input. We have converted all floats to 32-bit `float` type values.

    Note: I bet this is true for every existing VRML / X3D converter -- they all convert floats to 32-bit `float` type values, and then output them with full precision. Trying to preserve the information, for every number, how many decimal places were specified at input -- would be an overkill for maintenance and memory. Some ideas offered in http://web3d.org/pipermail/x3d-public_web3d.org/2023-February/018503.html , like using bignum or storing numbers as strings, are not practical (when you consider models have easily millions of floats -- we absolutely cannot represent them in any elaborate form like strings or bignum, we must represent them as 32-bit floats; it's also what everyone else, in X3D and general 3D, is doing).

- I realize that more precision on output -> makes larger text files. But we just cannot be perfect here, in light of above -- we either sacrifice precision sometimes (making a problem for some people), or we create larger files. We choose to create larger files, by default, but be safe (preserve all information we have).

- The ideal solution is storing float data in binary form, like glTF does, at least for per-vertex data. I was and am advocating this for X3D. See https://github.com/michaliskambi/x3d-tests/wiki/Binary-meshes . Then:

   - loading is efficient (no need to convert from text to float, just load the binary data directly to memory)

   - and saving back can be lossless (you load 32-bit float from file, you keep it in memory, you save 32-bit float in file).

   With text formats, like X3D classic or XML encoding, this is never going to be perfect -- conversion process has to transform text to 32-bit float and then back.

   But I know it's a larger goal to add this to X3D. That said, X3DOM already showed it can be done in X3D, in a way consistent with glTF. I want to integrate it with CGE/view3dscene, and hopefully with X3D spec too, some day.

**Comment by brutzman** [comment]
Thanks for review.  Additional points of interest:

a. The converter is receiving an input value to a given degree of precision.  If input value for Box size is `0.01 0.01 0.01` then translating that value as `0.0099999997764825821 0.0099999997764825821 0.0099999997764825821` has introduced inaccuracy.  Exact dimensions are critically important in some applications.  Exact values are further important for round-trip consistency and archival preservation of an original model in different formats.

b. For rendering-related parameters at least, and many other X3D fields, few values are perceptually discernable outside four decimal places, so offering a roundoff limit on maximum precision seems like a good option to offer.

**Comment by michaliskambi** [comment]
( The new option to `tovrmlx3d` is coming, I did not yet finish implementation. Below I only wanted to address the notes. )

Note that I believe I did address both your notes A and B in my previous comment ( https://github.com/castle-engine/castle-engine/issues/562#issuecomment-1898684233 ).  I try to give even more explanation below :)

> a. The converter is receiving an input value to a given degree of precision. If input value for Box size is 0.01 0.01 0.01 then translating that value as 0.0099999997764825821 0.0099999997764825821 0.0099999997764825821 has introduced inaccuracy. Exact dimensions are critically important in some applications. Exact values are further important for round-trip consistency and archival preservation of an original model in different formats. Am happy to discuss practical parsing methods for accomplishing that if you like.

As I mentioned above ( https://github.com/castle-engine/castle-engine/issues/562#issuecomment-1898684233 ), the "inaccuracy" already occurs when any 3D software reads these numbers to 32-bit floats (and even X3D spec says to use 32-bit floats).

The number like 0.01 is converted into 32-bit float in memory. It's never exactly 0.01, for CPU, GPU, in any 3D software. Please see my above comment where I talk exactly about that. Please also see e.g. https://en.wikipedia.org/wiki/Single-precision_floating-point_format , https://en.wikipedia.org/wiki/Floating-point_arithmetic .

We would like to be perfectly precise (I agree here with you!) but it is not practically doable, because of how floating-point works in all software in all computers. (Solutions like using BigNum are not practical for 3D software with millions of floats to pass to GPU.)

> b. For rendering-related parameters at least, and many other X3D fields, few values are perceptually discernable outside four decimal places. Offering a roundoff limit on maximum precision seems like a good option to offer.

It's true that *usually* these little details don't matter, but sometimes they do.

And for some models, 4 digits is enough. For some, 6 digits are enough, and 4 is not enough.

There can be a very significant visual difference caused by digits outside of 4 decimal places. Following my example numbers from https://github.com/castle-engine/castle-engine/issues/562#issuecomment-1898684233 , consider 3 planes at Z = 0.00001, Z = 0.00002, Z = 0.00003 . If we equate them all to just 0.0000 after conversion, we break them. Because on input, the planes were reliably ordered, one in front of another in front of another. On output, they are at the same place, and you will have Z-fighting.

Our overall strategy is: be maximally precise, as much as it is practical to do. We cannot really avoid changing 0.01 into 32-bit float (so it's not represented exactly precisely). We can at least output what we have, without arbitrary rounding.

**Comment by brutzman** [comment]
Appreciate your analysis.  Please be advised that this issue is not referring to roundoff issues that occur in any floating-point or double precision computations that occur during numeric processing.  I am referring to the change in the literal values that the conversion has produced.  Dominating factors are preservation of correctness, and ability of end users to discern a difference.

Primary: a conversion between various representations of X3D file formats or programming-language source code needs to maintain the same precision, namely same significant digits, if it wants to be considered lossless and round-trip capable.  This use case is essential when testing correctness of conversions from one form into another and then back again.

Additionally a useful option for options is the reverse operation, i.e. rounding off unnecessary digits that have no effect on human perception.  Few X3D parameters have any visual impact after the first several significant digits.  Some size variations may be noticeable physically when printing or constructing a physical 3D object that no longer fits as designed.  Notably the production process creating the physical 3D object may have ability to meet tolerances beyond the first few significant digits either.

If helpful, we might plan on an X3D Standards Working Group meeting to define guidelines and recommended practices for converters.

**Comment by michaliskambi** [comment]
We seem to be going in circles :)

I believe I explained our rationale 2 times above already. 

1.

>  Please be advised that this issue is not referring to roundoff issues that occur in any floating-point or double precision computations that occur during numeric processing. I am referring to the change in the literal values that the conversion has produced. Dominating factors are preservation of correctness, and ability of end users to discern a difference.
> 
> Primary: a conversion between various representations of X3D file formats or programming-language source code needs to maintain the same precision, namely same significant digits, if it wants to be considered lossless and round-trip capable. This use case is essential when testing correctness of conversions from one form into another and then back again.

There is no way to store 0.1 number precisely, as either `float` or `double`.
 
Please see the links I gave above to Wikipedia pages how are the floating-point numbers represented computers. Or read the manual for any programming language about `float` or `double`. We don't store the number 0.1 precisely in memory, we cannot. And alternative ideas, like storing as string or bignum, are not practical for 3D software. 

Maybe if we never wanted to do any calculation, we could do this (store numbers as strings), but the ultimate goal of CGE/view3dscene is to do calculation on these numbers and/or pass them to GPU. We cannot practically store every number as a string, it would be an overkill for code complication and memory usage. 

And that's how all 3D conversion software (that I know of) works. I'm really not claiming anything novel here. Look at what FreeWRL, X_ITE, X3DOM, Blender, libassimp or any other 3D software converting 3D works. When reading 0.1 to `float`, that 0.1 becomes something else, not precisely 0.1. Then at output, the software has a choice to either write all possibly-relevant numbers (we do this) or round to arbitrary precision (like 4 digits, possibly losing information if user had something meaningful in the 5th digit).

2.

> An additional useful option is the reverse operation, i.e. rounding off unnecessary digits that have no effect on human perception. Few X3D parameters have any visual impact after the first several significant digits. Some size variations may be noticeable physically when printing or constructing a physical 3D object that no longer fits as designed. Notably the 3D printing/production process creating the physical 3D object likely does not have the ability to meet tolerances beyond the first few significant digits either.

And I explained why rounding off arbitrary digits is bad. For you or Joe, maybe 4 digits is good enough. But then I will get an error report, because for someone the 5th digit contained something meaningful. I gave above an example where it may be meaningful ("3 planes at Z = 0.00001, Z = 0.00002, Z = 0.00003 ...").

I know that some software just chooses to round to 4 or 6 digits, and conversion in effect has edge cases when information is lost. I choose to not do this, by default. But I will add an option to do this, like `--output-precision=4`.

**Comment by michaliskambi** [comment]
( As usual, the snapshot version you can download from https://castle-engine.io/view3dscene.php will have this new feature shortly, give it ~1h since this message to be safe. )
