### ISSUE TITLE
Delphi IDE Integration issue...

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#569]
A picture is worth a thousand words so...

![image](https://github.com/castle-engine/castle-engine/assets/1549219/9c7622aa-7501-49de-b25b-1fe02bedb231)

**Comment by peardox** [comment]
Just updated Delphi12 via the 12.1 Patch and the above issue went away

The patch says it fixes IDE problems. Then again I now have no CGE menu at all....

**Comment by michaliskambi** [comment]
That menu is a work in progress. I have hidden it now -- we should not show it, it is also not documented.

Some of the known issues
- 3 out of 4 menu items do nothing
- 1 our of 4 menu items does not do what it should, and stores a file under a hardcoded path just for me, in `d:/cygwin64/tmp/`
- the menu disappears after IDE restart
- the menu keeps being visible despite "uninstall of the design package

It's not related to Delphi 12 or Delphi 12 + patch1, all above apply for Delphi 11.3.

It's just a work in progress :)

**Comment by michaliskambi** [comment]
I managed to fix both installing and uninstalling of new CGE menu items reliably. I have unhidden them now -- though they all only show _"TODO: Not implemented yet_" now.

**Comment by michaliskambi** [comment]
I managed to make all 4 menu items functional! Ha! This is working now, and makes adding/removing CGE paths from projects so easy... 

More testing will follow, but this is already available, and documented in https://castle-engine.io/control_on_form#_delphi_installation , _"When you create a new project and want to use CGE...". As usual, give Jenkins time to update downloads on https://castle-engine.io/download .

**Comment by peardox** [comment]
Obvious questions...

What happens if I put my project on GitHub? Are the paths are wrong for someone who clones it?
What happens if I add CGE to a project by accident e.g. a hello world - can I remove it?
If downloaded from Getit the CGE directory will be [Documents]/Embarcadero/Studio/[Delphi IDE version]/CatalogRepository/castle-engine - are these paths a problem?
Will it include Editor/View3DScene etc?
Will it deploy platform-dependant dlls?
Will CGE be re-compiled every time paths are added to a project?
Are any environment variables altered/added?
What is the effect of using castle-data urls in IDE vs Deployed?
Are directories added to browsing path - allowing IDE to find source files for IDE integration
Is Debug DCUs set?

A nice (but obviously not yet) feature would be to have help included (as discussed in Discord)

**Comment by michaliskambi** [comment]
> What happens if I put my project on GitHub? Are the paths are wrong for someone who clones it?

Yes -- they will be wrong.

I'm working now on menu items to add paths to global "Library path", so that paths are added to your Delphi for all projects. This will be recommended approach, once I get it working. It will use under the hood very similar code for paths manipulation.

> What happens if I add CGE to a project by accident e.g. a hello world - can I remove it?

There's a menu item _"Remove Engine Configuration from the Currrent Project"_ right next to the _"Configure Currrent Project to Use Engine"_ :) 

> If downloaded from Getit the CGE directory will be [Documents]/Embarcadero/Studio/[Delphi IDE version]/CatalogRepository/castle-engine - are these paths a problem?

Of course not. If you'll download from GetIt, everything will be already set up -- that's a simplest explanation for users.

> Will it include Editor/View3DScene etc?

Do you intend to ask whether CGE in GetIt will include editor, view3dscene etc.? 

Yes. It has to. GetIt is more than just a way to distribute packages, it's a way to run any installer from what I see, various component packages do various things including installing some special tools. We will absolutely want to have full CGE distributed this way, so including editor and other tools.

By this is getting a bit off-topic. This is not a ticket about GetIt.

> Will it deploy platform-dependant dlls?

A have a TODO to add this, yes. ToolsAPI has hooks to do stuff after building.

> Will CGE be re-compiled every time paths are added to a project?

Right now, all it does is adds paths to CGE sources. So CGE units are compiled along with the project. If you remove + readd the paths, the CGE will not be recompiled, as the compilation artifacts are already there, in project.

> Are any environment variables altered/added?

No. And they will not be. We're not using environment variables, since users don't understand environment variables, that's my general conclusion after supporting CGE.

> What is the effect of using castle-data urls in IDE vs Deployed?

Short answer: We make `data` subdirectory in project work, accessible as `castle-data:/xxx` URL, from everywhere. This includes "just running from Delphi IDE".

More details how it works on https://castle-engine.io/apidoc/html/CastleFilesUtils.html#ApplicationData-string- and https://castle-engine.io/manual_data_directory.php .

> Are directories added to browsing path - allowing IDE to find source files for IDE integration

There's no need to. We add CGE sources paths. Delphi has everything to treat CGE code just like your project code.

> Is Debug DCUs set?

Same as above: There's no need to. We add CGE sources paths. Delphi has everything to treat CGE code just like your project code. Including debugging.

**Comment by michaliskambi** [comment]
P.S. Discord or forums are better for such Q & A :)

**Comment by michaliskambi** [comment]
>  > P.S. Discord or forums are better for such Q & A :)
>    Yeah but this keeps everything together for later reference (and Discord is terrible to search for a specific Q from ages ago)

Indeed, Discord sucks for searching. OTOH https://forum.castle-engine.io/ is great for searching (both by humans and search ignores).

> >    I'm working now on menu items to add paths to global "Library path"
>  This is why I manually define CGEDIR in the delphi IDE them prefix all paths with {$CGEDIR} - ToolsApi will be able to do trhe same trick enabling portability (like downloading from GitHub would work flawlessly)

I'm looking at ToolsAPI how to do this best. Maybe we can define CASTLE_GAME_ENGINE at Delphi IDE level, and then we could have portable paths (using env variable) either globally or per-project, and everything is perfect. I'll experiment what is possible and best here.

**Comment by michaliskambi** [comment]
> A nice (but obviously not yet) feature would be to have help included (as discussed in Discord)

For now, I added menu items to open our website, API reference, and Patreon from menu.

The API reference uses the same code as editor -- so, as we talked on Discord also, it will open offline API reference (if the engine was installed from official installer; the future GetIt will come with these docs too).

**Comment by michaliskambi** [comment]
Deploying DLLs is in progress too.

![obraz](https://github.com/castle-engine/castle-engine/assets/1076978/e14d1e90-c224-4533-820b-181f511b8fac)

**Comment by michaliskambi** [comment]
I'll try to also stop using this closed GitHub issue as a devlog :) I'll post more updates on Discord or, once all done, in CGE news :)
