### ISSUE TITLE
KeepExisting stopped working?

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#57]
Hi, Michalis!
I've encountered a wierd problem.
Yesterday this code was working absolutely flawlessly:
```
TextureProperties.KeepExisting := 1;
...
(something).FdTextureProperties.Value := TextureProperties;
...
FreeAndNil(something);
...
FreeAndNil(TextureProperties);
```
But today I get a SIGSEGV at `FreeAndNil(TextureProperties)` as if it doesn't `KeepExisting` (the same problem I fixed for good by `KeepExisting`)... why? I'm sure I've fixed this issue yesterday and everything was working flawlessly afair. I don't see you've addressed any freeing operations checks in last commits (I've updated CGE to latest GIT since my last PULL request)...

**Comment by michaliskambi** [comment]
It works for me, I made a simple testcase: https://gist.github.com/michaliskambi/8bcec4a23306e39d1e2367db6a7b7f38

Can you send a testcase when it fails for you?

Indeed, there were no changes to the X3DNodes logic lately.

(BTW, I'll improve the TextureProperties stuff to allow doing 

~~~~
(something).TextureProperties := TextureProperties;
~~~~

instead of

~~~~
(something).FdTextureProperties.Value := TextureProperties;
~~~~
)

**Comment by michaliskambi** [comment]
(I did some API improvements around TextureProperties BTW:)

**Comment by eugeneloza** [comment]
Ok, I'll see it through. :)

**Comment by eugeneloza** [comment]
Hmm... I can't reproduce this one too. That's also very nice!
Maybe I was using some buggy version of something (Lazarus/FPC)?
