### ISSUE TITLE
Delphi Package Usability Tests

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#574]
Futher to #573 which now works and noting that this report is concerning the GetIt deployment as opposed to the instructions....

Also note that these are my own observations and it's your decision of course.

As a user downloading via GetIt (simulated here of course) after installation the user will have a TCastleControl in their Delphi Palette however the component is not yet usable as CGE path and Configure Delphi to use CGE have not yet occurred

If a TCastleControl  is placed on a form it is reasonable to assume that an app will compile - which it won't of course as there are no paths.

HOWEVER, if {CGEDIR}\packages\delphi\Win32\Debug (and Release) are added to Library for Win32 they will compile (further tests required) - these should go in the Debug DCU and Library entries respectively (per platform)
The same observation is true for Win64 - Linux64 is a more complex concern (TBC)

As CGEDIR is known by GetIt it can be pre-set by GetIt for Win32 and 64 with all versions available (Linux TBC) allowing for Out-Of-The-Box functionality

**The above is ONLY for GetIt deployment** (I checked GetIt can automate these things)

**Bug**
C++ does not currently work even with Path Set and Configure Delphi to use CGE
[bcc32c Error] CastleGL.hpp(5619): unknown type name 'PWGLSwap'

**QOL**
Configure to use CGE asks you to restart via a ShowMessage Dialog box. This would be much nicer if it was OK/Cancel and OK restarted Delphi - note that GetIt can restart anyway. This is the IDE equivalent of Developer Art in terms of usability :)

**Comment by peardox** [comment]
Compilation of https://github.com/peardox/CGEFormExamples (Pascal / VCL) - needs updating (note to self)

First time compile 

With Configure Delphi to use CGE
> Elapsed time: 00:04:12.8 (Win64)
> Elapsed time: 00:06:53.8 (Win32)

Without Configure Delphi to use CGE (but with paths above) - only set up for Win32 ATM...
> Elapsed time: 00:00:47.0 (Win32)

Note that these appear to be switchable (best of both worlds) - adding 517 paths forces full compilation while having them absent uses pre-compiled versions (everybody wins)

Also the timings are in a VM using a decent laptop so in real life prob similar to older and/or cheap machine

**Comment by peardox** [comment]
The C++ issues appear to be Installation related - it can't find it's system packages e.g. vcl.bpi - investigating

**Comment by peardox** [comment]
And fixed C++ (uninstall, re-install language option) but still get....

CastleGL.hpp
typedef unsigned __stdcall (*TwglSwapMultipleBuffers)(unsigned p1, const PWGLSwap p2);

[bcc64 Error] CastleGL.hpp(5618): unknown type name 'PWGLSwap'

**Comment by michaliskambi** [comment]
Thanks for the feedback!

As for C++ Builder error: fixed.

As for Getit:

> As a user downloading via GetIt (simulated here of course) after installation the user will have a TCastleControl in their Delphi Palette however the component is not yet usable as CGE path and Configure Delphi to use CGE have not yet occurred

Indeed when installed using GetIt we will want to perform the configuration ("Set Engine Path", "Configure Delphi to Use Engine") automatically. We know CGE location.

What does the "Configure Delphi to Use Engine" do (from GetIt, not from GetIt): I like to treat as an independent matter. That is, 

- Maybe we will switch to using DCUs instead of just recompiling CGE sources in each project.  I deliberately made the menu item generic _"Configure Delphi to Use Engine"_ (not e.g. _"Add Engine Source Paths to Delphi Library Path"_) to leave room for changes without the need to later adjust all docs. So that we can always just advise users "use "Configure Delphi to Use Engine"".

- But this is indepedent from GetIt. 

    If we go with "use DCUs", we'll make "Configure Delphi to Use Engine" do it, and GetIt setup also do it. 

    Until then (with current approach where we recompile CGE, and CGE is in "Library Paths") we recompile CGE sources, and GetIt is also fine with this. I saw FMXLinux relying on it too.

This doesn't really change any decision, I just say what is my line of thinking. "GetIt" is one thing (and for sure it will do whatever "Configure Delphi to Use Engine" does). Whether "Configure Delphi to Use Engine" adds only CGE sources or we recommend people to use precompiled CGE DCUs is another. At least in my mind :)

> Configure to use CGE asks you to restart via a ShowMessage Dialog box. This would be much nicer if it was OK/Cancel and OK restarted Delphi - note that GetIt can restart anyway. This is the IDE equivalent of Developer Art in terms of usability :)

I indeed wanted to do this -- i.e. a dialog OK / Cancel with "OK" doing Delphi reboot automatically. I agree it would be slightly better UX.

However, there's no ready API in ToolsAPI and friends to reboot Delphi. We could do "manually" (start some exe, kill the current process) but this isn't trivial (we want to make sure we do it only if user didn't cancel e.g. dialog "Do you want to save modified files", and we want to run the right exe -- regardless of the Delphi version, CE/not-CE, C++ Builder or not...). Overall the implementation of it looked risky, we would assume some stuff "what is Delphi doing" and risk assuming wrong in some case. So I resigned from it -- while the feature would be nice, at this point the risk our implementation would be half-broken is too large. 

I ToolsAPI will get API to "reboot Delphi", we'll use it then happily. Until then, just recommending users to reboot is better (more reliable for us).

**Comment by peardox** [comment]
An important feature of adding the DCU paths is that you can immediately drop a TCastleControl on a form and an app will compile without you doing anything else. Most people will do nothing rather than read _anything_.... So this does provide a fail-safe install that is more complex manually

The other thing is that if the paths are added then Delphi  will use that in preference to the DCUs

It would be really nice if the GetIt included enough git data so that you could git pull from the GetIT install location - My Documents\Embarcadero\Studio\xx.x\CatalogRepository\castle-engine (where xx.x is Version dependant) although such a capability is more for those who know what they're doing of course

Anyway - testing yet again then going to go down to 10.2.0 (which I expect to fail) to identify the lowest supported version (FMXLinux only goes down to 10.2.x so that's a good baseline to start testing at)

**Comment by peardox** [comment]
Cool - thought that one failed - one less to test so I'll start with 10.2.1

Note there are more C++ errors (report coming soon - trying to locate cause)
