### ISSUE TITLE
C++ Missing files (pre-alpha3 tests)

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#575]
Following to the Recommeded Instructions C++ 64 bit will not compile

For Win64 these files are not found leading to a compilation error

Win64 C++
castle_engine_fmx.a (FMX project)
castle_engine_vcl.a (VCL project)
castle_engine.bpi (All projects)

The solution to this issue is to _BUILD_ Win64 (all subprojects - design can prob be skipped of course) after Win32 has been installed. This adds the missing files. Note that it is also possible that a Win64 Pascal build would resolve this but that needs a clean test)

For some reason I'm not able to add Linux64 as a C++ platform but 

Linux64 Pascal appears to work (need confirmation as I fixed C++ so need to test without that step being done) I've also got a -lgtk3 error on that test so need to check my box before retest

This can be tested in a fresh VM by doing an install then immediately trying a Win64 C++ build (drop TCastleControl on form and try a build - FMX + VCL) -- ideally before any Pascal tests

**Comment by peardox** [comment]
Yeah - My Linux box neeed...

sudo apt install mesa-utils libgtk-3-dev libegl1 libcurl4 libpng-dev libz1 libopenal1 libfreetype6 libvorbisfile3

Pascal Linux64 compiles fine

**Comment by peardox** [comment]
Looks like FMXLinux has no C++ support so Linux is Delphi only

**Comment by michaliskambi** [comment]
You need to indeed _build_ for all platforms (Win32, Win64) to have C++ Builder working. This was documented at both C++ examples (and I just improved the text there):

https://github.com/castle-engine/castle-engine/tree/master/examples/delphi/cpp_builder/fmx

https://github.com/castle-engine/castle-engine/tree/master/examples/delphi/cpp_builder/window

"""Note that for C++ Builder you need to Build the packages for all your target platforms. It is not enough to only Install them for Win32 (Delphi IDE architecture) which is enough to allow usage from Delphi / Pascal."""

Aside from other compilation artifacts, building is also specifically needed for C++ Builder so that C++ header files (.hpp) are generated.

> Looks like FMXLinux has no C++ support so Linux is Delphi only

It's not about FMXLinux (only), the C++ Builder doesn't support Linux.

This is also known and documented. https://castle-engine.io/delphi_linux#_make_sure_your_delphi_supports_linux said already

"""Note that C++ Builder does not support the Linux target."""
