### ISSUE TITLE
C++ 10.2.1 Generics Type underclared? (pre alpha3)

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#576]
CastleShapeInternalShadowVolumes.hpp
typedef Castleutils::TStructList__1<T> TTrianglesShadowCastersList;

[bcc32c Error] CastleShapeInternalShadowVolumes.hpp(61): use of undeclared identifier 'T'

IDE Menu looks good
Pascal compilation OK
FMX Linux bad - installer does this...
![image](https://github.com/castle-engine/castle-engine/assets/1549219/88c06192-e3f7-420f-8e09-76775b6fb7dd)

Even though I'm testing on Tokyo - Delphi IDE buggy as hell in this release (JavaScript errors)

On to 10.2.2 which will hopefully do better

Leave this one open until I've done at least 10.2.2 + 10.2.3 as well as this should give us a baseline

**Comment by peardox** [comment]
10.2.2 Same as 10.2.1 in every 3way

**Comment by peardox** [comment]
10.2.3

C++ problem still present so needs looking at to support 10.2.x under C++
IDE actually works properly in this one
Still no FMXLinux

It appears then that if C++ is fixed then CGE will have a basseline of 10.2.1 (with dodgy IDE)
Pascal has a baseline of 10.2.1
FMXLinux will need a 10.3.x (TBC - they're next on the list)

Can close this at your will now as all findings are currently reported for 10.2.x

**Comment by peardox** [comment]
Aargh - 10.3.1 - still have the issue at the top of this bug 

[CLANG Error] CastleShapeInternalShadowVolumes.hpp(61): use of undeclared identifier 'T'

Think I'll skip to 10.4 to see if it goes away next

**Comment by peardox** [comment]
Also in 10.4.2

Is this a new worldwide bug I wonder - i.e. 12.0 as well? It's 3AM so time fer bed - I'll look at it tomoz

**Comment by michaliskambi** [comment]
I say to not put work into supporting C++ Builder 10.x. 

While it seems easy one-time fix, it will be a maintenance burden over time, having to continuously test and fix on all supported Delphi and C++ Builder versions. And automating these tests from Jenkins isn't always doable -- Delphi IDE does quite some logic "above" the command-line tools like dcc, 

It's a significant work -- to keep all the test environments installed, and occasionally test (not all tests are easily automated by Jenkins, due to having to use special params with Delphi cli tools that only Delphi IDE knows).

Let's first see if 

We don't yet know if there's any real interest in C++ Builder + Castle Game Engine. Let's see if people actually start using 
, so let's not put effort into supporting an edge-case of this

**Comment by michaliskambi** [comment]
I say to not put work into supporting C++ Builder 10.x. 

While it seems easy one-time fix, it will be a maintenance burden over time, having to continuously test and fix on all supported Delphi and C++ Builder versions. And automating these tests from Jenkins isn't always easy (and would be additional work), e.g. we don't automate C++ Builder compilation from command-line yet.

Let's first see if there's user  interest in C++ Builder + Castle Game Engine.

I documented on https://castle-engine.io/delphi we require 11.3 for C++ Builder.

> 11.3 compiles but can't find e.g. fmx.castlecontrol.obj (built libraries)

This is an independent bugreport. Please show details. Does compiling with "Build" works? 11.3 should definitely work, at least it did ~week ago.
