### ISSUE TITLE
Add source paths to Broswing Path (Delphi)

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#578]
If you make your IDE Addin sublicate the long list of paths in Browsing Path then you can Right Click on a CGE class/method/etc selecting Find Declaration will take you straight to it.

It also appears to aid in completion - e.g. type in viewport. and the list of valid methods (this may just be as I don't have source defined in my daily version tho)

**Comment by michaliskambi** [comment]
You can already do this.  I.e. "Find Declaration" and all other features work, since "Library Paths" contains just CGE sources. 

Just tested, from both TCastleWindow application (play_animation) and FMX (examples/delphi/fmx), using "Find Declaration" on identifiers like TCastleView, TCastleUserInterface jumps to declaration in CGE sources.

Code completion also work -- Ctrl+Space on `TCastleB` completes as expected, see screenshot

![obraz](https://github.com/castle-engine/castle-engine/assets/1076978/a119b469-5755-4bd1-9e2d-e45d71268f1a)


There's no need to extend "Browsing Path" when Delphi IDE already knows our sources through "Library Paths", from what I see.

**Comment by peardox** [comment]
Actually... You want it EITHER in Library or Browsing Path

So Configure Delphi to use ... should witch it to Library while turning this off should switch it to Browsing Path

This way if you use pre-compiled DCUs (like me) you can still access source while if you compile CGE every new build you also have it

**Comment by michaliskambi** [comment]
If we'll switch to using pre-compiled DCUs, then indeed we'll add sources to "Browsing Paths" instead of "Library Paths".

Until then, we recommend https://castle-engine.io/delphi_packages which adds sources to "Library Paths".

We don't want to put effort in our integration to try to support both approaches simultaneously -- this would be extra work, and also extra UX complication to users who would need to understand this, see more options in menus. 

In general: I very much want to keep recommending current "Configure Delphi to Use Engine" and say "for regular users, they should not care what it does, just click it and then enjoy CGE in Delphi". On a related note, I'm skeptical already about the current menu option _"Configure Only Current Project (for Current Platform and Debug/Release Config) to Use Engine"_ which makes sense sometimes, but mostly is a leftover from first implementation, and is already UX complication, and requires additional docs ( https://castle-engine.io/delphi_packages#_alternative_configure_only_current_project ). The less we have such complications, the better :)
