### ISSUE TITLE
Strange bug in CastleWiki

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#58]
Just saw a very strange bug in Castle wiki at Github: most text is enclosed within h1 tag. I'm not sure if this is the only page affected...
![2017-03-20-173045_1920x1080_scrot](https://cloud.githubusercontent.com/assets/10726162/24107410/4c4a2c0e-0d93-11e7-98e7-a07d0cd8e230.png)

**Comment by eugeneloza** [comment]
the page: https://github.com/castle-engine/castle-engine/wiki/Android

**Comment by michaliskambi** [comment]
Ouch. Yes, I see the bug too. Fixed! Thank you for spotting it, otherwise it could be there unnoticed for a long time.

Looking at the history ( https://github.com/castle-engine/castle-engine/wiki/Android-FAQ/_history ), this bad version is present since a long time, since "26 Aug 2016" (revision 6f9c717).

But I think it was not actually visible for so long (I *think* I would have seen it during this time). Reading GitHub blog, I see that they did some changes to GitHub renderer on 14th March (a week ago), https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown , and I suspect that this broke our page rendering.

So, since "26 Aug 2016" I have mistakenly used an undocumented feature of Markdown, which just stopped working on 14th March.

The bug was easy to fix (the diff https://github.com/castle-engine/castle-engine/wiki/Android/_compare/cf627278f8270cfc8c1e0bbb489daa269ebe5a5c...6f9c71703d36dd6710ec67916a54f1bd3f478c7b shows I added a space between some ~~~~, and suddenly a hash in code comment got interpreted as a header tag).

Going forward, I may write more pages using the Asciidoc syntax, instead of Markdown. Unlike Markdown, Asciidoc had a much more precise specification from the beginning, and I generally like Asciidoc since some time. (I think it worked quite well for the "Modern Object Pascal Introduction", much easier than LaTex or DocBook that I used in the past.)

Although, the change described on GitHub blog is generally a good thing -- they are trying to make the Markdown better. But, it did break a couple of our wiki pages.
