### ISSUE TITLE
OffScreen Rendering is creating blanks...

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#585]
As mentioned in Discord

https://github.com/peardox/TestOffScreen

Testcase with notes

TFrameExport.Grab(AContainer: TCastleContainer) is where it appears to be going wrong.

**Comment by michaliskambi** [comment]
I wasn't yet able to go in-depth what is wrong in this case, sorry! So I'm still unsure whether this is CGE problem or a problem in the testcase.

Comments for now:

1. Your `TFrameExport` does a few things (own viewport, own camera) that are not visualized, so it's not obvious if the viewport / camera settings in `TFrameExport` are correct.  By "correct" I mean "something should be really visible in camera from this position/orientation". 

    That is, the things you set up in `TCastleApp` (that get rendered on-screen) are quite different than what you set up in `TFrameExport` (that gets rendered off-screen).

    I'd advise to check this. My first suspicion is that your viewport + camera in `TFrameExport` really doesn't see anything.

2. Can you maybe simplify the testcase on your side (you know the code better) to make sure that what you want to render is also visualized in `CastleControl1`? Can you setup in `TCastleApp` the same conditions, the same setup (viewport, camera) as you do in `TFrameExport`? If then the `CastleControl1.Container.RenderControl` renders something different, things will be more clear (and will be obviously CGE bug -- if the on-screen and off-screen rendering should show the same, but don't).

3. I tested for now that saving viewport to image using `CastleControl1.Container.RenderControl(...)` basically works. That is, I have a correct image generated if I  replace the `TForm1.Button2Click` contents by this:

```delphi
procedure TForm1.Button2Click(Sender: TObject);
var
  //frame: TFrameExport;
  DrawableImage: TDrawableImage;
  ClearImage, ImageToSave: TCastleImage;
  W, H: Integer;
begin
  W := CastleControl1.Container.PixelsWidth;
  H := CastleControl1.Container.PixelsHeight;

  ClearImage := TRGBAlphaImage.Create(W, H); // will be owned by DrawableImage
  ClearImage.Clear(Yellow);

  DrawableImage := TDrawableImage.Create(ClearImage, true, true);
  try
    DrawableImage.RenderToImageBegin;
    CastleControl1.Container.RenderControl(CastleApp.Viewport,
      Rectangle(0, 0, W, H));
    DrawableImage.RenderToImageEnd;
    ImageToSave := DrawableImage.GetContents(TRGBAlphaImage);
    try
      SaveImage(ImageToSave, '../../new-test.png');
    finally
      FreeAndNil(ImageToSave);
    end;
  finally
    FreeAndNil(DrawableImage);
  end;

//  if Assigned(CastleApp) then
//    begin
//      frame := TFrameExport.Create(Self, 256,256);
//      frame.GrabFromCastleApp(CastleApp);
//      frame.Save('../../test.png');
//      frame.Clear;
//      FreeAndNil(frame);
//    end;
end;
```

To make it work, add a few more unis to the uses clause:

```delphi
uses Math,
  CastleProjection, CastleFilesUtils, CastleGLImages, CastleImages, CastleColors,
  CastleRectangles;
``` 

and move `Viewport` in `TCastleApp` to be public.

The result is correct rendering in `new-test.png`.

![new-test](https://github.com/castle-engine/castle-engine/assets/1076978/9e691e73-58ac-40d7-852e-98469b896026)

I realize that in this case it is similar to `Container.SaveScreen`, i.e. we use `CastleControl1.Container.RenderControl` to effectively get almost the same thing as we render on-screen, just the viewport is now on yellow background. Naturally `CastleControl1.Container.RenderControl` should allow to render anything, maybe things completely different than what is visible on-screen. But at least in above case we know the viewport / camera settings are good, because we also see the same thing.

**Comment by peardox** [comment]
Yeah, I just tried using the visible Viewport to render and that worked
Just seem to be having issues doing it off-screen

**Comment by peardox** [comment]
Just tried https://github.com/peardox/Tilely and that one works

I cribbed the offscreen code in TFrameExport from another project so there's a potential solution hidden in there...

**Comment by peardox** [comment]
OK - I'm very stupid.... Found my issue
