### ISSUE TITLE
Delphi Compilation Order

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#592]
I got the log below installing latest CGE

The process to repeat this is to delete the output dirs in packages/delphi/PLATFORM(S)
Note that the following are probbaly irrelevant

Switch to Debug
All Packages -> Build All for Win32, Win64, Linux64
Switch to Release
All Packages -> Build All for Linux64, Win64, Win32 

The most liklely culprit... (i.e. Win32 Release)
Now Multi-Select ALL EXCEPT castle_engine_window.bpl
Right Click
Install

It appears that the compilation order is important. If castle_engine_design is not installed first castle_engine_vcl won't install (as it already got installed by onme of the others or summat - confusing error message)

To solve first install design then the rest (not exhaustivley tested - wanna test out Kenney)

It should be noted that the order can be controlled by manually editing teh groupproj and re-ordering it, notably the Target Name="SomeProcess" parts placing deps at start. It can also be used to re-order how the tree appears in Project Browser
======= Log =======

[58C9EF8D]{delphicoreide280.bpl} PakList.TPackageList.AddPackage (Line 491, "PakList.pas" + 7) + $2F
[58CBBE02]{delphicoreide280.bpl} BasePasProjOpts.TProjOptsManager.InstallPackage (Line 1820, "BasePasProjOpts.pas" + 9) + $5
[58CBD08B]{delphicoreide280.bpl} BasePasProjOpts.TProjectOptions.InstallPackage (Line 2449, "BasePasProjOpts.pas" + 0) + $3
[58C7C178]{delphicoreide280.bpl} PasMgr.TPascalPackageCodeUpdater.InstallPackage (Line 13149, "PasMgr.pas" + 18) + $19
[58BB6BE5]{delphicoreide280.bpl} PkgContainers.TStdPackageProjectContainer.CommandHandler (Line 178, "PkgContainers.pas" + 8) + $7
[59B95E6B]{coreide280.bpl} ContainerIntf.TIDEProjectManagerMenuObject.Execute (Line 862, "ContainerIntf.pas" + 26) + $17
[59B97A96]{coreide280.bpl} ContainerIntf.TProjectManagerMenuItem.Click (Line 1110, "ContainerIntf.pas" + 18) + $22
[5DCC5C5B]{vcl280.bpl  } Vcl.Menus.TMenu.DispatchCommand (Line 3576, "Vcl.Menus.pas" + 5) + $2
[5DCC6ED6]{vcl280.bpl  } Vcl.Menus.TPopupList.WndProc (Line 4749, "Vcl.Menus.pas" + 4) + $E
[5B0A0AB4]{rtl280.bpl  } System.TMonitor.CheckOwningThread (Line 19889, "System.pas" + 2) + $0
[5B0A0DDA]{rtl280.bpl  } System.TMonitor.Exit (Line 20079, "System.pas" + 1) + $2
[5B0A0E36]{rtl280.bpl  } System.TMonitor.Exit (Line 20101, "System.pas" + 2) + $7
[5DB7821D]{vcl280.bpl  } Vcl.Graphics.FreeMemoryContexts (Line 7308, "Vcl.Graphics.pas" + 12) + $8
[5DB9C700]{vcl280.bpl  } Vcl.Controls.TWinControl.MainWndProc (Line 10321, "Vcl.Controls.pas" + 3) + $6
[5DCC6E25]{vcl280.bpl  } Vcl.Menus.TPopupList.MainWndProc (Line 4724, "Vcl.Menus.pas" + 2) + $5
[5B1B5C1C]{rtl280.bpl  } System.Classes.StdWndProc (Line 18517, "System.Classes.pas" + 8) + $0
[5D905AEB]{vclide280.bpl} IDEVirtualTrees.TVirtualTreeHintWindow.IsHintMsg (Line 7127, "IDEVirtualTrees.pas" + 7) + $13
[5DCE5263]{vcl280.bpl  } Vcl.Forms.TApplication.ProcessMessage (Line 11488, "Vcl.Forms.pas" + 23) + $1
[5DCE52A6]{vcl280.bpl  } Vcl.Forms.TApplication.HandleMessage (Line 11518, "Vcl.Forms.pas" + 1) + $4
[5DCE55E5]{vcl280.bpl  } Vcl.Forms.TApplication.Run (Line 11657, "Vcl.Forms.pas" + 27) + $3
[00BE80A2]{bds.exe     } bds.bds (Line 227, "" + 16) + $2

**Comment by michaliskambi** [comment]
> Switch to Debug
> All Packages -> Build All for Win32, Win64, Linux64
> Switch to Release
> All Packages -> Build All for Linux64, Win64, Win32

I'm not clear exactly what do you do.

Note that `castle_engine_design` is only for Win32 (it's only for Delphi IDE, so it doesn't need to support any other platforms).

And `castle_engine_vcl` is only for Win32/Win64, since VCL is only for Windows.

So you cannot really compile them for Linux64 (nor does it make sense, on Linux we only work through FMX). Note that in Delphi, each package has it's own platform and debug/release setting, maybe you got confused by Delphi UI. Switching the platform on the Delphi toolbar only switches the platform of *current* package in the `AllPackages` group, not all of them.

Yes, it means that when you do "Compile All" it will compile some packages for platform X, some for platform Y. That's how it works.

> If castle_engine_design is not installed first castle_engine_vcl won't install (as it already got installed by onme of the others or summat - confusing error message)

`castle_engine_vcl` doesn't depend on `castle_engine_design`, it's the other way around (and it has to): `castle_engine_design` depends on `castle_engine_vcl`. `castle_engine_vcl` registers VCL variant of TCastleControl, `castle_engine_design` adds Delphi IDE stuff like menu item.

> To solve first install design then the rest (not exhaustivley tested - wanna test out Kenney)

Installing `castle_engine_design` just implicitly installs the other ones. You will see a message that it got TCastleControl for VCL and FMX registered, which is actually done by `castle_engine_vcl` and `castle_engine_fmx`.

Note that our instructions on https://castle-engine.io/delphi_packages deliberately advise a more careful approach, _"""Right-click on all packages (except castle_engine_window.bpl) in succession and click "Install"."""_, because if something fails -- it is better if users report which step exactly failed. But if you're brave, you can just install `castle_engine_design` and that's it.

> The most liklely culprit... (i.e. Win32 Release)
> Now Multi-Select ALL EXCEPT castle_engine_window.bpl
> Right Click
> Install

Works OK for me. Both with debug and release (set of all packages). It compiles and installs all packages in succession. Tested on Delphi 12.

So, everything seems fine on my end. If you can reproduce it, please record a movie -- starting from unmodified CGE, show what you're doing. This should make it clear what are steps to reproduce. Admittedly, the error message seems like Delphi problem anyway.

**Comment by peardox** [comment]
From experience of other libraries what should happen is that e.g. design would be compiled as Win32 if an attempt to compile under e.g. Linux was made

**Comment by michaliskambi** [comment]
> From experience of other libraries what should happen is that e.g. design would be compiled as Win32 if an attempt to compile under e.g. Linux was made

I don't get how other libraries could do something else here. 

To be clear, `castle_engine_design` is only for Win32. You literally cannot compile it to any other platform. You cannot "attempt to compile it for Linux".

The Delphi IDE toolbar allows you to change the platform to something else, when you have selected a package that supports other platforms as well, like `castle_engine_base`. But that only changes the platform for selected package, not all packages in a group. It's just Delphi UI, not something we can/want change on CGE side.

**Comment by peardox** [comment]
If you right click and use 'Build All' in Linux then castle_engine_design is part of 'All' but gets compiled as Win32 as it has no Linux build setting

**Comment by michaliskambi** [comment]
> If you right click and use 'Build All' in Linux then castle_engine_design is part of 'All' but gets compiled as Win32 as it has no Linux build setting

Yes, because platform of `castle_engine_design` is Win32. You cannot switch `castle_engine_design` to Linux. And this is all correct. 

See above -- I think you are confused what "selecting Linux" in Delphi toolbar does. It only switches the platform of the *current package* in `AllPackages`. 

- If you have `castle_engine_base` as current, then the platforms list on Delphi toolbar includes Win32,Win64,Linux64 because `castle_engine_base` supports these 3 platforms. 

- If you have `castle_engine_vcl` as current, then the platforms list on Delphi toolbar includes Win32,Win64 because VCL works on any Windows.

- If you have `castle_engine_design`, then the platforms list includes only Win32 since  `castle_engine_design` is only for Win32.

Every package is only compiled for the platform which you have selected. The `castle_engine_design` has only one platform (Win32), you cannot change its platform, so it only gets compiled for Win32.

So you can e.g. set `castle_engine_design` to Linux, `castle_engine_fmx` to Win64, `castle_engine_design` to Win32, and that's what "Build All" or "Compile All" will do.

And it's all good. No matter what the combination is -- I wasn't able to reproduce the crash you mentioned in the description of this issue.

**Comment by peardox** [comment]
Wrong....

![image](https://github.com/castle-engine/castle-engine/assets/1549219/bf39d2ab-0543-45dd-8649-6a632c244115)

**Comment by michaliskambi** [comment]
Actually we were both right, just talking about different buttons :) We should have exchanged screenshots earlier! I thought you're using the button at the top-most toolbar, which does what I claimed. You were using a different button :)

![d](https://github.com/castle-engine/castle-engine/assets/1076978/8f1ba8ac-503a-4cb9-955a-9c66e6636ebf)

Anyhow, I don't see anything to fix here. 
- Regardless of what button you use to switch which packages, `castle_engine_design` will always remain Win32, as this is the only platform it supports. And this is OK. You can only install it for Win32. 
- I cannot reproduce any sequence of operations that leads to Delphi error. 
- Regardless of what order do you do, it should all work as long as in the end you install `castle_engine_design`.
