### ISSUE TITLE
ExposeTransform design Mode vs Runtime mode

### ISSUE THREAD

**Issue by Nabucodosor** [castle-engine/castle-engine#600]
I have a group of 3D models in glb format that if I manually load each model from the editor and assign the "ExposedTransform" everything works correctly, but if I load the "ExposedTransforms" when loading each model in runtime, some models do recognize the bones and others not, using exactly the same code.

I use this:

Enemigo1.Load(url3d);   //path to glb

(prev: Enemigo1.ExposeTransforms.Clear; )

Enemigo1.ExposeTransforms.AddStrings(enemybody1.Name); //name of bone to assign, this case: "BLACK_DRAGON_Head"

which was previously defined as:

enemybody1 := TcastleTransform.Create(nil);

But there are models that, although from the editor it works in Design mode, it does not obtain them in runtine mode, it returns alarms like this:

Warning: No TTransformNode (bone) named "BLACK_DRAGON_Head" found in the model

However, they do appear manually, and in other glb models I can assign the bones at runtime... what is wrong?

**Comment by michaliskambi** [comment]
Thanks for the report! Everything looks OK from the description, what you describe should work without issues.

Please submit a testcase to reproduce -- at minimum the sample glTF where it fails. Best: simplest project, with both code and data, to reproduce it.

**Comment by Nabucodosor** [comment]
[screenshots.zip](https://github.com/castle-engine/castle-engine/files/14957722/screenshots.zip)
[Uploading ExposedTransforms.zip…]()

**Comment by Nabucodosor** [comment]
> Thank you. Information on screenshots looks OK -- this should work.
> 
> Can you upload the sample project? It seems you have send above comment before the example project finished uploading, the link above
> 
> > [Uploading ExposedTransforms.zip…](https://github.com/castle-engine/castle-engine/issues/600)
> 
> indicates the download was interrupted, and I cannot download the zip of the sample project.

Ok:


try again please
[ExposedTransforms.zip](https://github.com/castle-engine/castle-engine/files/15127350/ExposedTransforms.zip)

**Comment by michaliskambi** [comment]
Thanks for the testcase!

Investigating, the `blackdragon.glb` file doesn't actually have a bone (transformation) named `BLACK_DRAGON_Head`. It has a transformation named `BLACK_DRAGON_ Head` (additional space before `HEAD`). I know, it's easy to miss since they look so similar, and space is so small in most non-monospace fonts.

To complicate matters more, since the space is not a valid Pascal identifier (and `TCastleTransform.Name` must be a valid Pascal identifier), the corresponding Pascal component is expected to have this space replaced with an underscore.  So the name for the corresponding Pascal component has to contain 2 underscores between `DRAGON` and `HEAD`: `BLACK_DRAGON__Head`.

Using the `ExposeTransforms` at design-time correctly sets up children `TCastleTransform` with name `BLACK_DRAGON__Head` (with 2 underscores). This represents the bone `BLACK_DRAGON_ Head` (space before `HEAD`).

Changing your run-time code to use a proper name (bone name with extra space, Pascal name for this bone with extra underscore) works OK:

```
bodyenemigo1.Name:= 'BLACK_DRAGON__Head'; //Exposed bone name assign to Transform name
Enemigo1.Add(bodyenemigo1); //Add tranform to Scene
Enemigo1.ExposeTransforms.AddStrings(['BLACK_DRAGON_ Head']); //Insert Exposed bone named "BLACK_DRAGON_Head" to list and
```

![obraz](https://github.com/castle-engine/castle-engine/assets/1076978/5bb60ccf-5d47-4f9b-adf3-48ae46cd83a6)

My recommendation is just to fix the model -- remove the extra space between `BLACK_DRAGON_` and `Head` and everything will be as expected :)

**Comment by jabipunk** [comment]
Your right!!, an error design!, thanks for your support and good job with your project
