### ISSUE TITLE
PositionFromWorld variant 

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#601]
Can we have a PositionFromWorld variant that doesn't do the MapRange pls

I'd write a helper but PositionToPrerequisites is private

Also this would avoid some FP value issues (as in x / y <> (x/y) * y)

**Comment by michaliskambi** [comment]
I don't understand -- what variant of `PositionFromWorld` do you need / propose? With what API? With what behavior?

The request to "implement it without MapRange" isn't clear, I  don't know why you're asking for it, and what alternative version do you need :)

**Comment by peardox** [comment]
This (PositionFromWorld without MapRange for Result)
```
function TCastleViewport.PositionToRaw(const WorldPosition: TVector3): TVector2;
var
  Matrix: TMatrix4;
  P: TVector3;
begin
  PositionToPrerequisites;

  Matrix := InternalCamera.ProjectionMatrix * InternalCamera.Matrix;
  P := Matrix.MultPoint(WorldPosition);
  Result := Vector2 (P.X, P.Y );
end;
```

**Comment by peardox** [comment]
Never mind...

**Comment by michaliskambi** [comment]
> Never mind...

I understand you don't need this anymore?

On my side, sorry for delay, I wanted to query what is the use-case. I mean, without `MapRange`, the results are in `[-1..1]` range, which seems hardly useful for most things. Having range `[0 ... EffectiveWidth]` seemed useful and natural in all my use-cases.

And if desperately needed, you can always scale it back to `[-1 .. 1]` . These are not big floats, I don't see a use-case where precision would really be terribly hurt. So, since this is a rare case in my eyes, it makes sense to just say that in these rare cases you can do 

```
V := Viewport.PositionFromWorld(...)
V := Vector2(
  MapRange(V.X, 0, EffectiveWidth, -1, 1),
  MapRange(V.Y, 0, EffectiveHeight, -1, 1));
```

I emphasize, I'm not against adding alternative versions -- but they must have a strong use-case, esp. if we can also avoid adding them because the desired result can be achieved without adding alternative version (and thus complicating CGE API).
