### ISSUE TITLE
TImageTextureNode - add a URL property?

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#605]
TImageTextureNode has FdUrl but this is a TMFString
It's also got two SetUrl variants but no GetUrl or URL property
OK, Something like...

> TImageTextureNode(Node).FdUrl.Items[0]

Works but it looks messy and is possibly prone to errors

Presumably a texture may have multiple URLs as Items is a TStrings of sorts?

Using EnumerateNodes I can easily get a list of textures I can then easily change but obviously want to see what it's already got before changing to ensure the  correct texture is changed

**Comment by michaliskambi** [comment]
Use `TextureUsedFullUrl` to learn what texture URL is loaded *right now*. It's defined at `TAbstractTexture2DNode` class, `TImageTextureNode` descends from it.

The `TImageTextureNode.FdUrl` is indeed an URL list -- deliberately, since the idea is that you have a list of URLs, and the browser uses the first one that works (file exists, file has a format supported by the browser etc.).

**Comment by peardox** [comment]
As I've said before it would improve documentation if the exposed parent properties etc were included on the API Docs
There is, of course, a problem here as e.g. TImageTextureNode has a lot of parents

**Comment by peardox** [comment]
Hmm

TImageTextureNode(Node).FdUrl.Items[0] returned 'dungeon_texture.png' (correct)
while
TImageTextureNode(Node).TextureUsedFullUrl  returned ''

**Comment by michaliskambi** [comment]
> As I've said before it would improve documentation if the exposed parent properties etc were included on the API Docs
> There is, of course, a problem here as e.g. TImageTextureNode has a lot of parents

Indeed, it is still a TODO -- https://github.com/castle-engine/castle-engine/issues/177

> TImageTextureNode(Node).FdUrl.Items[0] returned 'dungeon_texture.png' (correct)
> while
> TImageTextureNode(Node).TextureUsedFullUrl returned ''

It likely means it wasn't loaded yet (e.g. because wasn't rendered). A testcase would make it clear and avoid me guessing :)

See other TAbstractTexture2DNode stuff, https://castle-engine.io/apidoc/html/X3DNodes.TAbstractTexture2DNode.html , in particular you can just do `MyTexture.IsTextureLoaded := true` to load the image *now* (if possible at all).

Note that there's no problem if you just want to access `FdUrl.Items[0]` (after checking `FdUrl.Items.Count > 0`). It returns the 1st texture URL (relative) specified at texture node. Regardless of which URL, if any, was loaded. So `FdUrl.Items[0]` is something quite different than `TextureUsedFullUrl` but they have a defined meaning and you can use them.

**Comment by peardox** [comment]
Yeah, thought a testcase might be handy here. (so I'll write one)
