### ISSUE TITLE
Symbol '#' in file or folder names may create problems loading files

### ISSUE THREAD

**Issue by eugeneloza2factor** [castle-engine/castle-engine#613]
At least for LibPNG, at least on Windows:

![2024-06-03 19_48_49-Greenshot](https://github.com/castle-engine/castle-engine/assets/73470521/a734ea2a-ff42-4350-90d4-bfce8fd13a5e)

Reproduction:

1. Use project that needs to load a PNG file.
2. Rename project folder to `#`. (In the screenshot above the path is `v:\#\vinculike.exe`)
3. Try running the project.
4. Error.

**Comment by michaliskambi** [comment]
This proves our `RecognizeEvenEscapedHash` was a bad idea. This was introduced in https://github.com/castle-engine/castle-engine/commit/4fbc16b37bbf1b14f36a5c0d7b4eb2f834c60cb5 , I see I even documented for myself that this is dangerous:

> This is a hack and should not be used (prevents
>  from using actual filename with hash, thus making the escaping process
>  useless).

... but then I went on and used this :) In effect, we treated `#` inside filename as something special, and stripped `#` and everything after it in many cases (e.g. when detecting image MIME type).

I removed it now from CGE. I love the simplicity gain from removing this :)  I added auto-tests to make sure we don't break it again.

Note that this also removes one obscure (possibly I was the only one who used it :) ) feature from our model viewer: 

- Previously you could use "File -> Open" in castle-model-viewer, navigate to directory with Spine model, select a file like `lady.json`, and manually add anchor like `lady.json#skin:my_skin_name` in the dialog before pressing "OK" to open. So you abused the filename field in GTK open dialog -- adding there `#skin:my_skin_name`. It worked, even though `#` was then transformed to `%23` in URL, because of `RecognizeEvenEscapedHash`. 

- Now, castle-model-viewer will behave as if you try to open a file with `#` inside the filename, `lady.json#skin:my_skin_name`, which will fail (we cannot recognize MIME of it, we also could not read it). We also had similar feature with MD3, used in `examples/animations/md3_animations_tags/`. 

- After this, `#` in a *filename* is part of the filename (and `%23` in URL is nothing special). Only `#` in *URL* is special, designates anchor ("bookmark" in `TURI` terms), and then it can be used to indicate a skin of Spine / MD3. 

- I think this change is good. The UX of choosing skins this way, by abusing the open dialog, was wrong anyway :) For proper skin support, we should have dedicated property of TCastleScene to list available skin, select skin, and castle-model-viewer should have a regular UI (combo box or such) to allow selecting them.
