### ISSUE TITLE
TGrayscaleImage16

### ISSUE THREAD

**Issue by peardox** [castle-engine/castle-engine#619]
Basically a https://castle-engine.io/apidoc/html/CastleImages.TGrayscaleImage.html with Colour being a 16 bit Integer

Why?

[ASTER](https://asterweb.jpl.nasa.gov/gdem.asp) 3 has DEM (Digital Elevation Maps) of the entire earth at 30m resolution

The format of these files is a 9 layer TIFF with each pixel being an Int16 in the ramge -9999 (void value) to 8849 (Top Of Everest) with 0 being sea level of course

Reading in the TIFF **should** produce a 3601x3601 height map (the top + left edges are the same values as the next grid's left + bottom edges

The layers in the TIFF have dimensions of 1 + (3600, 1800, 1200, 900, 450, 400, 225, 56, 44) but I doubt we can read the smaller versions directly

Using a sample image of Tenerife (as it's a small island with a big Volcano) as a sample you'd end up with a hight-map that looked something like this....

![teneriffe](https://github.com/user-attachments/assets/e2673e8a-bc3a-4565-bf35-5573c50257ee)

[Tenerife](https://en.wikipedia.org/wiki/Tenerife) has a volcano that rises to 3.7km

Given that as a 16 bit Integer it should be possible to pass that to e.g. a shader for testing and/or construct a mesh

One last issue I'll mention on the assumption that you'll want to try this out yourself is that the maps will look squashed the further north or south you go. To make the height (and therefore shape) of a map familiar you need to scale it by 1/cos(latitude) owing to the universal familiarity of the mercator map projection

Also I have every DEM file of the world locally so if you want easy access for your own purposes I can stick them on the Pi as it's got plenty of space (took me about 18 hours to download them all even automated - crappy single thread solution used). Total size of wold as zips (with extra info) = 378Gb

**Comment by michaliskambi** [comment]
We support float-based images, like `TGrayscaleFloatImage`, that use `Single` type for each channel value (instead of `Byte` used by `TGrayscaleImage`). Images with higher precision than 8-bytes, like 16/32-bit TIFF, like 16-bit PNG, like float-based KTX are all read to such float-based formats. See:

- https://castle-engine.io/wp/2024/07/12/float-based-images-e-g-for-precise-terrains-full-support-4-float-based-image-classes-passed-to-gpu-and-shaders-loading-16-bit-png-loading-float-based-ktx-loading-16-32-bit-tiffs-castle-image/ ,

- https://github.com/castle-engine/test-high-precision-terrains .

It was specifically added to support high-precision terrains, just like the use-case you describe, and it rocks :)

And the `Single` type can reliably hold all `UInt16` values, see https://github.com/castle-engine/castle-engine/commit/b3074a9763312f839a90d77b4189e830b8a229cc .

We do not want to support dedicated 16-bit images types (like `TGrayscaleImage16`), as it would a significant additional maintenance (4 more image types, since then we shall support all versions - grayscale, grayscale+alpha, RGB, RGBA) for not much gain. As above -- "high-precision terrains" use-case is covered by float-based image support, and `Single` can hold all `UInt16` values. The only gain would be that `UInt16` is 2x smaller in memory than `Single`, but then, such images (whether 16-bit based or float-based) are needed very seldom in practice.

**Comment by peardox** [comment]
Yeah, thought you might have done this

Does the optional TIFF via libtiff read sub-images? The only way I noticed there were 9 images in the tiffs was by opening one of the DEM files in GIMP

If you want any of the DEM files they're on the Pi in /opt/USGS - zip folder has 23k individual ZIP files with two files in each - the _dem.tiff one being the relevant DEM GeoTIFF

**Comment by michaliskambi** [comment]
> Does the optional TIFF via libtiff read sub-images? The only way I noticed there were 9 images in the tiffs was by opening one of the DEM files in GIMP

The CGE API does not expose sub-images in TIFF (or any other image formats, except [KTX](https://castle-engine.io/ktx) and [DDS](https://castle-engine.io/dds); only for KTX and DDS we have implemented "image may contain many subimages", but it is still internal for them, in `CastleInternalCompositeImage`, as their subimages are usually supposed to be all loaded to GPU as one texture e.g. with mipmaps).

As for the underlying libraries, probably "yes", they do support it:

- We use Vampyre Imaging Library for TIFF, I think it handles subimages in TIFF, judging from the `TTiffLibFileFormat.LoadData` implementation having `var Images: TDynImageDataArray; OnlyFirstLevel: Boolean` parameters (see https://github.com/castle-engine/castle-engine/blob/17ede32586292249b0ba07652b612f9146b275b2/src/vampyre_imaginglib/src/Extensions/LibTiff/ImagingTiffLib.pas#L180 ).

- And it's using `TIFFNumberOfDirectories`, `TIFFSetDirectory`  from libtiff, see https://libtiff.gitlab.io/libtiff/functions/TIFFquery.html#c.TIFFNumberOfDirectories

So, 

- while you cannot use CGE API to get subimages in TIFF (and I think I don't want to add it now to CGE -- too little gain, I don't want to complicate our API more, let this be a feature for dedicated image processing libraries like Vampyre)

- most likely you can use Vampyre Imaging API directly to get subimages. And then loading a single image from Vampyre to CGE images is easy, see https://github.com/castle-engine/castle-engine/blob/17ede32586292249b0ba07652b612f9146b275b2/src/images/castleimages_vampyre_imaging.inc#L23 -- this is handling all Vampyre -> CGE conversion. The `Load_VampyreImaging` routine is not exposed now, but it is simple enough that I would say to go ahead and copy it into your project :), possibly trimming down to the formats you really need.
