### ISSUE TITLE
Strange error in TRGBAlphaImage alpha

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#62]
In a very simple code:
````
  Img := LoadImage('1.png', [TRGBAlphaImage]) as TRGBAlphaImage;
  SaveImage(img,'1a.png');
````
the simple Load-Save fails to keep "alpha channel". Yes, there is a "hidden" alpha=0 RGB-image at 1.png... but it should remain alpha=0.
I.e. SaveImage treats only (0,0,0,0) as transparent, but not (value,value,value,0).
See the attachment with test-case.
It fails at images "1.png" and "5.png", while absolutely identical images (made just by rotating '1.png' - they also contain the 'hidden' part) work fine. Image 1.png contains a "hidden alpha=0" sub-image, which I've tried to remove with GIMP -> 5.png. Eraser brush didn't remove the hidden image, so I've over-painted it with black color (0,0,0,255) and then erased it (0,0,0,0). Eventually SaveImage interprets non-transparent black color (0,0,0,alpha<>0) as transparent...
There are some other artefacts relative to this issue (harder to reproduce, but "appearing" at DrawFrom when buggy alpha channel is interpreted in a wrong way after saving)...
P.S. I'm not exactly sure if it's SaveImage the one which fails. However, saving an image with "buggy" alpha channel (e.g. by DrawFrom) depends on what else is present at this image. E.g. mixing one buggy image with a normal one produces a normal result. Sometimes, copying and saving a part from a "normal image" yields a buggy result.
It might be the problem of accidentally using AlphaDecide based on top-left pixel of the image (the symptoms witness about that)? When, e.g. by some accident HasAlpha is not set properly?
[LoadSaveImageError.tar.gz](https://github.com/castle-engine/castle-engine/files/871612/LoadSaveImageError.tar.gz)

**Comment by michaliskambi** [comment]
In short: fixed, and I used your PNG images to create an automatic testcase to make sure it will not happen again:)

Explanation:

The PNG image format offers various ways to save the alpha information -- it may be saved "explicitly" as alpha values for each pixels, or it may be saved as "this special color value should be interpreted as transparent" (tRNS chunk, see http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html ). Also, a palette of colors may be used instead of a "true color" representation (explicit value of each pixel), which adds even more options.

All these options are nice, but they should be used with care otherwise you can destroy the image information, in particular the RGB values are places where alpha=0. This is what happened here.

What I did:

1. We can split TRGBAlphaImage into TRGBImage + TGrayscaleImage to test the state of the image in the CGE memory. This way we can see that the image is correct after LoadImage, so it's the SaveImage that breaks it.

    See https://gist.github.com/michaliskambi/3ca5acfa1d57a26c483d28bed8ef79ef

2. As it happens, we have two implementations of loading/saving PNG images: one is using the libpng library, the other one uses fcl-image FPC units (FPImage, and numerous FPReadXXX and FPWriteXXX units). You can change

    ~~~~
    {$define CASTLE_PNG_USING_FCL_IMAGE}
    ~~~~

    to

    ~~~~
    { $define CASTLE_PNG_USING_FCL_IMAGE}
    ~~~~

    in `castle-engine/src/base/castleconf.inc` to test the implementation using libpng. Result: The libpng implementation doesn't have this error.

    So the bug is somewhere inside fcl-image units. (Or in our code communicating with fcl-image, but it's quite straightforward, see castle-engine/src/images/images_fpimage.inc .)

    (By default, CGE uses fcl-image units for PNG, as it's easier to use on Android/iOS, it doesn't require any external libraries.)

3. As it happens, we actually use a fork of FPC's FpWritePNG unit, in CastleInternalFPWritePNG. It was forked to fix http://bugs.freepascal.org/view.php?id=28082 , which is still present in FPC 2.6.4 and 3.0.0 that we want to support (it's only fixed in FPC 3.0.2).

    Testing, this bug is already fixed in the FPC trunk version of FpWritePNG. Some of these fixes did it: http://svn.freepascal.org/cgi-bin/viewvc.cgi/trunk/packages/fcl-image/src/fpwritepng.pp?view=log (I have not investigated which one).

    Soo.. I just refreshed our fork, taking latest FPC's FpWritePNG unit -> for our CastleInternalFPWritePNG. And everything is fixed now:)

I also added an automatic testcase to see that reading + writing your PNG files preserves their contents, RGB and alpha channels.

Thanks for reporting!

**Comment by eugeneloza** [comment]
Great!!! Thanks a lot!

**Comment by eugeneloza** [comment]
[Confirmed!] Everything working flawlessly in complex cases.
