### ISSUE TITLE
"Configure Delphi to use engine" corrupts Delphi Search Path lists

### ISSUE THREAD

**Issue by cernisr** [castle-engine/castle-engine#626]
If you have any spaces in paths in a Delphi Search library list, the "Configure Delphi to use engine" command will corrupt the list. The cause is in castleinternaldelphidesign.pas in TCastleDelphiIntegration.AddPaths, on the line "SrcDirs.DelimitedText  := Paths;". 

From the Delphi documentation:

"When assigning DelimitedText, the value is parsed as SDF formatted text. For SDF format, strings are separated by Delimiter characters **or spaces**,"..."Spaces and Delimiter characters that are not contained within QuoteChar marks are delimiters." [my emphasis]

Since the registry entry does not contain delimiter characters around the individual entries, any entry containing a space will be split into multiple entries.

**Comment by michaliskambi** [comment]
Thank you enormously for the report and spot-on analysis. Fixed. I tested interactively, I also added an auto-test to reproduce the bug and later confirm the fix.

![image](https://github.com/user-attachments/assets/752efa5d-f50d-492e-b0ec-c9e4f35da1e5)

Since this is critical (we don't want to break people's Delphi config...) I consider this a "hot fix" and this commit will update the [7.0-alpha.3](https://castle-engine.io/wp/2024/08/21/7-0-alpha-3-release-physics-blending-batching-shadows-delphi-packages-linux-ui-masks-lots-of-editor-ux-android-ios-work-float-textures-vs-code-sketchfab-more/) release. So everyone who downloads `7.0-alpha.3` soon will have this fix. 

It will be available in [official downloads](https://castle-engine.io/download) just as soon as GitHub Actions finish a few auto-tests, in roughly 3 hours. You can observe [this page](https://github.com/castle-engine/castle-engine/compare/v7.0-alpha.3...master), when it no longer shows the commit "_Fix "Configure Delphi to Use Engine" (and the reverse) operations_" then it's included in the release.

**Comment by michaliskambi** [comment]
P.S. In a hindsight, I should have bumped the version number for the fix, like `7.0-alpha.4` or `7.0-alpha.3.1` . I should not have "silently replaced" the release of `7.0-alpha.3`.

In my defense: I wanted to push this fix quickly, and I was afraid of having even more complicated version number :) But then, bumping the version number would be clearer --- people would know "oh, this is new version, worth downloading for extra fix". Anyhow, this is just a note for myself for future. I'll do it better. We should also have shorter version numbers after 7.0.

The most important thing -- it is fixed, [the latest downloads](https://castle-engine.io/download) contain this fix, all is good from now :) I'll make a note about it in news soon.
