### ISSUE TITLE
Add function to report version, date-time and commit hash when CGE built

### ISSUE THREAD

**Issue by janadamec1** [castle-engine/castle-engine#630]
It would be great if CGE could report the version when it was built. It could help identify (historical) issues. I am attaching screenshots from Android Studio and Qt Creator below.

My suggestion will be to report current:

- castle_base.lpk version (but not entirely needed), 
- date,
- commit hash

**Maybe build-tool could do this at first?** (while we would ignore all other ways to compile projects)

<img width="613" alt="Android Studio version" src="https://github.com/user-attachments/assets/d066dc4f-4fc6-4748-84cd-b93403363212">

![Qt Creator version](https://github.com/user-attachments/assets/11ecef12-b3ff-40d6-bf09-88021ad71494)

Of course, I can help.

**Comment by janadamec1** [comment]
Inspiration: [StackOverflow: Include Git commit hash and/or branch name in C/C++ source](https://stackoverflow.com/questions/44038428/include-git-commit-hash-and-or-branch-name-in-c-c-source)

**Comment by michaliskambi** [comment]
It's already done:

- From your Pascal programs: use `CastleEngineVersion` constant from `CastleUtils` unit.
- From command-line: `castle-engine --version`.

When you run the engine from official downloads https://castle-engine.io/download , these version numbers contain the GIT hash, and look like `'7.0-alpha.3.snapshot (commit xxx)` . It is also automatically output as one of the first things to [log](https://castle-engine.io/log).

Note: If you clone the GitHub repository and compile build tool yourself following https://castle-engine.io/compiling_from_source.php , these version numbers do not contain a hash -- simply because it would be too risku to make it work on all systems, with all scripting systems etc. Our build tool has to be compiled as easily as possible, without causing errors e.g. because someone doesn't have `git` in `$PATH`. 

So the GIT hash is only present there in official downloads https://castle-engine.io/download , it's placed there during `tools/internal/pack_release/pack_release.sh` execution.
