### ISSUE TITLE
Error: Operator is not overloaded: "TGenericVector3" = "TGenericVector3"

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#73]
Hmm... something as simple as comparing two TVector3 is not working... Maybe, I'm missing something?
Using `MyVector1.Equals(MyVector1,MyVector2)` doesn't look nice to me...

**Comment by michaliskambi** [comment]
This is deliberate.

Reason: It is not obvious how to compare floating-point values: you either 
- compare with some epsilon tolerance (this is done by `TVector3.Equals`) 
- or compare perfectly (this is done by `TVector3.PerfectlyEquals`), knowing that you risk that some seemingly-equivalent calculations yield slightly (by a very small epsilon) different results.

The reason of this choice is that floating-point calculations are never precise. You know, for sure, that `3.0 = 3.0`. But you should never assume that `3.0 = 7.0 - 4.0`. It may happen that the left side is actually represented as `3.000001` and the right side will be calculated to `2.999999`. (Although, I just tested, this particular example yields true... but you get the idea :)

The standard = operator on floats, like  `MyFloat1 = MyFloat2` (when `MyFloat` is Single, Double or Extended (or Float, defined in Math unit, which equals Extended)) does a *perfect* comparison (in Pascal, C, C++, Java, C#...). And it's a source of small errors, because in most cases, you instead want to compare with some tolerance (which is done by `SameValue` from `Math` unit).

To avoid this trap, we force you to explicitly "spell out" which comparison you want. You usually want to use `Equals`, and you very seldom want to use `PerfectlyEquals` (thus, `PerfectlyEquals` has a longer name).

Readability note: I always use `TVector3.Equals(V1, V2)`, this looks a bit cleaner than `V1.Equals(V1, V2)`.

I could add a single-argument non-class method called Equals, then you could write `V1.Equals(V2)`. I thought about it, and deferred it for now. Do you think it would be useful, does it look better?

**Comment by eugeneloza** [comment]
Sorry, my bad as usually :)
I keep on forgetting that it's a class method, not just a function. That indeed looks nice and clean.
Closing this one.
