### ISSUE TITLE
A4Tech x750 mouse DPI problem [WINDOWS]

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#75]
Well, my old, cheap and reliable all-purpose A4Tech OP-35D optical mouse finally died. I've decided to by a A4Tech x750 laser mouse. It works and feels a bit more comfortable (not mentioning that it's 5 times more expensive), and there are no problem on Linux.
However, on Win7 I've experienced a strange behavior in Caste Game Engine (Decohrence).
There is a DPI switch button on the mouse (I really needed it (sarcasm)), and it has several switchable modes from 100 DPI to 3600 DPI.
OP-35D worked "fine" both in games and in Windows software. But, x750 on "average DPI" settings is too fast in Windows software and too slow in Decoherence window with `MouseLook = true` (and TES: Oblivion / fullscreen too, so it's not just CGE :) I haven't tried it anywhere else yet).
This isn't a critical problem, of course. However, maybe there is a way to "understand" and "take into account" mouse DPI (it should be reported by a driver)?

**Comment by michaliskambi** [comment]
Hm, reading your mouse DPI may be possible. But it may be a non-cross-platform solution. So I don't know if it's worth our time to implement, especially if other games don't do it too...

Instead, you can simply let the player adjust the sensitivity of mouse look. Just adjust `TWalkCamera.MouseLookHorizontalSensitivity` and `TWalkCamera.MouseLookVerticalSensitivity`. If you use `CastlePlayer`, then the instance of `TWalkCamera` is inside `Player.Camera`.
Allow player to adjust these values, save them in a config file ( https://castle-engine.sourceforge.io/manual_user_prefs.php ) and you're done:) My old game "The Castle" https://github.com/castle-engine/castle-game/ is doing it.

I know, it's not the same -- it will not automatically detect and adjust to your fancy new hardware button :)

But the advantages is that it will 
- Work for everyone, or any hardware and any OS.
- Allow to also be adjusted "because personal preferences". Maybe some people prefer to rotate slower or faster with mouse.

**Comment by eugeneloza** [comment]
Wow, that really looks like a nice alternative solution! I'll do it this way. Thanks a lot.
