### ISSUE TITLE
Caption unreadable problem

### ISSUE THREAD

**Issue by trustyboy** [castle-engine/castle-engine#81]
Hi,I found that if the caption value contain chinese characters in the CastleEngineManifest.xml,after install the game,the caption will be unreadable.It the CastleEngineManifest.xml file(you can modify from the drawing_toy demo)
`<?xml version="1.0" encoding="utf-8"?>
<project name="drawing_toy"
  caption="测试"
  qualified_name="net.sourceforge.castleengine.drawingtoy"
  standalone_source="drawing_toy_standalone.lpr"
  game_units="Game">
  <package>
    <include path="README.txt" />
  </package>
</project>
`

**Comment by michaliskambi** [comment]
I tested it today, and I can reproduce it on Windows (it works fine on Linux). Did not find a solution yet, will try again around next weekend.

I got sidetracked with another task (not really related to this one, but related to Android building on Windows) to upgrade Gradle usage in CGE, to work with Java 9 on Windows. This turned out to be a larger task, for now in branch https://github.com/castle-engine/castle-engine/tree/upgrade-gradle :)

I will keep you updated once I have a solution to this:)

**Comment by michaliskambi** [comment]
P.S. A screen on Android when compiling from Linux, where it works:)
![screenshot_20180129-165843](https://user-images.githubusercontent.com/1076978/35542707-b48ea6c0-0561-11e8-8704-4f0f24b6f2a0.png)

**Comment by michaliskambi** [comment]
Fixed, on Windows and Linux everything should be OK now:) Please test and reopen if you still have troubles.

**Comment by trustyboy** [comment]
@michaliskambi Wow,it is OK now!
