### ISSUE TITLE
dmAlphaBlend

### ISSUE THREAD

**Issue by eugeneloza** [castle-engine/castle-engine#9]
I've made a patch to support dmAlphaBlend, however, I couldn't figure out how to push it to github... Still to new to all those forks and etc... I see that the file structure has been changed on 10th October, but my fork I've downloaded yesterday had different file structure... Maybe this feature was already implemented and I have to update my branch somehow?
Well... here's the patch:
[castleimages.pas.zip](https://github.com/castle-engine/castle-engine/files/51287/castleimages.pas.zip)
[AlphaBlendTest.zip](https://github.com/castle-engine/castle-engine/files/51288/AlphaBlendTest.zip)
I've used https://en.wikipedia.org/wiki/Alpha_compositing formula for alpha-blending. And it works only for Vector4byte type pixels.

**Comment by tsr8** [comment]
Detailed instructions about how to proposing patches are on GitHub help. You will need to find "creating pull request" and "syncing a fork"  phrases.
My way:
1. You need a fork
2. Keep your fork synced to master
3. Make changes
4. Commit changes to your local repository
5. Push local repository to your fork
6. Create a pull request
Its only my easy way. There are good practices described: https://help.github.com/articles/what-is-a-good-git-workflow/

**Comment by eugeneloza** [comment]
Thanks! I'll try that tomorrow.

**Comment by michaliskambi** [comment]
Thanks! Answering the comments:

1. Using the GitHub "pull requests" is quite easy, like @tsr8  says:) An alternative is to simply send a "patch", which is an output of "git diff" or "svn diff" commands. Just attach the resulting "patch" file to an issue on GitHub (or to the ticket on SourceForge --- whichever you prefer). The patch is also very comfortable for applying, just like a pull request:)

  The important thing is to base your changes on the latest engine sources version. So make sure you update your working copy ("git pull --rebase" or "svn up") often, and resolve any conflicts (which may arise if the file you modify changed in the meantime).

  I think you also have the SVN commit rights actually:) I gave them to you a while ago when you planned to improve the engine documentation:) Feel free to commit the simple changes yourself --- I watch SVN and will eventually review them anyway. Although if you're unsure, it may make sense to submit them as issue (or pull request) like this.

2. As for the change itself:

- The organization of code related to DrawCore indeed changed a bit (to support more combinations of from/to image types, there were a few moves and renames:). Can you send the patch (or create a pull request) that applies to current engine sources, also taking into account my suggestions below?:)

- I would suggest to change the name. dmAlphaBlend is confusing, since we already have dmBlend operator that also works on alpha. Existing dmBlend is not as smart as your code in the case when the destination already has non-trivial alpha, it doesn't mix the alpha as smartly as the equations you implemented (but then, it's faster). I would probably call your operator as dmComposite or dmBlendSmart. 

- Add a brief description what is does at the constant declaration inside TDrawMode type, as we do with other types (dmBlend and dmAdd).

- They were some organization changes around DrawXxx methods, to support more from/to combinations. The name changed from DrawCore to DrawFromCore, and the implementation moved to castleimages_draw.inc file. So most of your implementation should go there.

- You will also find there examples how to easily iterate over image pixels (use "Inc" on pointer types like "PVector4Byte"). See e.g. how dmBlend is done, inside TRGBAlphaImage.DrawFromCore . More precisely, the case when you draw from TRGBAlphaImage to another TRGBAlphaImage is covered in "SourceRGBAlpha" nested procedure inside TRGBAlphaImage.DrawFromCore.

- Do not add your implementation to TCastleImage.DrawCore or TCastleImage.DrawFromCore. Instead add it to TRGBAlphaImage.DrawFromCore (and other TXxxImage descendants, if you want to make it supported by other classes). Inside TRGBAlphaImage.DrawFromCore you already know that the destination class is TRGBAlphaImage, so no need to check it.

  You still need to check the Source type --- do this by "is Xxx" operator. (Don't simply compare PixelSize, as PixelSize tells you the size but not the "interpretation" of pixel data.) Remember that source and destination classes of images may be different. This makes implementing these blend modes difficult (and explains the large size of castleimages_draw.inc), but it's also very useful in practice. It's absolutely Ok to implement only a part of them --- but document it in docs at "dmCompsite" definition.

- Don't define type PPixel4, simply use existing PVector4Byte. The existing code in castleimages_draw.inc should also serve as a good example of this:)

Please ask if you have any questions:)

**Comment by eugeneloza** [comment]
Phew... seems I've managed updating my fork :) Pushed the commit, I've included all your suggestions, thanks.
